/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;

import static beleris.es.finalinformationmanager.MainErrorManager.ShowDError;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import static ccpd.es.p8config.P8Config.PConfig;
import ccpd.es.p8dbmanager.FDBManExtra;
import ccpd.es.p8pdfmanager.P8PdfManager;
import org.openide.LifecycleManager;

/**
 *
 * @author edavid
 */
public class JPCreateOtherDocuments extends javax.swing.JPanel {

    private static final long serialVersionUID = 4575372395674541577L;

    /**
     * Creates new form PrintDocuments
     */
    public JPCreateOtherDocuments() {
        initComponents();
        LoadData();
        // PConfig.setHelpConfig(this.getName(), "Crear Otros Documents", "CreateOtherDocuments.html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jUpperMenu_Panel = new javax.swing.JPanel();
        jBSecurityMeasuresDocs = new javax.swing.JButton();
        JBImpactEvaluationDocs = new javax.swing.JButton();
        jBTratRiscks = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPSecurity_MeasuresPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(JPCreateOtherDocuments.class, "JPCreateOtherDocuments.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jUpperMenu_Panel.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jBSecurityMeasuresDocs, org.openide.util.NbBundle.getMessage(JPCreateOtherDocuments.class, "JPCreateOtherDocuments.jBSecurityMeasuresDocs.text")); // NOI18N
        jBSecurityMeasuresDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSecurityMeasuresDocsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jBSecurityMeasuresDocs, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBImpactEvaluationDocs, org.openide.util.NbBundle.getMessage(JPCreateOtherDocuments.class, "JPCreateOtherDocuments.JBImpactEvaluationDocs.text")); // NOI18N
        JBImpactEvaluationDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBImpactEvaluationDocsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(JBImpactEvaluationDocs, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBTratRiscks, org.openide.util.NbBundle.getMessage(JPCreateOtherDocuments.class, "JPCreateOtherDocuments.jBTratRiscks.text")); // NOI18N
        jBTratRiscks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTratRiscksActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jBTratRiscks, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(JPCreateOtherDocuments.class, "JPCreateOtherDocuments.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jUpperMenu_Panel.add(jButton1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(JPCreateOtherDocuments.class, "JPCreateOtherDocuments.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jUpperMenu_Panel.add(jButton2, gridBagConstraints);

        jSplitPane1.setLeftComponent(jUpperMenu_Panel);

        javax.swing.GroupLayout jPSecurity_MeasuresPanelLayout = new javax.swing.GroupLayout(jPSecurity_MeasuresPanel);
        jPSecurity_MeasuresPanel.setLayout(jPSecurity_MeasuresPanelLayout);
        jPSecurity_MeasuresPanelLayout.setHorizontalGroup(
            jPSecurity_MeasuresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPSecurity_MeasuresPanelLayout.setVerticalGroup(
            jPSecurity_MeasuresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPSecurity_MeasuresPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String GetSecurityMeasures() {
        String sreturnvalue = "las medidas de segurdad son las siguientes: ";

        if (!SMLACL.isEmpty()) {
            sreturnvalue += " listas de control de acceso,";
        }

        if (!getSMLADL().isEmpty()) {
            sreturnvalue += ", delegación de autorizaciones";
        }
        if (!SMLASM.isEmpty()) {
            sreturnvalue += ", medidas de seguridad alternativas";
        }

        if (!getSMLAUTH().isEmpty()) {
            sreturnvalue += ", autorizaciones";
        }

        if (!SMLDTMAN.isEmpty()) {
            sreturnvalue += ", encargado del tratamiento de datos";
        }

        if (!SMLEDTMAN.isEmpty()) {
            sreturnvalue += ", tratamiento externo de datos";
        }

        if (!SMLFIDES.isEmpty()) {
            sreturnvalue += ", descripción de los ficheros";
        }

        if (!getSMLMEDANDOC().isEmpty()) {
            sreturnvalue += ", medios digitales y documentos en papel";
        }

        if (!getSMLNOMI().isEmpty()) {
            sreturnvalue += ", nombramientos";
        }

        if (!SMLSECPROC.isEmpty()) {
            sreturnvalue += ", procedimientos de seguridad";
        }

        if (!SMLSCAP.isEmpty()) {
            sreturnvalue += ", procedimientos especiales de control de acceso";
        }

        if (!SMLWFANDOB.isEmpty()) {
            sreturnvalue += ", funciones y obligaciones de los trabajadores";
        }
        sreturnvalue += ".";
        return sreturnvalue;
    }

    private void jBSecurityMeasuresDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSecurityMeasuresDocsActionPerformed
        CreateSecurityMeasuresDocs();
        //  AddObjecttoOperationsPanel(SMAuthor);
    }//GEN-LAST:event_jBSecurityMeasuresDocsActionPerformed

    private void JBImpactEvaluationDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBImpactEvaluationDocsActionPerformed
        CreateImpactEvaluationDocs();
    }//GEN-LAST:event_JBImpactEvaluationDocsActionPerformed

    private void jBTratRiscksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTratRiscksActionPerformed
        // TODO add your handling code here:
        CreateTratRiscksDocs();
    }//GEN-LAST:event_jBTratRiscksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PConfig.RestoreHelpconfig();
        setVisible(false);
        removeAll();
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PConfig.RestoreHelpconfig();
        setVisible(false);
        removeAll();
        revalidate();
        repaint();
        LifecycleManager.getDefault().exit();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBImpactEvaluationDocs;
    private javax.swing.JButton jBSecurityMeasuresDocs;
    private javax.swing.JButton jBTratRiscks;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPSecurity_MeasuresPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jUpperMenu_Panel;
    // End of variables declaration//GEN-END:variables
 private CLAllObjectList<CLAllObjectList<String>> SMLACL;
    private CLAllObjectList<CLAllObjectList<String>> SMLASM;
    private CLAllObjectList<CLAllObjectList<String>> SMLADL;
    private CLAllObjectList<CLAllObjectList<String>> SMLAUTH;
    private CLAllObjectList<CLAllObjectList<String>> SMLDTMAN;
    private CLAllObjectList<CLAllObjectList<String>> SMLEDTMAN;
    private CLAllObjectList<CLAllObjectList<String>> SMLFIDES;
    private CLAllObjectList<CLAllObjectList<String>> SMLMEDANDOC;
    private CLAllObjectList<CLAllObjectList<String>> SMLNOMI;
    private CLAllObjectList<CLAllObjectList<String>> SMLSECPROC;
    private CLAllObjectList<CLAllObjectList<String>> SMLSCAP;
    private CLAllObjectList<CLAllObjectList<String>> SMLWFANDOB;
    private CLAllObjectList<CLAllObjectList<String>> REGBARPRE;
    private CLAllObjectList<CLAllObjectList<String>> REGINRE;
    private CLAllObjectList<CLAllObjectList<String>> REGINOUTEXITREC;
    private CLAllObjectList<CLAllObjectList<String>> REGSANCTIONS;
    private CLAllObjectList<CLAllObjectList<String>> REGSECURITYCONTROLS;
    private CLAllObjectList<CLAllObjectList<String>> EVALUATIONRISKLIST;
    private CLAllObjectList<CLAllObjectList<String>> RISKMANAGEMENTLIST;
    private CLAllObjectList<CLAllObjectList<String>> IMPACTEVALUATIONLIST;
    private CLAllObjectList<CLAllObjectList<String>> BEHAVIOURCODESLIST;

    FDBManExtra DBManager = null;
    CLAllObjectList<String> ColumnsName = new CLAllObjectList<>();

    private void CreateSecurityMeasuresDocs() {
        if (PConfig.isUserAuthenticated() == true && PConfig.isClientActivated() == true && PConfig.isEntityActivated() == true) {
            P8PdfManager pdfman = new P8PdfManager("SecurityMeasures-Nominations.pdf");
            //CLAllObjectList<String> ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("Nombre");
            ColumnsName.add("Posición");
            ColumnsName.add("Permisos");
            pdfman.CreatePDFSecurityMeasures(getSMLNOMI(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-Authorizations.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("Nombre");
            ColumnsName.add("posición");
            ColumnsName.add("Recursos");
            pdfman.CreatePDFSecurityMeasures(getSMLAUTH(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-MediaandDocuments.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("fecha y hora");
            ColumnsName.add("tipo de recipiente");
            ColumnsName.add("numero o código");
            ColumnsName.add("tipo de información");
            ColumnsName.add("método de envío");
            ColumnsName.add("Id de la persona autorizada");
            ColumnsName.add("envío o recepìón");
            pdfman.CreatePDFSecurityMeasures(getSMLMEDANDOC(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-AuthorizationsDelegation.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("descripción de las autorizaciones delegadas");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            pdfman.CreatePDFSecurityMeasures(getSMLADL(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-AccesControlList.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("id autorizados");
            ColumnsName.add("recursos a los que se ha autorizado");
            pdfman.CreatePDFSecurityMeasures(getSMLACL(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-AlternateSecurityMeasures.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("descripción de las medidas alternativas");
            pdfman.CreatePDFSecurityMeasures(getSMLASM(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-DescrptionTreatmentManagement.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("descripción del tratamiento");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            pdfman.CreatePDFSecurityMeasures(getSMLDTMAN(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-ExternalDataTreatment.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("descripción del tratamiento externo");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            pdfman.CreatePDFSecurityMeasures(getSMLEDTMAN(), ColumnsName);
           /* pdfman = new P8PdfManager("SecurityMeasures-FilesDescription.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("nombre del fichero");
            ColumnsName.add("descripción del fichero");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            pdfman.CreatePDFSecurityMeasures(getSMLFIDES(), ColumnsName);*/
            pdfman = new P8PdfManager("SecurityMeasures-SecurityProcedures.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("descripción de los procedimientos de seguridad");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            pdfman.CreatePDFSecurityMeasures(getSMLSECPROC(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-SpecificControlAccessProcedures.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("procedimientos de acceso específicos");
            ColumnsName.add("procedimientos de control específicos");
            pdfman.CreatePDFSecurityMeasures(getSMLSCAP(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-WorkersFunctionsandObligations.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("id del trabajador");
            ColumnsName.add("funciones y obligaciones del trabajador");
            pdfman.CreatePDFSecurityMeasures(getSMLWFANDOB(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-BackupandRecoveryProcedureRegister.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("id del medio");
            ColumnsName.add("copia o recuperación");
            ColumnsName.add("administrador de las copias de seguridad");
            ColumnsName.add("medio del que hacer copia seg");
            ColumnsName.add("periodicidad copia");
            ColumnsName.add("metodolopgía copia");
            ColumnsName.add("tipo de medio usado");
            ColumnsName.add("tiempo de almacenamiento");
            ColumnsName.add("lugar de almacenamtiento");
            ColumnsName.add("fecha");
            ColumnsName.add("periodicidad transferencia");
            pdfman.CreatePDFSecurityMeasures(getREGBARPRE(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-IncidenceRegister.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("tipo de incidencia");
            ColumnsName.add("informante de la incidencia");
            ColumnsName.add("persona informada de la indicdencia");
            ColumnsName.add("efectos de la incidencia");
            ColumnsName.add("acciones tomadas");
            ColumnsName.add("procedimiento de recuperación");
            ColumnsName.add("datos restaurados");
            ColumnsName.add("datos guardados");
            ColumnsName.add("notas");
            ColumnsName.add("fecha");
            ColumnsName.add("nivel de seguridad");
            pdfman.CreatePDFSecurityMeasures(getREGINRE(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-CopyorRestaurationRegister.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("tipo de medio de datos");
            ColumnsName.add("copia o recuperación");
            ColumnsName.add("administrador de copias de seguridad");
            ColumnsName.add("medio a copiar o recuperar");
            ColumnsName.add("periodicidad de la copia");
            ColumnsName.add("metodología de la copia");
            ColumnsName.add("medios usados");
            ColumnsName.add("tiempo de almacenamiento");
            ColumnsName.add("lugar de almacenamiento");
            ColumnsName.add("fecha");
            ColumnsName.add("periodicidad de la transferencia");
            pdfman.CreatePDFSecurityMeasures(getREGINOUTEXITREC(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-CopyorRestaurationRegistar.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            ColumnsName.add("acto punible");
            ColumnsName.add("sanción");
            ColumnsName.add("persona sancionada");
            ColumnsName.add("fecha");
            pdfman.CreatePDFSecurityMeasures(getREGSANCTIONS(), ColumnsName);
            pdfman = new P8PdfManager("SecurityMeasures-SecurityControls.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("administrador del control de seguridad");
            ColumnsName.add("procedimiento del control de seguridad");
            ColumnsName.add("resultado del control de seguridad");
            ColumnsName.add("accón del control de seguridad completada");
            ColumnsName.add("id cliente");
            ColumnsName.add("id empresa");
            pdfman.CreatePDFSecurityMeasures(getREGSECURITYCONTROLS(), ColumnsName);
              ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");        
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("códigos de conducta");
        pdfman.CreatePDFSecurityMeasures(getREGSECURITYCONTROLS(), ColumnsName);
        } else {
            ShowDError("Debe dar de alta y seleccionar un cliente y una empresa para poder continuar ...");
        }
    }

    private void CreateImpactEvaluationDocs() {
        if (PConfig.isUserAuthenticated() == true && PConfig.isClientActivated() == true && PConfig.isEntityActivated() == true) {
            // CLAllObjectList<String> ColumnsName = new CLAllObjectList<>();
            P8PdfManager pdfman = new P8PdfManager("SecurityMeasures-EvalListRisks.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("ìndice del riesgo");
            ColumnsName.add("evaluación del riesgo");
            ColumnsName.add("id empresa");
            ColumnsName.add("id cliente");
            pdfman.CreatePDFSecurityMeasures(getBEHAVIOURCODESLIST(), ColumnsName);
            /**
             * pdfman = new
             * P8PdfManager("SecurityMeasures-RISKMANAGEMENTLIST.pdf"); Columns
             * = new CLAllObjectList<>(); Columns.add("índice");
             * Columns.add("Descripción del riesgo"); Columns.add("notas");
             * Columns.add("id empresa"); Columns.add("id cliente");
             * pdfman.CreatePDFSecurityMeasures(getRISKMANAGEMENTLIST(), Columns);
             */

        } else {
            ShowDError("Debe dar de alta y seleccionar un cliente y una empresa para poder continuar ...");
        }
    }

    private void CreateTratRiscksDocs() {
        if (PConfig.isUserAuthenticated() == true && PConfig.isClientActivated() == true && PConfig.isEntityActivated() == true) {
            //CLAllObjectList<String> ColumnsName = new CLAllObjectList<>();
            P8PdfManager pdfman = new P8PdfManager("TreatmentRisksManagementList.pdf");
            ColumnsName = new CLAllObjectList<>();
            ColumnsName.add("índice");
            ColumnsName.add("Descripción del riesgo");
            ColumnsName.add("Notas");
            ColumnsName.add("id empresa");
            ColumnsName.add("id cliente");
            pdfman.CreatePDFSecurityMeasures(getRISKMANAGEMENTLIST(), ColumnsName);

        } else {
            ShowDError("Debe dar de alta y seleccionar un cliente y una empresa para poder continuar ...");
        }
    }

    /**
     * @return the SMLNOMI
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLNOMI() {
        return SMLNOMI;
    }

    /**
     * @param SMLNOMI the SMLNOMI to set
     */
    public void setSMLNOMI(CLAllObjectList<CLAllObjectList<String>> SMLNOMI) {
        this.SMLNOMI = SMLNOMI;
    }

    /**
     * @return the SMLMEDANDOC
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLMEDANDOC() {
        return SMLMEDANDOC;
    }

    /**
     * @param SMLMEDANDOC the SMLMEDANDOC to set
     */
    public void setSMLMEDANDOC(CLAllObjectList<CLAllObjectList<String>> SMLMEDANDOC) {
        this.SMLMEDANDOC = SMLMEDANDOC;
    }

    /**
     * @return the SMLADL
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLADL() {
        return SMLADL;
    }

    /**
     * @param SMLADL the SMLADL to set
     */
    public void setSMLADL(CLAllObjectList<CLAllObjectList<String>> SMLADL) {
        this.SMLADL = SMLADL;
    }

    /**
     * @return the SMLAUTH
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLAUTH() {
        return SMLAUTH;
    }

    /**
     * @param SMLAUTH the SMLAUTH to set
     */
    public void setSMLAUTH(CLAllObjectList<CLAllObjectList<String>> SMLAUTH) {
        this.SMLAUTH = SMLAUTH;
    }

    private void LoadData() {
        PConfig.setDBName("ccpd_security_measures");
        DBManager = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        ColumnsName = DBManager.GetColumnsName("acesscontrollist");
        setSMLACL(DBManager.LoadList_Table(PConfig.getDBName(), "acesscontrollist", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("authorizations_delegated");
        setSMLADL(DBManager.LoadList_Table(PConfig.getDBName(), "authorizations_delegated", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("alternate_security_measures");
        setSMLASM(DBManager.LoadList_Table(PConfig.getDBName(), "alternate_security_measures", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("autorizations");
        setSMLAUTH(DBManager.LoadList_Table(PConfig.getDBName(), "autorizations", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("datatreatment_manager");
        setSMLDTMAN(DBManager.LoadList_Table(PConfig.getDBName(), "datatreatment_manager", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("external_data_treatment");
        setSMLEDTMAN(DBManager.LoadList_Table(PConfig.getDBName(), "external_data_treatment", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("files_description");
        setSMLFIDES(DBManager.LoadList_Table(PConfig.getDBName(), "files_description", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("mediaanddocuments");
        setSMLMEDANDOC(DBManager.LoadList_Table(PConfig.getDBName(), "mediaanddocuments", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("nominations");
        setSMLNOMI(DBManager.LoadList_Table(PConfig.getDBName(), "nominations", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("security_procedures");
        setSMLSECPROC(DBManager.LoadList_Table(PConfig.getDBName(), "security_procedures", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("specificcontrolaccessprocedures");
        setSMLSCAP(DBManager.LoadList_Table(PConfig.getDBName(), "specificcontrolaccessprocedures", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("workers_functionsandobligations");
        setSMLWFANDOB(DBManager.LoadList_Table(PConfig.getDBName(), "workers_functionsandobligations", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        PConfig.setDBName("ccpd_registers");
        DBManager = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        ColumnsName = DBManager.GetColumnsName("backupandrecoveryprocedure_register");
        setREGBARPRE(DBManager.LoadList_Table(PConfig.getDBName(), "backupandrecoveryprocedure_register", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("incidenceregister");
        setREGINRE(DBManager.LoadList_Table(PConfig.getDBName(), "incidenceregister", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("inoutexitrec_register");
        setREGINOUTEXITREC(DBManager.LoadList_Table(PConfig.getDBName(), "inoutexitrec_register", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("sanctions_register");
        setREGSANCTIONS(DBManager.LoadList_Table(PConfig.getDBName(), "sanctions_register", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("securitycontrols_register");
        setREGSECURITYCONTROLS(DBManager.LoadList_Table(PConfig.getDBName(), "securitycontrols_register", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        PConfig.setDBName("ccpd_lists");
        DBManager = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        ColumnsName = DBManager.GetColumnsName("list_impact_evaluation");
        setIMPACTEVALUATIONLIST(DBManager.LoadList_Table(PConfig.getDBName(), "list_impact_evaluation", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        PConfig.setDBName("ccpd_treat_risks");
        DBManager = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        ColumnsName = DBManager.GetColumnsName("evaluationrisklist");
        setEVALUATIONRISKLIST(DBManager.LoadList_Table(PConfig.getDBName(), "evaluationrisklist", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("riskmanagementlist");
        setRISKMANAGEMENTLIST(DBManager.LoadList_Table(PConfig.getDBName(), "riskmanagementlist", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
        ColumnsName = DBManager.GetColumnsName("behaviourcodes");
        setBEHAVIOURCODESLIST(DBManager.LoadList_Table(PConfig.getDBName(), "behaviourcodes", ColumnsName, PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise()));
    }

    /**
     * @return the SMLACL
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLACL() {
        return SMLACL;
    }

    /**
     * @param SMLACL the SMLACL to set
     */
    public void setSMLACL(CLAllObjectList<CLAllObjectList<String>> SMLACL) {
        this.SMLACL = SMLACL;
    }

    /**
     * @return the SMLASM
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLASM() {
        return SMLASM;
    }

    /**
     * @param SMLASM the SMLASM to set
     */
    public void setSMLASM(CLAllObjectList<CLAllObjectList<String>> SMLASM) {
        this.SMLASM = SMLASM;
    }

    /**
     * @return the SMLDTMAN
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLDTMAN() {
        return SMLDTMAN;
    }

    /**
     * @param SMLDTMAN the SMLDTMAN to set
     */
    public void setSMLDTMAN(CLAllObjectList<CLAllObjectList<String>> SMLDTMAN) {
        this.SMLDTMAN = SMLDTMAN;
    }

    /**
     * @return the SMLEDTMAN
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLEDTMAN() {
        return SMLEDTMAN;
    }

    /**
     * @param SMLEDTMAN the SMLEDTMAN to set
     */
    public void setSMLEDTMAN(CLAllObjectList<CLAllObjectList<String>> SMLEDTMAN) {
        this.SMLEDTMAN = SMLEDTMAN;
    }

    /**
     * @return the SMLFIDES
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLFIDES() {
        return SMLFIDES;
    }

    /**
     * @param SMLFIDES the SMLFIDES to set
     */
    public void setSMLFIDES(CLAllObjectList<CLAllObjectList<String>> SMLFIDES) {
        this.SMLFIDES = SMLFIDES;
    }

    /**
     * @return the SMLSECPROC
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLSECPROC() {
        return SMLSECPROC;
    }

    /**
     * @param SMLSECPROC the SMLSECPROC to set
     */
    public void setSMLSECPROC(CLAllObjectList<CLAllObjectList<String>> SMLSECPROC) {
        this.SMLSECPROC = SMLSECPROC;
    }

    /**
     * @return the SMLSCAP
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLSCAP() {
        return SMLSCAP;
    }

    /**
     * @param SMLSCAP the SMLSCAP to set
     */
    public void setSMLSCAP(CLAllObjectList<CLAllObjectList<String>> SMLSCAP) {
        this.SMLSCAP = SMLSCAP;
    }

    /**
     * @return the SMLWFANDOB
     */
    public CLAllObjectList<CLAllObjectList<String>> getSMLWFANDOB() {
        return SMLWFANDOB;
    }

    /**
     * @param SMLWFANDOB the SMLWFANDOB to set
     */
    public void setSMLWFANDOB(CLAllObjectList<CLAllObjectList<String>> SMLWFANDOB) {
        this.SMLWFANDOB = SMLWFANDOB;
    }

    /**
     * @return the REGBARPRE
     */
    public CLAllObjectList<CLAllObjectList<String>> getREGBARPRE() {
        return REGBARPRE;
    }

    /**
     * @param REGBARPRE the REGBARPRE to set
     */
    public void setREGBARPRE(CLAllObjectList<CLAllObjectList<String>> REGBARPRE) {
        this.REGBARPRE = REGBARPRE;
    }

    /**
     * @return the REGINRE
     */
    public CLAllObjectList<CLAllObjectList<String>> getREGINRE() {
        return REGINRE;
    }

    /**
     * @param REGINRE the REGINRE to set
     */
    public void setREGINRE(CLAllObjectList<CLAllObjectList<String>> REGINRE) {
        this.REGINRE = REGINRE;
    }

    /**
     * @return the REGINOUTEXITREC
     */
    public CLAllObjectList<CLAllObjectList<String>> getREGINOUTEXITREC() {
        return REGINOUTEXITREC;
    }

    /**
     * @param REGINOUTEXITREC the REGINOUTEXITREC to set
     */
    public void setREGINOUTEXITREC(CLAllObjectList<CLAllObjectList<String>> REGINOUTEXITREC) {
        this.REGINOUTEXITREC = REGINOUTEXITREC;
    }

    /**
     * @return the REGSANCTIONS
     */
    public CLAllObjectList<CLAllObjectList<String>> getREGSANCTIONS() {
        return REGSANCTIONS;
    }

    /**
     * @param REGSANCTIONS the REGSANCTIONS to set
     */
    public void setREGSANCTIONS(CLAllObjectList<CLAllObjectList<String>> REGSANCTIONS) {
        this.REGSANCTIONS = REGSANCTIONS;
    }

    /**
     * @return the REGSECURITYCONTROLS
     */
    public CLAllObjectList<CLAllObjectList<String>> getREGSECURITYCONTROLS() {
        return REGSECURITYCONTROLS;
    }

    /**
     * @param REGSECURITYCONTROLS the REGSECURITYCONTROLS to set
     */
    public void setREGSECURITYCONTROLS(CLAllObjectList<CLAllObjectList<String>> REGSECURITYCONTROLS) {
        this.REGSECURITYCONTROLS = REGSECURITYCONTROLS;
    }

    /**
     * @return the EVALUATIONRISKLIST
     */
    public CLAllObjectList<CLAllObjectList<String>> getEVALUATIONRISKLIST() {
        return EVALUATIONRISKLIST;
    }

    /**
     * @param EVALUATIONRISKLIST the EVALUATIONRISKLIST to set
     */
    public void setEVALUATIONRISKLIST(CLAllObjectList<CLAllObjectList<String>> EVALUATIONRISKLIST) {
        this.EVALUATIONRISKLIST = EVALUATIONRISKLIST;
    }

    /**
     * @return the RISKMANAGEMENTLIST
     */
    public CLAllObjectList<CLAllObjectList<String>> getRISKMANAGEMENTLIST() {
        return RISKMANAGEMENTLIST;
    }

    /**
     * @param RISKMANAGEMENTLIST the RISKMANAGEMENTLIST to set
     */
    public void setRISKMANAGEMENTLIST(CLAllObjectList<CLAllObjectList<String>> RISKMANAGEMENTLIST) {
        this.RISKMANAGEMENTLIST = RISKMANAGEMENTLIST;
    }

    /**
     * @return the IMPACTEVALUATIONLIST
     */
    public CLAllObjectList<CLAllObjectList<String>> getIMPACTEVALUATIONLIST() {
        return IMPACTEVALUATIONLIST;
    }

    /**
     * @param IMPACTEVALUATIONLIST the IMPACTEVALUATIONLIST to set
     */
    public void setIMPACTEVALUATIONLIST(CLAllObjectList<CLAllObjectList<String>> IMPACTEVALUATIONLIST) {
        this.IMPACTEVALUATIONLIST = IMPACTEVALUATIONLIST;
    }

    /**
     * @return the BEHAVIOURCODESLIST
     */
    public CLAllObjectList<CLAllObjectList<String>> getBEHAVIOURCODESLIST() {
        return BEHAVIOURCODESLIST;
    }

    /**
     * @param BEHAVIOURCODESLIST the BEHAVIOURCODESLIST to set
     */
    public void setBEHAVIOURCODESLIST(CLAllObjectList<CLAllObjectList<String>> BEHAVIOURCODESLIST) {
        this.BEHAVIOURCODESLIST = BEHAVIOURCODESLIST;
    }
}
