package ccpd.es.p8panels;

import static beleris.es.finalinformationmanager.MainErrorManager.ShowDError;
import static ccpd.es.p8config.P8Config.PConfig;
import java.awt.Component;
import java.awt.FlowLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author edavid
 */
public class JPCustomization extends javax.swing.JPanel {

    private static final long serialVersionUID = 5836778799310749330L;

   

    /**
     * Creates new form JPSecurity_Measures
     */
    public JPCustomization() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jUpperMenu_Panel = new javax.swing.JPanel();
        jBCoorCAt = new javax.swing.JButton();
        JBGenNotif = new javax.swing.JButton();
        jBDestCes = new javax.swing.JButton();
        jBTreatTypes = new javax.swing.JButton();
        jBTiposMedios = new javax.swing.JButton();
        JPProvinces = new javax.swing.JButton();
        JBCountries = new javax.swing.JButton();
        jBFileType = new javax.swing.JButton();
        JBEnityLogo = new javax.swing.JButton();
        JBSecLev = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBEvalImpact1 = new javax.swing.JButton();
        jPSecurity_MeasuresPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1560, 900));
        setMinimumSize(new java.awt.Dimension(1560, 900));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1560, 900));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1560, 900));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1560, 900));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1560, 900));

        jUpperMenu_Panel.setMaximumSize(new java.awt.Dimension(1560, 60));
        jUpperMenu_Panel.setMinimumSize(new java.awt.Dimension(1560, 60));
        jUpperMenu_Panel.setPreferredSize(new java.awt.Dimension(1560, 60));
        jUpperMenu_Panel.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jBCoorCAt, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.jBCoorCAt.text")); // NOI18N
        jBCoorCAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCoorCAtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jBCoorCAt, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBGenNotif, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.JBGenNotif.text")); // NOI18N
        JBGenNotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGenNotifActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(JBGenNotif, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBDestCes, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.jBDestCes.text")); // NOI18N
        jBDestCes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDestCesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jBDestCes, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBTreatTypes, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.jBTreatTypes.text")); // NOI18N
        jBTreatTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTreatTypesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jBTreatTypes, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBTiposMedios, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.jBTiposMedios.text")); // NOI18N
        jBTiposMedios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTiposMediosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jBTiposMedios, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JPProvinces, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.JPProvinces.text")); // NOI18N
        JPProvinces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPProvincesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(JPProvinces, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBCountries, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.JBCountries.text")); // NOI18N
        JBCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCountriesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(JBCountries, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBFileType, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.jBFileType.text")); // NOI18N
        jBFileType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFileTypeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jBFileType, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBEnityLogo, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.JBEnityLogo.text")); // NOI18N
        JBEnityLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEnityLogoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(JBEnityLogo, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBSecLev, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.JBSecLev.text")); // NOI18N
        JBSecLev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSecLevActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(JBSecLev, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jButton1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBEvalImpact1, org.openide.util.NbBundle.getMessage(JPCustomization.class, "JPCustomization.jBEvalImpact1.text")); // NOI18N
        jBEvalImpact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEvalImpact1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jUpperMenu_Panel.add(jBEvalImpact1, gridBagConstraints);

        jSplitPane1.setLeftComponent(jUpperMenu_Panel);

        jPSecurity_MeasuresPanel.setMaximumSize(new java.awt.Dimension(1560, 740));
        jPSecurity_MeasuresPanel.setMinimumSize(new java.awt.Dimension(1560, 740));
        jPSecurity_MeasuresPanel.setPreferredSize(new java.awt.Dimension(1560, 740));
        jPSecurity_MeasuresPanel.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane1.setRightComponent(jPSecurity_MeasuresPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCoorCAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCoorCAtActionPerformed
        // TODO add your handling code here:
        Panel_TableDBManager PCollectivesorcategories = new Panel_TableDBManager("ccpd_lists", "list_collectivesorcategories");
        AddObjecttoOperationsPanel(PCollectivesorcategories);
    }//GEN-LAST:event_jBCoorCAtActionPerformed

    private void jBTiposMediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTiposMediosActionPerformed
        // TODO add your handling code here:
        Panel_TableDBManager PTsourcemedia = new Panel_TableDBManager("ccpd_lists", "list_tsourcemedia");
        AddObjecttoOperationsPanel(PTsourcemedia);
    }//GEN-LAST:event_jBTiposMediosActionPerformed

    private void jBTreatTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTreatTypesActionPerformed
        Panel_TableDBManager PTreatypes = new Panel_TableDBManager("ccpd_lists", "list_treatypes");
        AddObjecttoOperationsPanel(PTreatypes);
    }//GEN-LAST:event_jBTreatTypesActionPerformed

    private void JPProvincesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPProvincesActionPerformed
        Panel_TableDBManager PTprovinces = new Panel_TableDBManager("ccpd_lists", "list_tprovinces");
        AddObjecttoOperationsPanel(PTprovinces);
    }//GEN-LAST:event_JPProvincesActionPerformed

    private void JBCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCountriesActionPerformed
        Panel_TableDBManager PTcountries = new Panel_TableDBManager("ccpd_lists", "list_tcountries");
        AddObjecttoOperationsPanel(PTcountries);
    }//GEN-LAST:event_JBCountriesActionPerformed

    private void JBEnityLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEnityLogoActionPerformed
        if (PConfig.isUserAuthenticated() == true && PConfig.isClientActivated() == true && PConfig.isEntityActivated() == true) {
            JPLoadLogoEnity loadlogoentity = new JPLoadLogoEnity();
            AddObjecttoOperationsPanel(loadlogoentity);
        } else {
            ShowDError("Debe dar de alta y seleccionar un cliente y una empresa para poder continuar ...");
        }

    }//GEN-LAST:event_JBEnityLogoActionPerformed

    private void JBGenNotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGenNotifActionPerformed
        Panel_TableDBManager PGenerictypenotifications = new Panel_TableDBManager("ccpd_lists", "list_generictypenotifications");
        AddObjecttoOperationsPanel(PGenerictypenotifications);
    }//GEN-LAST:event_JBGenNotifActionPerformed

    private void jBFileTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFileTypeActionPerformed
        Panel_TableDBManager PFiletype = new Panel_TableDBManager("ccpd_lists", "list_filetype");
        AddObjecttoOperationsPanel(PFiletype);
    }//GEN-LAST:event_jBFileTypeActionPerformed

    private void jBDestCesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDestCesActionPerformed
        Panel_TableDBManager PTargetcessions = new Panel_TableDBManager("ccpd_lists", "list_cat_targetcessions");
        AddObjecttoOperationsPanel(PTargetcessions);
    }//GEN-LAST:event_jBDestCesActionPerformed

    private void JBSecLevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSecLevActionPerformed
        Panel_TableDBManager PSeclevel = new Panel_TableDBManager("ccpd_lists", "list_seclevel");
        AddObjecttoOperationsPanel(PSeclevel);
    }//GEN-LAST:event_JBSecLevActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Panel_TableDBManager PDesttransint = new Panel_TableDBManager("ccpd_lists", "list_cat_desttransint");
        AddObjecttoOperationsPanel(PDesttransint);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBEvalImpact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEvalImpact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEvalImpact1ActionPerformed
    void AddObjecttoOperationsPanel(Component Cnt) {
        jPSecurity_MeasuresPanel.removeAll();
        jPSecurity_MeasuresPanel.invalidate();
        jPSecurity_MeasuresPanel.setLayout(new FlowLayout());
        jPSecurity_MeasuresPanel.add(Cnt);
        jPSecurity_MeasuresPanel.setVisible(true);
        jPSecurity_MeasuresPanel.validate();
        jPSecurity_MeasuresPanel.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCountries;
    private javax.swing.JButton JBEnityLogo;
    private javax.swing.JButton JBGenNotif;
    private javax.swing.JButton JBSecLev;
    private javax.swing.JButton JPProvinces;
    private javax.swing.JButton jBCoorCAt;
    private javax.swing.JButton jBDestCes;
    private javax.swing.JButton jBEvalImpact1;
    private javax.swing.JButton jBFileType;
    private javax.swing.JButton jBTiposMedios;
    private javax.swing.JButton jBTreatTypes;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPSecurity_MeasuresPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jUpperMenu_Panel;
    // End of variables declaration//GEN-END:variables
}
