/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;

import static beleris.es.finalinformationmanager.MainErrorManager.ShowDError;
import static ccpd.es.p8config.P8Config.PConfig;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.openide.windows.WindowManager;

/**
 *
 * @author edavid
 */
public class JPLoadLogoEnity extends javax.swing.JPanel {

    private static final long serialVersionUID = 4455137120039238574L;

  

    //FPrintManager pm = new FPrintManager();
    /**
     * Creates new form JPLoasLogoEnity
     */
    public JPLoadLogoEnity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        JPLoadImage = new javax.swing.JPanel();
        JBLogoEntityImage = new javax.swing.JButton();
        JPShowImage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        setMaximumSize(new java.awt.Dimension(1080, 650));
        setMinimumSize(new java.awt.Dimension(1080, 650));
        setPreferredSize(new java.awt.Dimension(1080, 650));
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1080, 655));

        JPLoadImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        JPLoadImage.setMaximumSize(new java.awt.Dimension(1080, 60));
        JPLoadImage.setMinimumSize(new java.awt.Dimension(1080, 60));
        JPLoadImage.setPreferredSize(new java.awt.Dimension(1080, 60));
        JPLoadImage.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(JBLogoEntityImage, org.openide.util.NbBundle.getMessage(JPLoadLogoEnity.class, "JPLoadLogoEnity.JBLogoEntityImage.text")); // NOI18N
        JBLogoEntityImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLogoEntityImageActionPerformed(evt);
            }
        });
        JPLoadImage.add(JBLogoEntityImage, new java.awt.GridBagConstraints());

        jSplitPane1.setTopComponent(JPLoadImage);

        JPShowImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPShowImage.setMaximumSize(new java.awt.Dimension(1080, 590));
        JPShowImage.setMinimumSize(new java.awt.Dimension(1080, 590));
        JPShowImage.setPreferredSize(new java.awt.Dimension(1080, 590));
        JPShowImage.setVerifyInputWhenFocusTarget(false);
        JPShowImage.setLayout(new java.awt.GridLayout(1, 0));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JPLoadLogoEnity.class, "JPLoadLogoEnity.jLabel1.text")); // NOI18N
        JPShowImage.add(jLabel1);

        jSplitPane1.setBottomComponent(JPShowImage);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void JBLogoEntityImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLogoEntityImageActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(WindowManager.getDefault().getMainWindow());
        BufferedImage ImageLoaded = null;
        BufferedImage ImagePDF = null;
        File selectedFile = null;
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            // ShowDInfo("Imagen seleccionada");

            try {
                ImageLoaded = ImageIO.read(selectedFile);
            } catch (IOException ex) {
                ShowDError("Debe seleccion ar un fichero de imagen: " + ex.getLocalizedMessage());
            }

            //JScrollPane SP = new JScrollPane(label);
            Rectangle rPanel = JPShowImage.getBounds();

            int thewidth = 0;
            int theheigth = 0;
            int iheigth = 0;
            int iwidth = 0;

            iheigth = ImageLoaded.getHeight();
            iwidth = ImageLoaded.getWidth();
            int scaleFactor = 16;
            int pscaleFactor = 90;

            // if (rPanel.height < rImage.height) {
            theheigth = iheigth * scaleFactor / 100;
            thewidth = iwidth * scaleFactor / 100;
            int pthewidth = rPanel.width * pscaleFactor / 100;
            float aratio = (float) iheigth / (float) iwidth;
            float floptheheigth = ((float) pthewidth * (float) iheigth) / (float) iwidth;
            //float floptheheigth = (float) rPanel.height.ç * aratio;
            int ptheheigth = (int) floptheheigth;

            // }
            //  int scaledWidth = Math.min(rImage.width, rPanel.width);
            // int scaledHeight = Math.max(1, rImage.height * scaledWidth / rImage.width);
            //int scaledHeight = Math.max(rImage.height, rPanel.height);
            /* if (ImageLoaded != null) {
                ImageLoaded.resize(thewidth, theheigth,Image.SCALE_SMOOTH);
            }*/
            if (ImageLoaded != null) {
                try {
                    ImagePanel = resizeImage(ImageLoaded, pthewidth, ptheheigth);
                } catch (IOException ex) {
                    ShowDError("Error al redimensionar imagen: " + ex.getLocalizedMessage());
                }
            }
            if (ImageLoaded != null) {
                try {
                    ImagePDF = resizeImage(ImageLoaded, thewidth, theheigth);

                } catch (IOException ex) {
                    ShowDError("Error al redimensionar imagen: " + ex.getLocalizedMessage());
                }
            }
            PConfig.setEntityLogo(ImageLoaded);
            PConfig.setEntityLogoPDF(ImagePDF);
            
            //Imagecon ImageLoadedIcon = new ImageIcon(ImagePanel);
            //JLabel label = new JLabel();

            //label.setBounds(rImage);
            //label.setIcon(ImageLoadedIcon);
            //JFinalPanel.setBounds(rImage);
            //JFinalPanel.add(label);
//            pm.CreateImageDocument(ImagePanel, JFinalPanel.getGraphics());
            ImageIcon icon = new ImageIcon(ImagePanel);
            jLabel1.setIcon(icon);
            JPShowImage.validate();
            JPShowImage.repaint();
            jLabel1.validate();
            jLabel1.repaint();
        } else {
            ShowDError("Debe seleccionar un fichero de imagen");
        }
        //    this.add(ThNP);

       // pdfman.GeneratePDF(ImagePDF);

    }//GEN-LAST:event_JBLogoEntityImageActionPerformed

    BufferedImage resizeImage(BufferedImage originalImage, int targetWidth, int targetHeight) throws IOException {
        BufferedImage resizedImage = new BufferedImage(targetWidth, targetHeight, BufferedImage.SCALE_SMOOTH + BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics2D = resizedImage.createGraphics();
        graphics2D.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
        graphics2D.drawImage(originalImage, 0, 0, targetWidth, targetHeight, null);
        graphics2D.dispose();
        return resizedImage;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBLogoEntityImage;
    private javax.swing.JPanel JPLoadImage;
    private javax.swing.JPanel JPShowImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    BufferedImage ImagePanel = null;
}

class JNewPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = -4942408036273095595L;

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        //rectangle originates at 10,10 and ends at 240,240
        // g.drawRect(10, 10, 240, 240);
        //filled Rectangle with rounded corners.    
        // g.fillRoundRect(50, 50, 100, 100, 80, 80);
        // g.create(0, 0, imagerenderx, imagerendery);
        int imagerenderx = g.getClipBounds().width;
        int imagerendery = g.getClipBounds().height;
        g.setColor(Color.white);
        g.fillRect(0, 0, imagerenderx, imagerendery);
        g.setColor(Color.black);
        g.drawRoundRect(25, 25, imagerenderx - 50, imagerendery - 50, 25, 25);
//        g.drawImage(ImagePanel, 50, 50, null);
        g.drawString("Hello world!", 100, 100);
    }

}
