package ccpd.es.p8panels;

import beleris.es.finalprimaryclasses.CLAllObjectList;
import static ccpd.es.p8config.P8Config.PConfig;
import ccpd.es.p8dbmanager.FDBManExtra;
import java.awt.Component;
import java.util.Iterator;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author edavid
 */
public class JPSecurity_Measures extends javax.swing.JPanel {

    private static final long serialVersionUID = 8912161553826880378L;
    CLAllObjectList<String> ColumnsName = new CLAllObjectList<>();

    /**
     * Creates new form JPSecurity_Measures
     */
    public JPSecurity_Measures() {
        initComponents();
        /*   JInnerSPanel.getVerticalScrollBar().setPreferredSize(new Dimension(
                (int) (JInnerSPanel.getVerticalScrollBar().getPreferredSize()
                        .getWidth() * 1.2),
                (int) JInnerSPanel.getVerticalScrollBar().getPreferredSize().getHeight()
        ));
        JInnerSPanel.getHorizontalScrollBar().setPreferredSize(new Dimension(
                (int) JInnerSPanel.getHorizontalScrollBar().getPreferredSize()
                        .getWidth(),
                (int) (JInnerSPanel.getHorizontalScrollBar().getPreferredSize().getHeight() * 1.2)
        ));*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jUpperMenu_Panel = new javax.swing.JPanel();
        jBIncidenceReg = new javax.swing.JButton();
        jBSanctions = new javax.swing.JButton();
        jBInOutexitorRecData = new javax.swing.JButton();
        jBAuthiorizations = new javax.swing.JButton();
        jBNominations = new javax.swing.JButton();
        JBCessionsTargets = new javax.swing.JButton();
        jRAlternatMeasures = new javax.swing.JButton();
        jBMediaandDocsSources = new javax.swing.JButton();
        jBCpyREstReg = new javax.swing.JButton();
        jBAuthorDel = new javax.swing.JButton();
        JRBaseDatos = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        JBAcessList = new javax.swing.JButton();
        JTreatDescr = new javax.swing.JButton();
        jBExternal = new javax.swing.JButton();
        jBSecurityDescrProcedures = new javax.swing.JButton();
        jBSpecialProc = new javax.swing.JButton();
        jBFuncAndObligWorkers = new javax.swing.JButton();
        jBBehaviourCodes = new javax.swing.JButton();
        jInnerSurfacePanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(0, 0));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jUpperMenu_Panel.setMaximumSize(new java.awt.Dimension(1829, 150));
        jUpperMenu_Panel.setMinimumSize(new java.awt.Dimension(1829, 150));
        jUpperMenu_Panel.setPreferredSize(new java.awt.Dimension(1829, 150));
        jUpperMenu_Panel.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jBIncidenceReg, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBIncidenceReg.text")); // NOI18N
        jBIncidenceReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncidenceRegActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBIncidenceReg, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBSanctions, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBSanctions.text")); // NOI18N
        jBSanctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSanctionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBSanctions, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBInOutexitorRecData, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBInOutexitorRecData.text")); // NOI18N
        jBInOutexitorRecData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInOutexitorRecDataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBInOutexitorRecData, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBAuthiorizations, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBAuthiorizations.text")); // NOI18N
        jBAuthiorizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAuthiorizationsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBAuthiorizations, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBNominations, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBNominations.text")); // NOI18N
        jBNominations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNominationsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBNominations, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBCessionsTargets, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.JBCessionsTargets.text")); // NOI18N
        JBCessionsTargets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCessionsTargetsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(JBCessionsTargets, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jRAlternatMeasures, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jRAlternatMeasures.text")); // NOI18N
        jRAlternatMeasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAlternatMeasuresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jRAlternatMeasures, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBMediaandDocsSources, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBMediaandDocsSources.text")); // NOI18N
        jBMediaandDocsSources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMediaandDocsSourcesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBMediaandDocsSources, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBCpyREstReg, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBCpyREstReg.text")); // NOI18N
        jBCpyREstReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCpyREstRegActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBCpyREstReg, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBAuthorDel, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBAuthorDel.text")); // NOI18N
        jBAuthorDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAuthorDelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBAuthorDel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JRBaseDatos, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.JRBaseDatos.text")); // NOI18N
        JRBaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBaseDatosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(JRBaseDatos, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jExit, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jExit.text")); // NOI18N
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jExit, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBAcessList, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.JBAcessList.text")); // NOI18N
        JBAcessList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAcessListActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(JBAcessList, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JTreatDescr, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.JTreatDescr.text")); // NOI18N
        JTreatDescr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTreatDescrActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(JTreatDescr, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBExternal, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBExternal.text")); // NOI18N
        jBExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExternalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBExternal, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBSecurityDescrProcedures, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBSecurityDescrProcedures.text")); // NOI18N
        jBSecurityDescrProcedures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSecurityDescrProceduresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBSecurityDescrProcedures, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBSpecialProc, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBSpecialProc.text")); // NOI18N
        jBSpecialProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSpecialProcActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBSpecialProc, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBFuncAndObligWorkers, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBFuncAndObligWorkers.text")); // NOI18N
        jBFuncAndObligWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFuncAndObligWorkersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBFuncAndObligWorkers, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBBehaviourCodes, org.openide.util.NbBundle.getMessage(JPSecurity_Measures.class, "JPSecurity_Measures.jBBehaviourCodes.text")); // NOI18N
        jBBehaviourCodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBehaviourCodesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jUpperMenu_Panel.add(jBBehaviourCodes, gridBagConstraints);

        jSplitPane1.setTopComponent(jUpperMenu_Panel);

        jInnerSurfacePanel.setMaximumSize(new java.awt.Dimension(1829, 880));
        jInnerSurfacePanel.setMinimumSize(new java.awt.Dimension(1829, 880));
        jInnerSurfacePanel.setPreferredSize(new java.awt.Dimension(1829, 880));
        jSplitPane1.setBottomComponent(jInnerSurfacePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBIncidenceRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncidenceRegActionPerformed
        // TODO add your handling code here:
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("ID");
        ColumnsName.add("ID del cliente");
        ColumnsName.add("ID de la Empresa");
        ColumnsName.add("Tipo de incidencia");
        ColumnsName.add("Informante");
        ColumnsName.add("Informado");
        ColumnsName.add("Efectos de la incidencia");
        ColumnsName.add("Acciones");
        ColumnsName.add("Procedimiento de recuperación");
        ColumnsName.add("Datos restaurados");
        ColumnsName.add("Datos guardados");
        ColumnsName.add("Notas");
        ColumnsName.add("Fecha");
        ColumnsName.add("Nivel de seguridad");
        Panel_TableDBManager SMIncidenceREg = new Panel_TableDBManager("ccpd_registers", "incidenceregister", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Registro de incidencias");
        InsertComlumnList(SMIncidenceREg, "ccpd_lists", "list_seclevel", "security_level", 13);
        RemoveUnneededColumns(SMIncidenceREg, 3);
        AddObjecttoOperationsPanel(SMIncidenceREg);
    }//GEN-LAST:event_jBIncidenceRegActionPerformed

    private void jBNominationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNominationsActionPerformed
        // TODO add your handling code here:
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("Nombre");
        ColumnsName.add("Posición");
        ColumnsName.add("Permisos");
        Panel_TableDBManager SMNom = new Panel_TableDBManager("ccpd_security_measures", "nominations", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Lista de nombramientos");
        RemoveUnneededColumns(SMNom, 3);
        AddObjecttoOperationsPanel(SMNom);
    }//GEN-LAST:event_jBNominationsActionPerformed

    private void jBAuthiorizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAuthiorizationsActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("Nombre");
        ColumnsName.add("posición");
        ColumnsName.add("Recursos");
        Panel_TableDBManager SMAuthor = new Panel_TableDBManager("ccpd_security_measures", "autorizations", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Lista de autorizaciones");
        RemoveUnneededColumns(SMAuthor, 3);
        AddObjecttoOperationsPanel(SMAuthor);
    }//GEN-LAST:event_jBAuthiorizationsActionPerformed

    private void JBCessionsTargetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCessionsTargetsActionPerformed
        Panel_TableDBManager SMCesTar = new Panel_TableDBManager("ccpd_lists", "list_cat_targetcessions");
        AddObjecttoOperationsPanel(SMCesTar);
    }//GEN-LAST:event_JBCessionsTargetsActionPerformed
    void InsertComlumnList(Panel_TableDBManager ptdbm, String tmpDB, String tmpDBTable, String Column, int colnum) {
        JComboBox TestComboBox = new JComboBox();
        PConfig.setDBName(tmpDB);
        FDBManExtra DBMSAP = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        CLAllObjectList<String> IDX = DBMSAP.LoadList(tmpDBTable, Column);
        TableColumn typemedia = ptdbm.getJPTable().getColumnModel().getColumn(colnum);
        for (String item : IDX) {
            TestComboBox.addItem(item);
        }
        TestComboBox.setSelectedIndex(Integer.parseInt((String) ptdbm.getJPTable().getModel().getValueAt(0, colnum)) - 1);
        typemedia.setCellEditor(new DefaultCellEditor(TestComboBox));
    }
    private void jBMediaandDocsSourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMediaandDocsSourcesActionPerformed
        JComboBox TestComboBox = new JComboBox();
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("índice de medio");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("fecha y hora");
        ColumnsName.add("tipo de recipiente");
        ColumnsName.add("numero o código");
        ColumnsName.add("tipo de información");
        ColumnsName.add("método de envío");
        ColumnsName.add("Id de la persona autorizada");
        ColumnsName.add("envío o recepìón");
        Panel_TableDBManager SMMediaandDocs = new Panel_TableDBManager("ccpd_security_measures", "mediaanddocuments", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "registro de soportes");
        InsertComlumnList(SMMediaandDocs, "ccpd_lists", "list_tsourcemedia","sourcemedia_name", 5);
//        InsertComlumnList(SMMediaandDocs, "list_tsourcemedia", "sourcemedia_name", 5);
        RemoveUnneededColumns(SMMediaandDocs, 3);
        AddObjecttoOperationsPanel(SMMediaandDocs);
    }//GEN-LAST:event_jBMediaandDocsSourcesActionPerformed

    private void jBAuthorDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAuthorDelActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("descripción de las autorizaciones delegadas");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        Panel_TableDBManager SMAuthor = new Panel_TableDBManager("ccpd_security_measures", "authorizations_delegated", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Delegación de autorizaciones");
        RemoveUnneededColumnsselected(SMAuthor, 3);
        RemoveUnneededColumnsselected(SMAuthor, 2);
        RemoveUnneededColumnsselected(SMAuthor, 0);
        AddObjecttoOperationsPanel(SMAuthor);
    }//GEN-LAST:event_jBAuthorDelActionPerformed

    private void jBSanctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSanctionsActionPerformed

        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("acto punible");
        ColumnsName.add("sanción");
        ColumnsName.add("persona sancionada");
        ColumnsName.add("fecha");
        Panel_TableDBManager SMSanctionReg = new Panel_TableDBManager("ccpd_registers", "sanctions_register", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Registro de sanciones");
        RemoveUnneededColumns(SMSanctionReg, 3);
        AddObjecttoOperationsPanel(SMSanctionReg);
    }//GEN-LAST:event_jBSanctionsActionPerformed

    private void jBCpyREstRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCpyREstRegActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("tipo de medio de datos");
        ColumnsName.add("copia o recuperación");
        ColumnsName.add("administrador de copias de seguridad");
        ColumnsName.add("medio a copiar o recuperar");
        ColumnsName.add("periodicidad de la copia");
        ColumnsName.add("metodología de la copia");
        ColumnsName.add("medios usados");
        ColumnsName.add("tiempo de almacenamiento");
        ColumnsName.add("lugar de almacenamiento");
        ColumnsName.add("fecha");
        ColumnsName.add("periodicidad de la transferencia");
        Panel_TableDBManager BackupAndRecovery = new Panel_TableDBManager("ccpd_registers", "backupandrecoveryprocedure_register", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Registro de las copias de seguridad o restauración realizadas");
        InsertComlumnList(BackupAndRecovery, "ccpd_lists", "list_tsourcemedia","sourcemedia_name", 3);
        RemoveUnneededColumns(BackupAndRecovery, 3);
        AddObjecttoOperationsPanel(BackupAndRecovery);
    }//GEN-LAST:event_jBCpyREstRegActionPerformed

    private void jBInOutexitorRecDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInOutexitorRecDataActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("tipo de medio de datos");
        ColumnsName.add("copia o recuperación");
        ColumnsName.add("administrador de copias de seguridad");
        ColumnsName.add("medio a copiar o recuperar");
        ColumnsName.add("periodicidad de la copia");
        ColumnsName.add("metodología de la copia");
        ColumnsName.add("medios usados");
        ColumnsName.add("tiempo de almacenamiento");
        ColumnsName.add("lugar de almacenamiento");
        ColumnsName.add("fecha");
        ColumnsName.add("periodicidad de la transferencia");
        Panel_TableDBManager SMCopyREstorReg = new Panel_TableDBManager("ccpd_registers", "inoutexitrec_register", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Registro de entrada o salida de datos");
        InsertComlumnList(SMCopyREstorReg, "ccpd_lists","list_tsourcemedia", "sourcemedia_name", 3);
        RemoveUnneededColumns(SMCopyREstorReg, 3);
        AddObjecttoOperationsPanel(SMCopyREstorReg);
    }//GEN-LAST:event_jBInOutexitorRecDataActionPerformed

    private void JRBaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBaseDatosActionPerformed
        // TODO add your handling code here:
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("Nombre de la bbdd");
        ColumnsName.add("Descripción de la bbdd");

        Panel_TableDBManager PersonaDatalDBList = new Panel_TableDBManager("ccpd_lists", "list_personaldatadb", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Bases de datos con información personal");
        RemoveUnneededColumns(PersonaDatalDBList, 3);
        AddObjecttoOperationsPanel(PersonaDatalDBList);
    }//GEN-LAST:event_JRBaseDatosActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        setVisible(false);
        removeAll();
        revalidate();
        repaint();
    }//GEN-LAST:event_jExitActionPerformed
    void RemoveUnneededColumns(Panel_TableDBManager tmpPanel, int itimes) {
        for (int it = 0; it < itimes; it++) {
            tmpPanel.getJPTable().removeColumn(tmpPanel.getJPTable().getColumnModel().getColumn(0));
        }
    }

    void SetCellValue(Panel_TableDBManager tmpPanel, int x, int y, String Content) {
        tmpPanel.getJPTable().setValueAt(Content, y, x);

    }

    void RemoveUnneededColumnsselected(Panel_TableDBManager tmpPanel, int icolumn) {
        tmpPanel.getJPTable().removeColumn(tmpPanel.getJPTable().getColumnModel().getColumn(icolumn));
    }
    private void JBAcessListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAcessListActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("id autorizados");
        ColumnsName.add("recursos a los que se ha autorizado");
        Panel_TableDBManager AccessControlList = new Panel_TableDBManager("ccpd_security_measures", "acesscontrollist", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "recursos a los que se ha autorizado");
        InsertComlumnList(AccessControlList, "ccpd_security_measures", "autorizations","name", 3);
        RemoveUnneededColumns(AccessControlList, 3);
        AddObjecttoOperationsPanel(AccessControlList);
    }//GEN-LAST:event_JBAcessListActionPerformed

    private void jRAlternatMeasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAlternatMeasuresActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("descripción de las medidas alternativas");
        Panel_TableDBManager AccessControlList = new Panel_TableDBManager("ccpd_security_measures", "alternate_security_measures", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "descripción de las medidas alternativaso");
        RemoveUnneededColumns(AccessControlList, 3);
        AddObjecttoOperationsPanel(AccessControlList);
    }//GEN-LAST:event_jRAlternatMeasuresActionPerformed

    private void jBExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExternalActionPerformed

        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("descripción del tratamiento externo");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        Panel_TableDBManager ExternTreat = new Panel_TableDBManager("ccpd_security_measures", "external_data_treatment", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "descripción del tratamiento externo");
        RemoveUnneededColumnsselected(ExternTreat, 3);
        RemoveUnneededColumnsselected(ExternTreat, 2);
        RemoveUnneededColumnsselected(ExternTreat, 0);
        AddObjecttoOperationsPanel(ExternTreat);

    }//GEN-LAST:event_jBExternalActionPerformed

    private void jBSecurityDescrProceduresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSecurityDescrProceduresActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("descripción de los procedimientos de seguridad");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        Panel_TableDBManager SecProc = new Panel_TableDBManager("ccpd_security_measures", "security_procedures", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "descripción de los procedimientos de seguridad");
        RemoveUnneededColumnsselected(SecProc, 3);
        RemoveUnneededColumnsselected(SecProc, 2);
        RemoveUnneededColumnsselected(SecProc, 0);
        AddObjecttoOperationsPanel(SecProc);
    }//GEN-LAST:event_jBSecurityDescrProceduresActionPerformed

    private void jBSpecialProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSpecialProcActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("procedimientos de acceso específicos");
        ColumnsName.add("procedimientos de control específicos");
        Panel_TableDBManager SpecificControlActions = new Panel_TableDBManager("ccpd_security_measures", "specificcontrolaccessprocedures", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "procedimientos de acceso y control específicos");
        RemoveUnneededColumns(SpecificControlActions, 3);
        AddObjecttoOperationsPanel(SpecificControlActions);

    }//GEN-LAST:event_jBSpecialProcActionPerformed

    private void jBFuncAndObligWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFuncAndObligWorkersActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("id del trabajador");
        ColumnsName.add("funciones y obligaciones del trabajador");
        Panel_TableDBManager FuncAndWorkersOblig = new Panel_TableDBManager("ccpd_security_measures", "workers_functionsandobligations", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "funciones y obligaciones del trabajador");
        RemoveUnneededColumns(FuncAndWorkersOblig, 3);
        AddObjecttoOperationsPanel(FuncAndWorkersOblig);
    }//GEN-LAST:event_jBFuncAndObligWorkersActionPerformed

    private void JTreatDescrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTreatDescrActionPerformed
        ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");
        ColumnsName.add("descripción del tratamiento");
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        Panel_TableDBManager TreatDescr = new Panel_TableDBManager("ccpd_security_measures", "datatreatment_manager", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Descripción del tratamiento");
        RemoveUnneededColumnsselected(TreatDescr, 3);
        RemoveUnneededColumnsselected(TreatDescr, 2);
        RemoveUnneededColumnsselected(TreatDescr, 0);
        AddObjecttoOperationsPanel(TreatDescr);
    }//GEN-LAST:event_JTreatDescrActionPerformed

    private void jBBehaviourCodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBehaviourCodesActionPerformed
         ColumnsName = new CLAllObjectList<>();
        ColumnsName.add("índice");        
        ColumnsName.add("id cliente");
        ColumnsName.add("id empresa");
        ColumnsName.add("códigos de conducta");
        Panel_TableDBManager BehaCodes = new Panel_TableDBManager("ccpd_security_measures", "behaviourcodes", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsName, "Códigos de conducta");
        RemoveUnneededColumns(BehaCodes, 3);
        AddObjecttoOperationsPanel(BehaCodes);
    }//GEN-LAST:event_jBBehaviourCodesActionPerformed
    void AddObjecttoOperationsPanel(Component Cnt) {
        jInnerSurfacePanel.removeAll();
        jInnerSurfacePanel.invalidate();
        //JInnerSPanel.setLayout(new FlowLayout());
        jInnerSurfacePanel.add(Cnt);
        //JInnerSPanel.setVisible(true);        
        jInnerSurfacePanel.setVisible(true);
        jInnerSurfacePanel.validate();
        jInnerSurfacePanel.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAcessList;
    private javax.swing.JButton JBCessionsTargets;
    private javax.swing.JButton JRBaseDatos;
    private javax.swing.JButton JTreatDescr;
    private javax.swing.JButton jBAuthiorizations;
    private javax.swing.JButton jBAuthorDel;
    private javax.swing.JButton jBBehaviourCodes;
    private javax.swing.JButton jBCpyREstReg;
    private javax.swing.JButton jBExternal;
    private javax.swing.JButton jBFuncAndObligWorkers;
    private javax.swing.JButton jBInOutexitorRecData;
    private javax.swing.JButton jBIncidenceReg;
    private javax.swing.JButton jBMediaandDocsSources;
    private javax.swing.JButton jBNominations;
    private javax.swing.JButton jBSanctions;
    private javax.swing.JButton jBSecurityDescrProcedures;
    private javax.swing.JButton jBSpecialProc;
    private javax.swing.JButton jExit;
    private javax.swing.JPanel jInnerSurfacePanel;
    private javax.swing.JButton jRAlternatMeasures;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jUpperMenu_Panel;
    // End of variables declaration//GEN-END:variables
}
