/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;

import ccpd.es.p8dbmanager.FDBManExtra;
import static beleris.es.finalinformationmanager.MainErrorManager.AcceptInformation;
import static beleris.es.finalinformationmanager.MainErrorManager.mconfyes;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CL_DBCV;
import static ccpd.es.p8config.P8Config.PConfig;
import java.util.List;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class List_CatDestTransfer extends javax.swing.JPanel {

    private static final long serialVersionUID = -1644676842352599898L;

    /**
     * Creates new form List_CatDestTransfer
     */
    public List_CatDestTransfer() {
        initComponents();
        JPTable.getColumnModel().getColumn(0).setWidth(10);
        LoadList();
        FillPanel();
        //     PruebaSQLLite();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JPTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jInsertRow = new javax.swing.JButton();
        jUpdateRow = new javax.swing.JButton();
        jDeleteRow = new javax.swing.JButton();
        jExitPanel = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1080, 650));
        setMinimumSize(new java.awt.Dimension(1080, 650));
        setPreferredSize(new java.awt.Dimension(1080, 650));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 540));

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setColumnHeaderView(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(960, 540));

        JPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Índice", "Destinatarios transferencias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JPTable.setDoubleBuffered(true);
        JPTable.setFillsViewportHeight(true);
        JPTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        JPTable.setMaximumSize(new java.awt.Dimension(1080, 540));
        JPTable.setMinimumSize(new java.awt.Dimension(1080, 540));
        JPTable.setPreferredSize(new java.awt.Dimension(1080, 540));
        JPTable.setShowGrid(true);
        jScrollPane2.setViewportView(JPTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel1.setText("Lista de categorías de destinatarios de las transferencias de datos personales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jInsertRow.setText("Insertar");
        jInsertRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertRowActionPerformed(evt);
            }
        });
        jPanel2.add(jInsertRow);

        jUpdateRow.setText("Actualizar");
        jUpdateRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateRowActionPerformed(evt);
            }
        });
        jPanel2.add(jUpdateRow);

        jDeleteRow.setText("Borrar");
        jDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteRowActionPerformed(evt);
            }
        });
        jPanel2.add(jDeleteRow);

        jExitPanel.setText("Salir");
        jExitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitPanelActionPerformed(evt);
            }
        });
        jPanel2.add(jExitPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateRowActionPerformed
        UpdateDBWithTableData();
    }//GEN-LAST:event_jUpdateRowActionPerformed

    private void jExitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitPanelActionPerformed
        UpdateDBData();
        setVisible(false);
        removeAll();
        revalidate();
        repaint();
    }//GEN-LAST:event_jExitPanelActionPerformed

    private void jInsertRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertRowActionPerformed
        InsertRow();
    }//GEN-LAST:event_jInsertRowActionPerformed

    private void jDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteRowActionPerformed
        DeleteRow();
    }//GEN-LAST:event_jDeleteRowActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JPTable;
    private javax.swing.JButton jDeleteRow;
    private javax.swing.JButton jExitPanel;
    private javax.swing.JButton jInsertRow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jUpdateRow;
    // End of variables declaration//GEN-END:variables
    FDBManExtra DBMSAP;
    List<String> DEST;

    private void FillPanel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" idregistro ");
        model.addColumn(" Destinatarios transferencias internacionales ");
        model.setRowCount(0);
        int index = 1;
        if (!DEST.isEmpty()) {
            ListIterator<String> dli = DEST.listIterator();
            while (dli.hasNext()) {
                String TheNext = " " + dli.next() + " ";
                var Number = String.format("%03d", index);
                model.addRow(new Object[]{Number, TheNext});
                index++;
            }
            JPTable.setModel(model);
        }
        AddEmptyRow();

    }

    private void LoadList() {
        //SELECT * FROM ccpd_lists.list_cat_desttransint;
        PConfig.setDBName("ccpd_lists");
        DBMSAP = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        DEST = DBMSAP.LoadList("list_cat_desttransint", "targetinternattrans");

    }

    private void UpdateDBWithTableData() {
        int ntf = AcceptInformation("¿Está seguro de que quiere actualizar los datos?");
        if (ntf == mconfyes) {
            UpdateDBData();
        }
    }

    void AddEmptyRow() {
        int index = JPTable.getModel().getRowCount() + 1;
        DefaultTableModel model = (DefaultTableModel) JPTable.getModel();
        var Number = String.format("%03d", index);
        model.addRow(new Object[]{Number, ""});
    }

    private void InsertRow() {
        int index = JPTable.getModel().getRowCount() - 1;
        String sIndex = (String) JPTable.getModel().getValueAt(index, 0);
        String sDestinatary = (String) JPTable.getModel().getValueAt(index, 1);
        //CL_DBCV CamposPanel=new CL_DBCV();
        CLAllObjectList<CL_DBCV> List_CamposPanel = new CLAllObjectList<>();
        List_CamposPanel.add(new CL_DBCV(sDestinatary, sIndex));
        DBMSAP.InsertDatainDB("list_cat_desttransint", List_CamposPanel);
        AddEmptyRow();
    }

    private void DeleteRow() {
        int ntf = AcceptInformation("¿Está seguro de que quiere borrar la fila seleccionada?");
        if (ntf == mconfyes) {
            int index = JPTable.getSelectedRow();
            ((DefaultTableModel) JPTable.getModel()).removeRow(index);
        }
    }

    private void UpdateDBData() {
        int totalindex = JPTable.getModel().getRowCount();
        int index = 0;
        CLAllObjectList<CL_DBCV> List_CamposPanel = new CLAllObjectList<>();
        while (index < totalindex) {
            String sIndex = (String) JPTable.getModel().getValueAt(index, 0);
            String sDestinatary = (String) JPTable.getModel().getValueAt(index, 1);
            if (!"".equals(sDestinatary)) {
                List_CamposPanel.add(new CL_DBCV(sDestinatary, sIndex));
            }
            index++;
        }
        DBMSAP.DeleteDataTable("list_cat_desttransint");
        DBMSAP.InsertDatainDB("list_cat_desttransint", List_CamposPanel);
    }
}
