/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;

import ccpd.es.p8dbmanager.FDBManExtra;
import static beleris.es.finalinformationmanager.MainErrorManager.AcceptInformation;
import static beleris.es.finalinformationmanager.MainErrorManager.mconfyes;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CLDBColumnsList;
import beleris.es.finalprimaryclasses.CL_DBColumns;
import static ccpd.es.p8config.P8Config.PConfig;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class List_ImpactEvaluation extends javax.swing.JPanel {

    private static final long serialVersionUID = 4501548454663453996L;

    private FDBManExtra DBMSAP;

    /**
     * Creates new form List_ImpactEvaluation
     */
    public List_ImpactEvaluation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JPTable = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel1.setText("Lista de categorías de destinatarios de las transferencias de datos personales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setColumnHeaderView(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(960, 540));

        JPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Índice", "Destinatarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JPTable.setDoubleBuffered(true);
        JPTable.setFillsViewportHeight(true);
        JPTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        JPTable.setMaximumSize(new java.awt.Dimension(1080, 540));
        JPTable.setMinimumSize(new java.awt.Dimension(1080, 540));
        JPTable.setPreferredSize(new java.awt.Dimension(1080, 540));
        JPTable.setShowGrid(true);
        jScrollPane2.setViewportView(JPTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JPTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    CLDBColumnsList Columns = new CLDBColumnsList();
    CLAllObjectList<String> IDX;
    CLAllObjectList<String> DESC;
    CLAllObjectList<String> EVAL;
    CLAllObjectList<String> IDENTERP;
    CLAllObjectList<String> IDCLIENT;

    private void LoadList() {
        //SELECT * FROM ccpd_lists.list_cat_desttransint;
        PConfig.setDBName("ccpd_lists");
        DBMSAP = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        IDX = DBMSAP.LoadList("list_impact_evaluation", "idlist_impact_evaluation");
        Columns.addCol(new CL_DBColumns("idlist_impact_evaluation", new CLAllObjectList<String>(IDX)));
        DESC = DBMSAP.LoadList("list_impact_evaluation", "impact_description");
        Columns.addCol(new CL_DBColumns("impact_description", new CLAllObjectList<String>(DESC)));
        EVAL = DBMSAP.LoadList("list_impact_evaluation", "impact_evaluation");
        Columns.addCol(new CL_DBColumns("impact_evaluation", new CLAllObjectList<String>(EVAL)));
        IDENTERP = DBMSAP.LoadList("list_impact_evaluation", "identerprise");
        Columns.addCol(new CL_DBColumns("identerprise", new CLAllObjectList<String>(IDENTERP)));
        IDCLIENT = DBMSAP.LoadList("list_impact_evaluation", "idclient");
        Columns.addCol(new CL_DBColumns("idclient", new CLAllObjectList<String>(IDCLIENT)));
    }

    private void FillPanel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" índice ");
        model.addColumn(" evaluación ");
        model.addColumn(" descripción ");
        model.setRowCount(0);
        int index = 1;
        if (!IDX.isEmpty()) {
            ListIterator<String> de_li = DESC.listIterator();
            ListIterator<String> eva_li = EVAL.listIterator();
            while (de_li.hasNext()) {
                String de_TheNext = " " + de_li.next() + " ";
                String eva_TheNext = " " + eva_li.next() + " ";
                var Number = String.format("%03d", index);
                model.addRow(new Object[]{Number, de_TheNext, eva_TheNext});
                index++;
            }
            JPTable.setModel(model);
        }

        AddEmptyRow();

    }

    private void UpdateDBWithTableData() {
        int ntf = AcceptInformation("¿Está seguro de que quiere actualizar los datos?");
        if (ntf == mconfyes) {
            UpdateDBData();
        }
    }

    void AddEmptyRow() {
        int index = JPTable.getModel().getRowCount() + 1;
        DefaultTableModel model = (DefaultTableModel) JPTable.getModel();
        var Number = String.format("%03d", index);
        model.addRow(new Object[]{Number, "", ""});
    }

    private void InsertRow() {
        CLDBColumnsList CLT = new CLDBColumnsList();
        CLAllObjectList<String> clolTmpDEST = new CLAllObjectList<>();
        CLAllObjectList<String> clolTmpCODE = new CLAllObjectList<>();
        CLAllObjectList<String> clolTmpIDX = new CLAllObjectList<>();
        int index = JPTable.getSelectedRow();
        String sCol_1 = (String) JPTable.getModel().getValueAt(index, 0);
        String sCol_2 = (String) JPTable.getModel().getValueAt(index, 1);
        String sCol_3 = (String) JPTable.getModel().getValueAt(index, 2);
        CLT.addCol(new CL_DBColumns("idlist_impact_evaluation", clolTmpIDX));
        CLT.addCol(new CL_DBColumns("impact_description", clolTmpCODE));
        CLT.addCol(new CL_DBColumns("impact_evaluation", clolTmpDEST));
        CLT.getElements().get(0).getElementList().add(sCol_1);
        CLT.getElements().get(1).getElementList().add(sCol_2);
        CLT.getElements().get(2).getElementList().add(sCol_3);
        CLT.getElements().get(3).getElementList().add(IDENTERP.get(index));
        CLT.getElements().get(4).getElementList().add(IDCLIENT.get(index));
        DBMSAP.InsertDatainDB("list_impact_evaluation", CLT);
        AddEmptyRow();
    }

    private void DeleteRow() {
        int ntf = AcceptInformation("¿Está seguro de que quiere borrar la fila seleccionada?");
        if (ntf == mconfyes) {
            int index = JPTable.getSelectedRow();
            ((DefaultTableModel) JPTable.getModel()).removeRow(index);
        }
    }

    private void UpdateDBData() {
        int totalindex = JPTable.getModel().getRowCount();
        int icol, irows = 0;
        CLDBColumnsList LCP = new CLDBColumnsList();

        CLAllObjectList<String> ColumnList = new CLAllObjectList<>();
        ColumnList.add("idlist_impact_evaluation");
        ColumnList.add("impact_description");
        ColumnList.add("impact_evaluation");
        icol = ColumnList.size();
        CLAllObjectList<String> Rows = new CLAllObjectList<>();
        for (int idx = 0; idx < icol; idx++) {
            String Colname = ColumnList.get(idx);
            int irow = JPTable.getModel().getRowCount();
            Rows.clear();
            for (int idx2 = 0; idx2 < irow; idx2++) {
                String sCode = (String) JPTable.getModel().getValueAt(idx2, idx);
                Rows.add(sCode);
            }
            LCP.addCol(new CL_DBColumns(Colname, new CLAllObjectList<String>(Rows)));
            LCP.getElements().get(3).getElementList().add(IDENTERP.get(irow));
            LCP.getElements().get(4).getElementList().add(IDCLIENT.get(irow));
        }

        DBMSAP.DeleteDataTable("list_impact_evaluation");
        DBMSAP.InsertDatainDB("list_impact_evaluation", LCP);
    }
}
