/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;

import ccpd.es.p8dbmanager.FDBManExtra;
import static beleris.es.finalinformationmanager.MainErrorManager.AcceptInformation;
import static beleris.es.finalinformationmanager.MainErrorManager.mconfyes;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CLDBColumnsList;
import beleris.es.finalprimaryclasses.CL_DBColumns;
import static ccpd.es.p8config.P8Config.PConfig;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class List_CatTargetCessions extends javax.swing.JPanel {

    private static final long serialVersionUID = -3387005627447706284L;

    /**
     * Creates new form List_CatTargetCessions
     */
    public List_CatTargetCessions() {
        initComponents();
        JPTable.getColumnModel().getColumn(0).setWidth(10);
        LoadList();
        FillPanel();
        //     PruebaSQLLite()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JPTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jInsertRow = new javax.swing.JButton();
        jUpdateRow = new javax.swing.JButton();
        jDeleteRow = new javax.swing.JButton();
        jExitPanel = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(980, 800));
        setMinimumSize(new java.awt.Dimension(980, 800));
        setPreferredSize(new java.awt.Dimension(980, 800));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel1.setText("Lista de categorías de destinatarios de las cesiones de datos personales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setColumnHeaderView(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(960, 540));

        JPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Índice", "Destinatarios cesiones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JPTable.setDoubleBuffered(true);
        JPTable.setFillsViewportHeight(true);
        JPTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        JPTable.setMaximumSize(new java.awt.Dimension(1080, 540));
        JPTable.setMinimumSize(new java.awt.Dimension(1080, 540));
        JPTable.setPreferredSize(new java.awt.Dimension(1080, 540));
        JPTable.setShowGrid(true);
        jScrollPane2.setViewportView(JPTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane2, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jInsertRow.setText("Insertar");
        jInsertRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertRowActionPerformed(evt);
            }
        });
        jPanel2.add(jInsertRow);

        jUpdateRow.setText("Actualizar");
        jUpdateRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateRowActionPerformed(evt);
            }
        });
        jPanel2.add(jUpdateRow);

        jDeleteRow.setText("Borrar");
        jDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteRowActionPerformed(evt);
            }
        });
        jPanel2.add(jDeleteRow);

        jExitPanel.setText("Salir");
        jExitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitPanelActionPerformed(evt);
            }
        });
        jPanel2.add(jExitPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitPanelActionPerformed
        UpdateDBData();
        setVisible(false);
        removeAll();
        revalidate();
        repaint();
    }//GEN-LAST:event_jExitPanelActionPerformed

    private void jDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteRowActionPerformed
        DeleteRow();
    }//GEN-LAST:event_jDeleteRowActionPerformed

    private void jUpdateRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateRowActionPerformed
        UpdateDBWithTableData();
    }//GEN-LAST:event_jUpdateRowActionPerformed

    private void jInsertRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertRowActionPerformed
        InsertRow();
    }//GEN-LAST:event_jInsertRowActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JPTable;
    private javax.swing.JButton jDeleteRow;
    private javax.swing.JButton jExitPanel;
    private javax.swing.JButton jInsertRow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jUpdateRow;
    // End of variables declaration//GEN-END:variables

    FDBManExtra DBMSAP;
    CLAllObjectList<String> DEST;
    CLAllObjectList<String> CODE;
    CLAllObjectList<String> IDX;
    CLDBColumnsList Columns = new CLDBColumnsList();

    private void FillPanel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" índice ");
        model.addColumn(" código ");
        model.addColumn(" Categorías de destinatarios de cesiones ");
        model.setRowCount(0);
        int index = 1;
        if (!CODE.isEmpty() && !DEST.isEmpty()) {
            ListIterator<String> co_li = CODE.listIterator();
            ListIterator<String> de_li = DEST.listIterator();
            while (co_li.hasNext()) {
                String co_TheNext = " " + co_li.next() + " ";
                String de_TheNext = " " + de_li.next() + " ";
                var Number = String.format("%03d", index);
                model.addRow(new Object[]{Number, co_TheNext, de_TheNext});
                index++;
            }
            JPTable.setModel(model);
        }

        AddEmptyRow();

    }

    private void LoadList() {
        //SELECT * FROM ccpd_lists.list_cat_desttransint;
        PConfig.setDBName("ccpd_lists");
        DBMSAP = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        IDX = DBMSAP.LoadList("list_cat_targetcessions", "id_fe_cat_targetcessions");
        Columns.addCol(new CL_DBColumns("id_fe_cat_targetcessions", new CLAllObjectList<String>(IDX)));
        DEST = DBMSAP.LoadList("list_cat_targetcessions", "cessionstargetcategories");
        Columns.addCol(new CL_DBColumns("cessionstargetcategories", new CLAllObjectList<String>(DEST)));
        CODE = DBMSAP.LoadList("list_cat_targetcessions", "idcode");
        Columns.addCol(new CL_DBColumns("idcode", new CLAllObjectList<String>(CODE)));
    }

    private void UpdateDBWithTableData() {
        int ntf = AcceptInformation("¿Está seguro de que quiere actualizar los datos?");
        if (ntf == mconfyes) {
            UpdateDBData();
        }
    }

    void AddEmptyRow() {
        int index = JPTable.getModel().getRowCount() + 1;
        DefaultTableModel model = (DefaultTableModel) JPTable.getModel();
        var Number = String.format("%03d", index);
        model.addRow(new Object[]{Number, "", ""});
    }

    private void InsertRow() {
        CLDBColumnsList CLT = new CLDBColumnsList();
        CLAllObjectList<String> clolTmpDEST = new CLAllObjectList<>();
        CLAllObjectList<String> clolTmpCODE = new CLAllObjectList<>();
        CLAllObjectList<String> clolTmpIDX = new CLAllObjectList<>();
        int index = JPTable.getSelectedRow();
        String sCol_1 = (String) JPTable.getModel().getValueAt(index, 0);
        String sCol_2 = (String) JPTable.getModel().getValueAt(index, 1);
        String sCol_3 = (String) JPTable.getModel().getValueAt(index, 2);
        CLT.addCol(new CL_DBColumns("id_fe_cat_targetcessions", clolTmpIDX));
        CLT.addCol(new CL_DBColumns("idcode", clolTmpCODE));
        CLT.addCol(new CL_DBColumns("cessionstargetcategories", clolTmpDEST));
        CLT.getElements().get(0).getElementList().add(sCol_1);
        CLT.getElements().get(1).getElementList().add(sCol_2);
        CLT.getElements().get(2).getElementList().add(sCol_3);
        DBMSAP.InsertDatainDB("list_cat_targetcessions", CLT);
        AddEmptyRow();
    }

    private void DeleteRow() {
        int ntf = AcceptInformation("¿Está seguro de que quiere borrar la fila seleccionada?");
        if (ntf == mconfyes) {
            int index = JPTable.getSelectedRow();
            ((DefaultTableModel) JPTable.getModel()).removeRow(index);
        }
    }

    private void UpdateDBData() {
        int totalindex = JPTable.getModel().getRowCount();
        int icol, irows = 0;
        CLDBColumnsList LCP = new CLDBColumnsList();

        CLAllObjectList<String> ColumnList = new CLAllObjectList<>();
        ColumnList.add("id_fe_cat_targetcessions");
        ColumnList.add("idcode");
        ColumnList.add("cessionstargetcategories");
        icol = ColumnList.size();
        CLAllObjectList<String> Rows = new CLAllObjectList<>();
        for (int idx = 0; idx < icol; idx++) {
            String Colname = ColumnList.get(idx);
            int irow = JPTable.getModel().getRowCount();
            Rows.clear();
            for (int idx2 = 0; idx2 < irow; idx2++) {
                String sCode = (String) JPTable.getModel().getValueAt(idx2, idx);
                Rows.add(sCode);
            }
            LCP.addCol(new CL_DBColumns(Colname, new CLAllObjectList<String>(Rows)));
        }
        DBMSAP.DeleteDataTable("list_cat_targetcessions");
        DBMSAP.InsertDatainDB("list_cat_targetcessions", LCP);
    }
}
