/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;

import ccpd.es.p8dbmanager.FDBManExtra;
import static beleris.es.finalinformationmanager.MainErrorManager.AcceptInformation;
import static beleris.es.finalinformationmanager.MainErrorManager.mconfyes;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CLDBColumnsList;
import beleris.es.finalprimaryclasses.CL_DBColumns;
import static ccpd.es.p8config.P8Config.PConfig;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class List_SourceMedia extends javax.swing.JPanel {

    private static final long serialVersionUID = -3578411265382642793L;

    private FDBManExtra DBMSAP;

    /**
     * Creates new form List_SourceMedia
     */
    public List_SourceMedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        JPTable = new javax.swing.JTable();

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setColumnHeaderView(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(960, 540));

        JPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Índice", "Destinatarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JPTable.setDoubleBuffered(true);
        JPTable.setFillsViewportHeight(true);
        JPTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        JPTable.setMaximumSize(new java.awt.Dimension(1080, 540));
        JPTable.setMinimumSize(new java.awt.Dimension(1080, 540));
        JPTable.setPreferredSize(new java.awt.Dimension(1080, 540));
        JPTable.setShowGrid(true);
        jScrollPane2.setViewportView(JPTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1564, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 782, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JPTable;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    CLDBColumnsList Columns = new CLDBColumnsList();
    CLAllObjectList<String> IDX;
    CLAllObjectList<String> MEDIANAME;

    private void LoadList() {
        //SELECT * FROM ccpd_lists.list_cat_desttransint;
        PConfig.setDBName("ccpd_lists");
        DBMSAP = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        IDX = DBMSAP.LoadList("list_tsourcemedia", "idtsourcemedia");
        Columns.addCol(new CL_DBColumns("idtsourcemedia", new CLAllObjectList<String>(IDX)));
        MEDIANAME = DBMSAP.LoadList("list_tsourcemedia", "sourcemedia_name");

    }

    private void FillPanel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" índice ");
        model.addColumn(" tipo de medio ");

        model.setRowCount(0);
        int index = 1;
        if (!IDX.isEmpty()) {
            ListIterator<String> de_li = MEDIANAME.listIterator();

            while (de_li.hasNext()) {
                String de_TheNext = " " + de_li.next() + " ";

                var Number = String.format("%03d", index);
                model.addRow(new Object[]{Number, de_TheNext});
                index++;
            }
            JPTable.setModel(model);
        }

        AddEmptyRow();

    }

    private void UpdateDBWithTableData() {
        int ntf = AcceptInformation("¿Está seguro de que quiere actualizar los datos?");
        if (ntf == mconfyes) {
            UpdateDBData();
        }
    }

    void AddEmptyRow() {
        int index = JPTable.getModel().getRowCount() + 1;
        DefaultTableModel model = (DefaultTableModel) JPTable.getModel();
        var Number = String.format("%03d", index);
        model.addRow(new Object[]{Number, "", ""});
    }

    private void InsertRow() {
        CLDBColumnsList CLT = new CLDBColumnsList();
        CLAllObjectList<String> clolTmpMEDIANAME = new CLAllObjectList<>();
        CLAllObjectList<String> clolTmpIDX = new CLAllObjectList<>();
        int index = JPTable.getSelectedRow();
        String sCol_1 = (String) JPTable.getModel().getValueAt(index, 0);
        String sCol_2 = (String) JPTable.getModel().getValueAt(index, 1);

        CLT.addCol(new CL_DBColumns("idtsourcemedia", clolTmpIDX));
        CLT.addCol(new CL_DBColumns("sourcemedia_name", clolTmpMEDIANAME));

        CLT.getElements().get(0).getElementList().add(sCol_1);
        CLT.getElements().get(1).getElementList().add(sCol_2);
        DBMSAP.InsertDatainDB("list_tsourcemedia", CLT);
        AddEmptyRow();
    }

    private void DeleteRow() {
        int ntf = AcceptInformation("¿Está seguro de que quiere borrar la fila seleccionada?");
        if (ntf == mconfyes) {
            int index = JPTable.getSelectedRow();
            ((DefaultTableModel) JPTable.getModel()).removeRow(index);
        }
    }

    private void UpdateDBData() {
        int totalindex = JPTable.getModel().getRowCount();
        int icol, irows = 0;
        CLDBColumnsList LCP = new CLDBColumnsList();

        CLAllObjectList<String> ColumnList = new CLAllObjectList<>();
        ColumnList.add("idtsourcemedia");
        ColumnList.add("sourcemedia_name");
        icol = ColumnList.size();
        CLAllObjectList<String> Rows = new CLAllObjectList<>();
        for (int idx = 0; idx < icol; idx++) {
            String Colname = ColumnList.get(idx);
            int irow = JPTable.getModel().getRowCount();
            Rows.clear();
            for (int idx2 = 0; idx2 < irow; idx2++) {
                String sCode = (String) JPTable.getModel().getValueAt(idx2, idx);
                Rows.add(sCode);
            }
            LCP.addCol(new CL_DBColumns(Colname, new CLAllObjectList<String>(Rows)));

        }

        DBMSAP.DeleteDataTable("list_tsourcemedia");
        DBMSAP.InsertDatainDB("list_tsourcemedia", LCP);
    }
}
