/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;

import ccpd.es.p8dbmanager.FDBManExtra;
import static beleris.es.finalinformationmanager.MainErrorManager.AcceptInformation;
import static beleris.es.finalinformationmanager.MainErrorManager.mconfyes;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CL_DBCV;
import static ccpd.es.p8config.P8Config.PConfig;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.border.Border;
import static javax.swing.border.TitledBorder.ABOVE_TOP;
import static javax.swing.border.TitledBorder.CENTER;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class Panel_TableDBManager extends javax.swing.JPanel {

    private static final long serialVersionUID = 1918709098284117119L;

    /**
     * Creates new form ClientOperations
     */
    public Panel_TableDBManager() {
        initComponents();
        jTabla.putClientProperty("terminateEditOnFocusLost", true);
        CreateTableChangesDetector();
        /// ScrollPanel.add(JPTable);
      //  ScrollPanel.revalidate();
        LoadList();
        FillPanel();
    }

    public Panel_TableDBManager(String tmpDB, String tmpTable) {
        initComponents();
        ActualDBName = tmpDB;
        ActualDBTable = tmpTable;
        //   ScrollPanel.add(JPTable);
        //  ScrollPanel.revalidate();
        jTabla.putClientProperty("terminateEditOnFocusLost", true);
        CreateTableChangesDetector();
        LoadList();
        FillPanel();
    }

    public Panel_TableDBManager(String tmpDB, String tmpTable, CLAllObjectList<String> tmpColumnsName) {
        initComponents();
        ActualDBName = tmpDB;
        ActualDBTable = tmpTable;
        //   ScrollPanel.add(JPTable);
        jTabla.putClientProperty("terminateEditOnFocusLost", true);
        CreateTableChangesDetector();
        LoadList();
        ColumnsName = tmpColumnsName;
        FillPanel();
    }

    public Panel_TableDBManager(String tmpDB, String tmpTable, String TmpClient, String TmpEnterprise, CLAllObjectList<String> tmpColumnsName, String tmpTitle) {
        initComponents();
        ActualDBName = tmpDB;
        ActualDBTable = tmpTable;
        ActualClient = TmpClient;
        ActualEnterprise = TmpEnterprise;
        jTabla.putClientProperty("terminateEditOnFocusLost", true);
        Border blackline = this.getBorder();
        blackline = BorderFactory.createTitledBorder(blackline, tmpTitle, ABOVE_TOP, CENTER);
        setBorder(blackline);
        //     ScrollPanel.add(JPTable);
        //     ScrollPanel.revalidate();
        CreateTableChangesDetector();
        LoadList(ActualClient, ActualEnterprise);
        ColumnsName = tmpColumnsName;
        FillPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JUpperPanel = new javax.swing.JPanel();
        jInsertRow = new javax.swing.JButton();
        jUpdateRow = new javax.swing.JButton();
        jDeleteRow = new javax.swing.JButton();
        jExitPanel = new javax.swing.JButton();
        ScrollPanel = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        setMaximumSize(new java.awt.Dimension(1560, 660));
        setMinimumSize(new java.awt.Dimension(1560, 660));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1560, 660));
        setLayout(new java.awt.GridBagLayout());

        JUpperPanel.setMaximumSize(new java.awt.Dimension(1560, 40));
        JUpperPanel.setMinimumSize(new java.awt.Dimension(1560, 40));
        JUpperPanel.setPreferredSize(new java.awt.Dimension(1560, 40));
        JUpperPanel.setLayout(new java.awt.GridLayout(1, 0));

        jInsertRow.setText("Insertar");
        jInsertRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertRowActionPerformed(evt);
            }
        });
        JUpperPanel.add(jInsertRow);

        jUpdateRow.setText("Actualizar");
        jUpdateRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateRowActionPerformed(evt);
            }
        });
        JUpperPanel.add(jUpdateRow);

        jDeleteRow.setText("Borrar");
        jDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteRowActionPerformed(evt);
            }
        });
        JUpperPanel.add(jDeleteRow);

        jExitPanel.setText("Salir");
        jExitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitPanelActionPerformed(evt);
            }
        });
        JUpperPanel.add(jExitPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(JUpperPanel, gridBagConstraints);

        ScrollPanel.setMaximumSize(new java.awt.Dimension(1560, 620));
        ScrollPanel.setMinimumSize(new java.awt.Dimension(1560, 620));
        ScrollPanel.setPreferredSize(new java.awt.Dimension(1560, 620));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPanel.setViewportView(jTabla);

        add(ScrollPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jInsertRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertRowActionPerformed
        InsertRow();
    }//GEN-LAST:event_jInsertRowActionPerformed

    private void jUpdateRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateRowActionPerformed
        UpdateDBWithTableData();
    }//GEN-LAST:event_jUpdateRowActionPerformed

    private void jDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteRowActionPerformed
        DeleteRow();
    }//GEN-LAST:event_jDeleteRowActionPerformed

    private void jExitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitPanelActionPerformed
        UpdateDBData();
        PConfig.RestoreHelpconfig();
        setVisible(false);
        removeAll();
        revalidate();
        repaint();
    }//GEN-LAST:event_jExitPanelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JUpperPanel;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JButton jDeleteRow;
    private javax.swing.JButton jExitPanel;
    private javax.swing.JButton jInsertRow;
    private javax.swing.JTable jTabla;
    private javax.swing.JButton jUpdateRow;
    // End of variables declaration//GEN-END:variables
    String ActualDBName = "", ActualDBTable = "", ActualClient = "", ActualEnterprise = "";
    // Variables declaration - do not modify                     
    // End of variables declaration                   
    FDBManExtra DBManager = null;
    boolean TableUpdated = false;
    int firstRowupdated = 0, lastRowupdated = 0;
    CLAllObjectList<CLAllObjectList<String>> CLIOP = new CLAllObjectList<>();
    CLAllObjectList<String> ColumnsName = new CLAllObjectList<>();

    private void FillPanel() {
        DefaultTableModel tmodel = new DefaultTableModel();
        for (int idx = 0; idx < ColumnsName.size(); idx++) {
            Object[] cdata = CLIOP.get(idx).toArray();
            tmodel.addColumn(" " + ColumnsName.get(idx) + " ", cdata);
        }
        getJPTable().setModel(tmodel);
        AddEmptyRow();
        //ShowDInfo("rellenado panel");

    }

    private void LoadList() {
        //SELECT * FROM ccpd_lists.list_cat_desttransint;
        PConfig.setDBName("ccpd_registers");
        DBManager = new FDBManExtra(PConfig.getSQLURL() + ActualDBName, PConfig.getAdminDBPassword(), ActualDBName, PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        ColumnsName = DBManager.GetColumnsName(ActualDBTable);
        CLIOP = DBManager.LoadList_Table(ActualDBName, ActualDBTable, ColumnsName);
        //ShowDInfo("Cargando datos ...");
    }

    private void UpdateDBWithTableData() {
        int ntf = AcceptInformation("¿Está seguro de que quiere actualizar los datos?");
        if (ntf == mconfyes) {
            UpdateDBData();
        }
    }

    void AddEmptyRow() {
        DefaultTableModel model = (DefaultTableModel) getJPTable().getModel();
        int count = ColumnsName.size();
        Vector rowData = new Vector();
        for (int idx = 0; idx < count; idx++) {
            rowData.add(null);
        }
        model.addRow(rowData);
    }

    private void InsertRow() {
        int index = getJPTable().getModel().getRowCount() - 1;
        String sIndex = (String) getJPTable().getModel().getValueAt(index, 0);
        CLAllObjectList<CL_DBCV> List_CamposPanel = new CLAllObjectList<>();
        int CLS = getJPTable().getModel().getColumnCount() - 1;
        for (int idx = 0; idx < CLS; idx++) {
            String sOperations = (String) getJPTable().getModel().getValueAt(index, idx + 1);
            List_CamposPanel.add(new CL_DBCV(sOperations, sIndex));
        }
        DBManager.InsertDatainDB("dbclients", List_CamposPanel);
        AddEmptyRow();
    }

    private void DeleteRow() {
        int ntf = AcceptInformation("¿Está seguro de que quiere borrar la fila seleccionada?");
        if (ntf == mconfyes) {
            int index = getJPTable().getSelectedRow();
            ((DefaultTableModel) getJPTable().getModel()).removeRow(index);
        }
    }

    private void UpdateDBData() {
        DefaultTableModel tmodel = (DefaultTableModel) getJPTable().getModel();
      //  if (TableUpdated) { TableUpdated CODE NOT WORKING, WHY???
            for (int col = 0; col < ColumnsName.size(); col++) {
                for (int row = firstRowupdated; row <= lastRowupdated; row++) {
                    CLAllObjectList<CL_DBCV> FieldList = new CLAllObjectList<>();
                    if (tmodel.getValueAt(row, col) instanceof String) {
                        String sTheRowElement = (String) tmodel.getValueAt(row, col);
                        CLIOP.get(col + 1).set(row + 1, sTheRowElement);
                        CL_DBCV Field = new CL_DBCV(ColumnsName.get(col + 1), sTheRowElement);
                        FieldList.add(Field);
                    } else if (tmodel.getValueAt(row, col) instanceof JComboBox) {
                        JComboBox jcbTheRowElement = (JComboBox) tmodel.getValueAt(row, col);
                        String sTheRowElement = Integer.toString(jcbTheRowElement.getSelectedIndex());
                        CLIOP.get(col + 1).set(row + 1, sTheRowElement);

                        CL_DBCV Field = new CL_DBCV(ColumnsName.get(col + 1), sTheRowElement);
                        FieldList.add(Field);

                    }
                    DBManager.UpdateTable(ActualDBTable, FieldList);
                    FieldList.clear();
                }

        //    }

            //  CLIOP = DBManager.LoadList_Table(ActualDBName, ActualDBTable, Columns, ActualClient, ActualEnterprise);
        }

    }

    private void LoadList(String ActualClient, String ActualEnterprise) {

        //SELECT * FROM ccpd_lists.list_cat_desttransint;
        PConfig.setDBName(ActualDBName);
        DBManager = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), ActualDBName, PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        ColumnsName = DBManager.MYSQL_GetColumnsName(ActualDBTable);
        CLIOP = DBManager.LoadList_Table(ActualDBName, ActualDBTable, ColumnsName, ActualClient, ActualEnterprise);
        //ShowDInfo("Cargando datos ...");
    }

     //  tableChanged CODE NOT WORKING, WHY???
    private void CreateTableChangesDetector() {

        DefaultTableModel TheModel = (DefaultTableModel) getJPTable().getModel();

        TheModel.addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent tme) {
                int tm = tme.getType();
                if (tme.getType() == TableModelEvent.UPDATE) {
                    TableUpdated = true;
                    firstRowupdated = tme.getFirstRow();
                    lastRowupdated = tme.getLastRow();
                }
            }
        });
    }

    /**
     * @return the JPTable
     */
    public javax.swing.JTable getJPTable() {
        return jTabla;
    }

    /**
     * @param JPTable the JPTable to set
     */
    public void setJPTable(javax.swing.JTable JPTabla) {
        this.jTabla = JPTabla;
    }

}
