/*
 @author Emilio David Diaus López 2008-2021
 * *
 * *
 */
package ccpd.es.p8panels;

import ccpd.es.p8dbmanager.FDBManExtra;
import beleris.es.finalprimaryclasses.NAlmRes;
import beleris.es.finalprimaryclasses.NTypeQuestions;
import beleris.es.finalprimaryclasses.NExcluibles;
import beleris.es.finalprimaryclasses.NQuestions;
import java.awt.Color;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import org.openide.LifecycleManager;
import org.openide.util.RequestProcessor;
import beleris.es.finalinformationmanager.LoggingManagerGenerator;
import beleris.es.finalprimaryclasses.CL_Client;
import beleris.es.finalprimaryclasses.CL_NSC;
import beleris.es.finalutils.GraphicImageManager;
import beleris.es.finalutils.WebFileComposer;
import static ccpd.es.p8config.P8Config.PConfig;

/**
 *
 * @author Emilio David Diaus López 2008-2021
 */
public class PCreatingReportDocument extends javax.swing.JPanel /*implements HelpCtx.Provider */ {

    private static final long serialVersionUID = -7992068338815256305L;

    /**
     * Creates new form PCreatingReportDocument
     */
    public PCreatingReportDocument() {
        initComponents();
        LoadingDataLists();
    }

    private void LoadingDataLists() {
        String ActualClient = PConfig.getActualClient().getsIDClient();
        String ActualEnterprise = PConfig.getActualEnterprise().getsIDEnterprise();
        PConfig.setDBName("ccpd_compliancereports");
        DBManager = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        TFLQuestionsList = DBManager.LoadListQuestions(PConfig.getDBName(), "questions");
        TotalQuestions = TFLQuestionsList.size() - 1;
        TFLNAnswersList = DBManager.LoadAnswersList(PConfig.getDBName(), "answers", ActualClient, ActualEnterprise);
        //TotalQuestions = TFLQuestionsList.size() - 1;
        TotalAnswers = TFLNAnswersList.size() - 1;
        TFLNExcludedList = DBManager.LoadExcludedList(PConfig.getDBName(), "excluded", ActualClient, ActualEnterprise);
        TFLNQuestionTypesList = DBManager.LoadQuestionTypesList("question_types", "question_types_name");
    }

    /*
    void RecreateExcludedTable() {
        List<NExcluibles> NExcluiblesCreate = new ArrayList();
        NExcluiblesCreate.add(new NExcluibles(1, 7));
        NExcluiblesCreate.add(new NExcluibles(2, 8));
        NExcluiblesCreate.add(new NExcluibles(3, 9));
        NExcluiblesCreate.add(new NExcluibles(4, 6));
        NExcluiblesCreate.add(new NExcluibles(5, 10));
        NExcluiblesCreate.add(new NExcluibles(6, 1));
        NExcluiblesCreate.add(new NExcluibles(7, 13));
        NExcluiblesCreate.add(new NExcluibles(8, 14));
        NExcluiblesCreate.add(new NExcluibles(9, 16));
        NExcluiblesCreate.add(new NExcluibles(10, 7));
        NExcluiblesCreate.add(new NExcluibles(11, 8));
        NExcluiblesCreate.add(new NExcluibles(12, 9));
        NExcluiblesCreate.add(new NExcluibles(13, 6));
        NExcluiblesCreate.add(new NExcluibles(14, 10));
        NExcluiblesCreate.add(new NExcluibles(15, 4));
        NExcluiblesCreate.add(new NExcluibles(16, 13));
        NExcluiblesCreate.add(new NExcluibles(17, 14));
        NExcluiblesCreate.add(new NExcluibles(18, 16));
        // NExcluiblesCreate.add(new NExcluibles(1, 1));

        NExcluiblesJpaController NExcluibles_DBControler = new NExcluiblesJpaController(PM.getTheEMFactory());
        NExcluiblesCreate.forEach(NExcluibles_DBControler::create);

        //   setProgress(100);
    }
     */
    public PCreatingReportDocument(CL_Client tmpClient) {

        initComponents();

        MyClient = tmpClient;
        LoadingDataLists();
        // CCPD3.CCPD3View.HM.setTopic("CreacionInformeCumplimiento", CCPD3.CCPD3View.Ayuda.CInformeCumplimiento);
        LoggingManagerGenerator.getGlobalLogger().info("Entrada al diálogo de creación del informe de cumplimiento.");
        jIV.setText("  000% ");
        jAD.setText("  000% ");
        jCE.setText("  000% ");
        jECI.setText("  000% ");
        jESI.setText("  000% ");
        jEC.setText("  000% ");
        // HelpCtx.setHelpIDString(this, "ccpd.es.creatingdocuments.reportdoc");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jBProcess = new javax.swing.JButton();
        jBExitPanel = new javax.swing.JButton();
        jBExitProgram = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jEC = new javax.swing.JLabel();
        jIV = new javax.swing.JLabel();
        jAD = new javax.swing.JLabel();
        jCE = new javax.swing.JLabel();
        jECI = new javax.swing.JLabel();
        jESI = new javax.swing.JLabel();

        setBackground(java.awt.Color.lightGray);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(750, 450));
        setMinimumSize(new java.awt.Dimension(750, 450));
        setPreferredSize(new java.awt.Dimension(750, 450));
        setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(java.awt.Color.lightGray);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true), org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jPanel3.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(700, 400));
        jPanel3.setMinimumSize(new java.awt.Dimension(700, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setMaximumSize(new java.awt.Dimension(650, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 60));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jBProcess.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBProcess, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jBProcess.text")); // NOI18N
        jBProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcessActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jBProcess, gridBagConstraints);

        jBExitPanel.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBExitPanel, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jBExitPanel.text")); // NOI18N
        jBExitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitPanelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jBExitPanel, gridBagConstraints);

        jBExitProgram.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBExitProgram, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jBExitProgram.text")); // NOI18N
        jBExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitProgramActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jBExitProgram, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(java.awt.Color.lightGray);
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setMaximumSize(new java.awt.Dimension(650, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(650, 250));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 250));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 24));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jLabel2.text")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setMaximumSize(new java.awt.Dimension(250, 24));
        jLabel2.setMinimumSize(new java.awt.Dimension(250, 24));
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jLabel3.text")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setMaximumSize(new java.awt.Dimension(250, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(250, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(250, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jLabel6.text")); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setMaximumSize(new java.awt.Dimension(250, 24));
        jLabel6.setMinimumSize(new java.awt.Dimension(250, 24));
        jLabel6.setPreferredSize(new java.awt.Dimension(250, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jLabel5.text")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setMaximumSize(new java.awt.Dimension(250, 24));
        jLabel5.setMinimumSize(new java.awt.Dimension(250, 24));
        jLabel5.setPreferredSize(new java.awt.Dimension(250, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jLabel4.text")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setMaximumSize(new java.awt.Dimension(250, 24));
        jLabel4.setMinimumSize(new java.awt.Dimension(250, 24));
        jLabel4.setPreferredSize(new java.awt.Dimension(250, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jLabel4, gridBagConstraints);

        jEC.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jEC, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jEC.text")); // NOI18N
        jEC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jEC.setMaximumSize(new java.awt.Dimension(60, 24));
        jEC.setMinimumSize(new java.awt.Dimension(60, 24));
        jEC.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jEC, gridBagConstraints);

        jIV.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jIV, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jEC.text_5")); // NOI18N
        jIV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jIV.setMaximumSize(new java.awt.Dimension(60, 24));
        jIV.setMinimumSize(new java.awt.Dimension(60, 24));
        jIV.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jIV, gridBagConstraints);

        jAD.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jAD, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jEC.text_4")); // NOI18N
        jAD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAD.setMaximumSize(new java.awt.Dimension(60, 24));
        jAD.setMinimumSize(new java.awt.Dimension(60, 24));
        jAD.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jAD, gridBagConstraints);

        jCE.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jCE, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jEC.text_3")); // NOI18N
        jCE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCE.setMaximumSize(new java.awt.Dimension(60, 24));
        jCE.setMinimumSize(new java.awt.Dimension(60, 24));
        jCE.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jCE, gridBagConstraints);

        jECI.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jECI, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jEC.text")); // NOI18N
        jECI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jECI.setMaximumSize(new java.awt.Dimension(60, 24));
        jECI.setMinimumSize(new java.awt.Dimension(60, 24));
        jECI.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jECI, gridBagConstraints);

        jESI.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jESI, org.openide.util.NbBundle.getMessage(PCreatingReportDocument.class, "PCreatingReportDocument.jEC.text_1")); // NOI18N
        jESI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jESI.setMaximumSize(new java.awt.Dimension(60, 24));
        jESI.setMinimumSize(new java.awt.Dimension(60, 24));
        jESI.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel2.add(jESI, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jPanel2, gridBagConstraints);

        add(jPanel3, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jBProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcessActionPerformed
        Runnable Ejecutable = new Runnable() {

            public void run() {

                TotalProcess();

                return;
            }

        };
        RequestProcessor.getDefault().post(Ejecutable);

    }//GEN-LAST:event_jBProcessActionPerformed

    private void jBExitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitPanelActionPerformed
        // TODO add your handling code here:        
        setVisible(false);
        removeAll();
        revalidate();
        repaint();
    }//GEN-LAST:event_jBExitPanelActionPerformed

    private void jBExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitProgramActionPerformed
        LifecycleManager.getDefault().exit();
    }//GEN-LAST:event_jBExitProgramActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAD;
    private javax.swing.JButton jBExitPanel;
    private javax.swing.JButton jBExitProgram;
    private javax.swing.JButton jBProcess;
    private javax.swing.JLabel jCE;
    private javax.swing.JLabel jEC;
    private javax.swing.JLabel jECI;
    private javax.swing.JLabel jESI;
    private javax.swing.JLabel jIV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    FDBManExtra DBManager = null;

    List<NExcluibles> TFLNExcludedList = null;
    List<NAlmRes> TFLNAnswersList = null;
    List<NQuestions> TFLQuestionsList = null;
    List<NTypeQuestions> TFLNQuestionTypesList = null;

    WebFileComposer utHTFC = null;
    private CL_Client MyClient = new CL_Client();

    float fPercentAffirmativeExcludingNAQuestions;
    int iProcess = 0;

    long lsTime = 12;
    GraphicImageManager UTGraphicManager;

    final String PercentformatString = "  %03.0f%% ";

    private int TotalAnswers = 0;
    private int TotalQuestions = 0;

    String NumberToBar(int iNumber, char cBar) {
        int counter = 0;
        String sResult = null;
        String sCad = "";
        while (counter < iNumber) {
            sCad = sCad + cBar;
            counter++;
        }
        sResult = sCad;
        return sResult;
    }

    void Tsleep(long time) {
        try {
            Thread.sleep(time);
        } catch (InterruptedException e) {
        }
    }

    void InitGraphicImage() {
        UTGraphicManager = new GraphicImageManager(610, 610);
        UTGraphicManager.DrawWhiteBackGround(20, 20, 600, 600);
        UTGraphicManager.DrawFrame(30, 30, 570, 570);
    }

    void FillWholeImage(float fPercentAfirmativeTotalQuestions, float fPercentAfirmativeExcludingNAQuestions, float fPorcentExclu, float fPorcenFalladas) {
        String sTmp = null;
        //UT_GMan.DrawWhiteBackGround(10, 200, 500, 100);
        //  g2.filliPorcenAfirFinal / 10;
        sTmp = String.format("%03.0f", fPercentAfirmativeTotalQuestions * 100);
        UTGraphicManager.WritePercentBar("% Totales Acertadas " + sTmp + "%", fPercentAfirmativeTotalQuestions, 60, 100, Color.blue);
        sTmp = String.format("%03.0f", fPercentAfirmativeExcludingNAQuestions * 100);
        UTGraphicManager.WritePercentBar("% Totales Acertadas descontando excluidas " + sTmp + "%", fPercentAfirmativeExcludingNAQuestions, 60, 150, Color.blue);
        sTmp = String.format("%03.0f", fPorcenFalladas * 100);
        UTGraphicManager.WritePercentBar("% Totales no acertadas " + sTmp + "%", fPorcenFalladas, 60, 200, Color.red);
        sTmp = String.format("%03.0f", fPorcentExclu * 100);
        UTGraphicManager.WritePercentBar("% Totales excluidas " + sTmp + "%", fPorcentExclu, 60, 250, Color.gray);
        //UT_GMan.WritePercentBar("% Totales Acertadas no excluidas", fPercentAffirmativeExcludingNAQuestions, 30, 300, Color.BLUE);
        CreateChart(fPercentAfirmativeTotalQuestions, fPorcenFalladas, fPorcentExclu);
        sTmp = null;
    }

    void CreateChart(float fPercentAfirmativeTotalQuestions, float fPorcenFalladas, float fPorcetExclu) {

        UTGraphicManager.DrawArc(200, 300, fPercentAfirmativeTotalQuestions, fPorcenFalladas, fPorcetExclu);
    }

    void WriteImage() {
        UTGraphicManager.WriteImage();
    }

    synchronized void WriteFirstHeaders() {

        //String sSQLQueryRes = "SELECT * FROM `n_alm_res` WHERE idcliente=2 and idpregunta=1;";
        int icounter = 1, iTotalQuestions = 0, iAffirmOkQuestions = 0, iExcludedQuestions = 0;
        float fPercentAfirmativeTotalQuestions = 0;//,fTemp=0;

        String sTmp = null;
        String sTmpResStr = null, sTmpExcluStr = null;

        iTotalQuestions = TotalAnswers;
        for (icounter = 0; icounter < iTotalQuestions; icounter++) {

            Tsleep(lsTime);
            NAlmRes Resp = TFLNAnswersList.get(icounter);
            // NExcluibles Exclu=TFLNExcludedList.get(icounter);
            sTmpResStr = Integer.toString(Resp.getId_question());
            sTmpExcluStr = Resp.getExcluded().toString();
            if ("1".equals(sTmpResStr)) {
                iAffirmOkQuestions++;
            } else if ("1".equals(sTmpExcluStr)) {
                iExcludedQuestions++;
            }
            float percent = (((icounter + 1.0f) / iTotalQuestions) * 100);
            sTmp = String.format(PercentformatString, percent);
            jIV.setText(sTmp);
        }
        jIV.setText("  100% ");
        fPercentAfirmativeTotalQuestions = ((iAffirmOkQuestions + 1.0f) / iTotalQuestions);

        fPercentAffirmativeExcludingNAQuestions = ((iAffirmOkQuestions + 1.0f) / (iTotalQuestions - iExcludedQuestions));

        int iAffirmativeAnswerFinal = (int) iAffirmOkQuestions;
        int iTotalesFinal = iTotalQuestions;
        int iExcluded = iExcludedQuestions;
        float fPercExcl = ((iExcludedQuestions) / iTotalQuestions);
        float fPercentAffirFinal = fPercentAfirmativeTotalQuestions;
        float fPercenAffirFinalwithExc = fPercentAffirmativeExcludingNAQuestions;
        float fPercenFailed = (1.0f - (fPercenAffirFinalwithExc));
        //   int iPorcenAfirFinalconExc = (int) fPercentAffirmativeExcludingNAQuestions * 100;
        //    int iPorcenAfirFinal = (int) fPercentAfirmativeTotalQuestions * 100;
        //  int iPregTotales = (int) iTotalQuestions;
        int iComputableQuestions = (iTotalQuestions - iExcludedQuestions);
        int iQuestionsAffirSucessfull = iAffirmOkQuestions;

        utHTFC.WriteGlobalTitle("Tecnologías de protección de datos");
        utHTFC.WriteOpenBody();
        utHTFC.WriteHorizLine();
        utHTFC.WriteHeaderTable("4", "4", "4", "100%");
        utHTFC.WriteOpenRowLine();
        utHTFC.WriteImageinCell("logonuevo-dpt.png", "solid", "30%", "30%");
        utHTFC.WriteSubTitleLine("Tecnologías de gestión de protección de datos (c) Copyright 2008-2017 Emilio David Diaus López");
        utHTFC.WriteCloseRowLine();
        utHTFC.WriteCloseTable();
        utHTFC.WriteHorizLine();
        utHTFC.WriteHeader("INFORME DE CUMPLIMIENTO", utHTFC.sHsize1);
        sTmp = String.format(PercentformatString, 00.0);
        jCE.setText(sTmp);
        jAD.setText(sTmp);
        Tsleep(lsTime * 2);
        //  repaint();
        utHTFC.WriteHorizLine();
        utHTFC.WriteHorizLine();
        utHTFC.WriteHeaderTable("4", "4", "4", "80%");
        utHTFC.WriteOpenRowLine();
        utHTFC.WriteSubCategoryTitleLine("DATOS GENERALES");
        utHTFC.WriteCloseRowLine();
        utHTFC.WriteHorizLine();
        utHTFC.WriteOpenRowLine();
        sTmp = String.format(PercentformatString, 20.0);
        jCE.setText(sTmp);
        jAD.setText(sTmp);
        Tsleep(lsTime * 2);
        //      repaint();
        utHTFC.WriteDataCell("Preguntas Totales");
        utHTFC.WriteDataCell(String.format("%03d", iTotalesFinal));
        utHTFC.WriteDataCell("Preguntas Afirmativas");
        utHTFC.WriteDataCell(String.format("%03d", iAffirmativeAnswerFinal));
        utHTFC.WriteDataCell("Preguntas Excluidas");
        utHTFC.WriteDataCell(String.format("%03d", iExcluded));
        utHTFC.WriteCloseRowLine();
        utHTFC.WriteOpenRowLine();
        sTmp = String.format(PercentformatString, 40.0);
        jCE.setText(sTmp);
        jAD.setText(sTmp);
        Tsleep(lsTime * 2);
        //     repaint();

        utHTFC.WriteDataCell("Preguntas Totales");
        utHTFC.WriteDataCell(String.format("%03.0f", 100.0) + "%");
        utHTFC.WriteDataCell("Preguntas Afirmativas");
        utHTFC.WriteDataCell(String.format("%03.0f", fPercentAffirFinal * 100) + "%");
        utHTFC.WriteDataCell("Preguntas Excluidas");
        utHTFC.WriteDataCell(String.format("%03.0f", fPercenAffirFinalwithExc * 100) + "%");
        utHTFC.WriteCloseRowLine();
        utHTFC.WriteOpenRowLine();
        utHTFC.WriteTitleLine("Porcentaje Total de cumplimiento");
        utHTFC.WriteCloseRowLine();
        utHTFC.WriteOpenRowLine();
        sTmp = String.format(PercentformatString, 60.0);
        jCE.setText(sTmp);
        jAD.setText(sTmp);

        Tsleep(lsTime * 2);
        //    repaint();
        utHTFC.WriteDataCell("Preguntas computables totales");
        utHTFC.WriteDataCell(String.format("%03d", iComputableQuestions));
        utHTFC.WriteDataCell("Preguntas computadas afirmativas");
        utHTFC.WriteDataCell(String.format("%03d", iQuestionsAffirSucessfull));
        utHTFC.WriteDataCell("Porcentaje final de cumplimiento de la protección de datos");
        utHTFC.WriteDataCell(String.format("%03.0f", fPercenAffirFinalwithExc * 100) + "%");
        utHTFC.WriteCloseRowLine();
        utHTFC.WriteOpenRowLine();
        sTmp = String.format(PercentformatString, 80.0);
        jCE.setText(sTmp);
        jAD.setText(sTmp);
        Tsleep(lsTime * 2);

        utHTFC.WriteTitleLine("Porcentaje Total por categor&iacute;as");
        utHTFC.WriteCloseRowLine();
        sTmp = String.format(PercentformatString, 100.0);
        jCE.setText(sTmp);
        jAD.setText(sTmp);
        //     Tsleep(lsTime * 2);
        //    String BarraTotal = NumberToBar(iPorcenAfirFinal / 10, 'O');
        //  String BarraTotalconExclusiones = NumberToBar(iPorcenAfirFinalconExc / 10, 'O');
        InitGraphicImage();
        FillWholeImage(fPercentAfirmativeTotalQuestions, fPercentAffirmativeExcludingNAQuestions, fPercExcl, fPercenFailed);
        WriteImage();
    }

    void WriteHeadersResume() {
        //    String sSQLQueryNTipPreg = "SELECT idtippreg,tpreg FROM " + ccpd.CCPD3View.OCP.getTable_questions_QuestionsTypes() + ";";
        //  String sSQLQueryPreg = "SELECT idpreguntas," + PConfig.getTable_questions_Questions()
        //         + ".tpreg AS ntpreg," + PConfig.getTable_questions_QuestionsTypes()
        //          + ".tpreg AS tpreg FROM " + PConfig.getTable_questions_Questions()
        // +" JOIN " + PConfig.getTable_questions_QuestionsTypes() + " ON " //          + PConfig.getTable_questions_Questions() + ".tpreg="
        //         + PConfig.getTable_questions_QuestionsTypes() + ".idtippreg";

        String sTmpRes = null, sTmpExclu = null, sTmp = null, sTmpTip = null;
        int iSize = 0, iCount = 0;
        List<CL_NSC> vUTNSCvec = null;
        CL_NSC ncTmp = null;
        int fLastRowofCat = 0, fCount = 0, fCountCat = 0, fLastRowofThisCat = 0,
                fCompute = 0, fExcluded = 0;
        float fPercent = 0.0f;

        fLastRowofCat = TotalAnswers;

        vUTNSCvec = new ArrayList();

        for (fCount = 0; fCount < fLastRowofCat; fCount++) {

            Tsleep(lsTime);

            NAlmRes Resp = TFLNAnswersList.get(fCount);
            sTmpRes = Integer.toString(Resp.getId_question());
            sTmpExclu = Resp.getExcluded().toString();

            NQuestions Question = TFLQuestionsList.get(fCount);
            iCount = Question.getId_questiontype();
            iCount--;
            if (iCount < 0) {
                iCount = 0;
            }
            try {
                ncTmp = vUTNSCvec.get(iCount);
            } catch (IndexOutOfBoundsException ex) {
                ncTmp = null;
            }

            if (ncTmp == null) {
                ncTmp = new CL_NSC(iCount, Integer.parseInt(sTmpRes), Integer.parseInt(sTmpExclu), fCountCat + 1);
                vUTNSCvec.add(ncTmp);
            } else {
                ncTmp = vUTNSCvec.get(iCount);
                ncTmp.setAfirmative(ncTmp.getAfirmative() + Integer.parseInt(sTmpRes));
                ncTmp.setExcluded(ncTmp.getExcluded() + Integer.parseInt(sTmpExclu));
                ncTmp.setTotal(ncTmp.getTotal() + 1);
                vUTNSCvec.set(iCount, ncTmp);
            }
            fPercent = (((fCount + 1.0f) / fLastRowofCat) * 100);
            sTmp = String.format(PercentformatString, fPercent);
            jECI.setText(sTmp);
            Tsleep(lsTime * 2);
            // repaint();
        }
        jECI.setText("  100% ");
        fCountCat = 0;

        jECI.setText("100% ");

        iSize = vUTNSCvec.size();
        fCompute = 0;
        fExcluded = 0;
        for (fCount = 0; fCount < iSize; fCount++) {

            NTypeQuestions QTy = TFLNQuestionTypesList.get(fCount);

            sTmpTip = QTy.getQuestion_types_name();

            ncTmp = vUTNSCvec.get(fCount);
            if (ncTmp != null) {
                fLastRowofThisCat = ncTmp.getTotal();
                if (ncTmp.getAfirmative() > 0) {
                    fCompute++;
                }
                if (ncTmp.getExcluded() > 0) {
                    fExcluded++;
                }
                utHTFC.WriteOpenRowLine();
                utHTFC.WriteTitleLine(sTmpTip);
                utHTFC.WriteCloseRowLine();
                utHTFC.WriteOpenRowLine();
                utHTFC.WriteDataCell("Preguntas totales");
                utHTFC.WriteDataCell(String.format("%03d", fLastRowofThisCat));
                utHTFC.WriteDataCell("Preguntas afirmativas");
                utHTFC.WriteDataCell(String.format("%03d", fCompute));
                utHTFC.WriteDataCell("Preguntas excluidas");
                utHTFC.WriteDataCell(String.format("%03d", fExcluded));
                fPercentAffirmativeExcludingNAQuestions = (fCompute / (fLastRowofThisCat - fExcluded) * 100.0f);
                utHTFC.WriteDataCell("Porcentaje");
                utHTFC.WriteDataCell(String.format("%03.0f", fPercentAffirmativeExcludingNAQuestions) + "%");
                utHTFC.WriteCloseRowLine();
                fPercent = (((fCount + 1.0f) / iSize) * 100);
                sTmp = String.format(PercentformatString, fPercent);
                jECI.setText(sTmp);
                Tsleep((long) (lsTime * 1.5));
                // repaint();
            }
            jECI.setText("  100% ");
        }

        utHTFC.WriteOpenRowLine();
        //utHTFC.WriteTitleLine("Graficos");

        utHTFC.WriteImageinCell("graficos.png", "solid", "100%", "100%");

        utHTFC.WriteCloseRowLine();

        utHTFC.WriteOpenRowLine();

        utHTFC.WriteTitleLine("Indice de Protección de Datos");
        utHTFC.WriteCloseRowLine();

        utHTFC.WriteOpenRowLine();

        utHTFC.WriteDataCell("Porcentaje");
        utHTFC.WriteDataCell(String.format("%03.0f", fPercentAffirmativeExcludingNAQuestions) + "%");
        utHTFC.WriteCloseRowLine();

        utHTFC.WriteOpenRowLine();
        if (fPercentAffirmativeExcludingNAQuestions < 50) {
            utHTFC.WriteDataCell("Su índice de protección de datos es crítico, tiene mucho que mejorar, lea las recomendaciones"
                    + " y aplíquelas");
        } else if (fPercentAffirmativeExcludingNAQuestions < 75) {
            utHTFC.WriteDataCell("Su índice de protección de datos es muy bajo, tiene bastante que mejorar, lea las recomendaciones"
                    + " y aplíquelas");
        } else if (fPercentAffirmativeExcludingNAQuestions < 85) {
            utHTFC.WriteDataCell("Su índice de protección de datos es bueno, pero tiene que mejorar, lea las recomendaciones"
                    + " y aplíquelas");
        } else if (fPercentAffirmativeExcludingNAQuestions < 90) {
            utHTFC.WriteDataCell("Su índice de protección de datos es muy bueno, pero tiene que mejorar un poco, lea las recomendaciones"
                    + " y aplíquelas");
        } else if (fPercentAffirmativeExcludingNAQuestions < 98) {
            utHTFC.WriteDataCell("Su índice de protección de datos es casi perfecto, pero tiene que mejorar hasta llegar al 100%, lea las recomendaciones"
                    + " y aplíquelas");
        }

        utHTFC.WriteCloseRowLine();
    }

    void WriteReportRecommendations() {

        int iLastRow = 0, iCount = 0;
        float iPercent = 0.0f;
        String sSQLQueryPreg = null, sTmpResStr = null, sTmpExcluStr = null, sTmpPre = null, sTmp = null;

        utHTFC.WriteHorizLine();
        utHTFC.WriteHeaderTable("5", "5", "5", "85%");
        utHTFC.WriteOpenRowLine();
        utHTFC.WriteSubCategoryTitleLine("Recomendaciones");
        utHTFC.WriteCloseRowLine();
        utHTFC.WriteHorizLine();

        iLastRow = TotalAnswers;
        iProcess = 1;
        for (iCount = 0; iCount < iLastRow; iCount++) {
            NAlmRes Resp = TFLNAnswersList.get(iCount);
            NQuestions Question = TFLQuestionsList.get(iCount);
            NTypeQuestions QType = TFLNQuestionTypesList.get(Question.getId_questiontype());
            sTmpResStr = Integer.toString(Resp.getId_question());
            sTmpExcluStr = Resp.getExcluded().toString();
            if (("0".equals(sTmpResStr)) || ("0".equals(sTmpExcluStr))) {
                int questionty = Question.getId_questiontype();
                sTmpPre = QType.getQuestion_types_name();
                utHTFC.WriteOpenRowLine();
                utHTFC.WriteTitleLine(sTmpPre);
                utHTFC.WriteCloseRowLine();
                utHTFC.WriteOpenRowLine();
                utHTFC.WriteSubTitleLine("Num");
                utHTFC.WriteSubTitleLine("Pregunta");
                utHTFC.WriteSubTitleLine("Recomendación");
                utHTFC.WriteCloseRowLine();
                utHTFC.WriteDataCell(String.valueOf(iCount + 1));

                sTmpPre = Question.getQuestion_string();

                utHTFC.WriteDataCell(sTmpPre);
                sTmpPre = Question.getQuestion_recomendation();
                utHTFC.WriteDataCell(sTmpPre);
                utHTFC.WriteCloseRowLine();
                iPercent = (((iCount + 1.0f) / iLastRow) * 100);
                sTmp = String.format(PercentformatString, iPercent);
                jESI.setText(sTmp);
                Tsleep(lsTime);
                //                 repaint();

            }

        }

        jESI.setText("  100% ");
        utHTFC.WriteCloseTable();

        utHTFC.WriteCloseTable();

        utHTFC.WriteHorizLine();

        utHTFC.WriteHorizLine();
    }

    void DataBasePreparation() {
        utHTFC = new WebFileComposer("Informe.html");
    }

    void OpenReportDocument() throws MalformedURLException, IOException {
        Runtime rt;
        String OSName = System.getProperty("os.name");
        rt = Runtime.getRuntime();

        if ("windows".equals(OSName)) {
            try {
                rt.exec("cmd /c start Informe.html");

            } catch (IOException ex) {
                LoggingManagerGenerator.getGlobalLogger().log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                rt.exec("firefox Informe.html");

            } catch (IOException ex) {
                LoggingManagerGenerator.getGlobalLogger().log(Level.SEVERE, null, ex);
            }
        }

    }

    void Exiting() {
        utHTFC.WriteCloseBody();
        utHTFC.HTMLWriteCloseAll();
    }

    void ProcessReportComplaint() {
        jEC.setText("  000% ");
        // PGenVar.UpdateProgressStatusBar(0);
        DataBasePreparation();
        jEC.setText("  025% ");
        //   PGenVar.UpdateProgressStatusBar(25);
        WriteFirstHeaders();
        jEC.setText("  050% ");
        //   PGenVar.UpdateProgressStatusBar(50);
        WriteHeadersResume();
        jEC.setText("  075% ");
        //   PGenVar.UpdateProgressStatusBar(75);
        WriteReportRecommendations();
        jEC.setText("  080% ");
        Tsleep(lsTime);
        Exiting();
        //  PGenVar.UpdateProgressStatusBar(80);
        try {
            jEC.setText("  085% ");
            //      PGenVar.UpdateProgressStatusBar(85);
            Tsleep(lsTime);
            OpenReportDocument();
            jEC.setText("  090% ");
            //    PGenVar.UpdateProgressStatusBar(90);
            Tsleep(lsTime);
        } catch (MalformedURLException ex) {
            LoggingManagerGenerator.getGlobalLogger().log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            LoggingManagerGenerator.getGlobalLogger().log(Level.SEVERE, null, ex);
        }
        jEC.setText("  095% ");
        //     PGenVar.UpdateProgressStatusBar(95);
        Tsleep(lsTime);
        //    PGenVar.UpdateProgressStatusBar(100);
        jEC.setText("  100% ");
        Tsleep(lsTime);

    }

    void TotalProcess() {

        jBProcess.setVisible(false);
        jBExitPanel.setVisible(false);
        jBExitProgram.setVisible(false);
        ProcessReportComplaint();
        jBProcess.setVisible(true);
        jBExitPanel.setVisible(true);
        jBExitProgram.setVisible(true);

    }
    /*
    @Override
    public HelpCtx getHelpCtx() {
        return new HelpCtx("ccpd.es.NewCreateDocuments.reportdoc");
    }*/
}
