/*
 @author Emilio David Diaus López 2008-2021
 * *
 * *
 */
package ccpd.es.p8panels;

import ccpd.es.p8dbmanager.FDBManExtra;
import ccpd.es.p8dbmanager.FDBManExtra;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.NAlmRes;
import beleris.es.finalprimaryclasses.NTypeQuestions;
import beleris.es.finalprimaryclasses.NExcluibles;
import beleris.es.finalprimaryclasses.CL_Client;
import beleris.es.finalprimaryclasses.CL_DBCV;
import beleris.es.finalprimaryclasses.NQuestions;
import static ccpd.es.p8config.P8Config.PConfig;
import java.math.BigInteger;
import java.util.List;
import org.openide.LifecycleManager;

/**
 *
 * @author Emilio David Diaus López 2008-2021
 */
public class PFillingReportQuestions extends javax.swing.JPanel /*implements HelpCtx.Provider */ {

    private static final long serialVersionUID = -4091826082475960238L;

    private String idActualClient;
    private String idActualEnterprise;

    /**
     * Creates new form PGettingReportData
     */
    public PFillingReportQuestions() {
        initComponents();
        LoadingDataLists();
        ResIndex = GetAnswersCompleted() - 1;
        UpdateDataPanel(ResIndex);
        UpdateDataFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLQuestionText = new javax.swing.JTextArea();
        ButtonsPanel = new javax.swing.JPanel();
        jBFirst = new javax.swing.JButton();
        jBRewind = new javax.swing.JButton();
        jBForward = new javax.swing.JButton();
        jBLast = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRBNegative = new javax.swing.JButton();
        jRBAfirmative = new javax.swing.JButton();
        jRBNoAplicable = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JBExitDialog = new javax.swing.JButton();
        jBExitProgram = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLActualQuestionNumber = new javax.swing.JLabel();
        jLQuestionCategory = new javax.swing.JLabel();
        jLClientName = new javax.swing.JLabel();
        jLTotalQuestions = new javax.swing.JLabel();
        JEEtiquetaDe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.Color.lightGray);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(1100, 500));
        setMinimumSize(new java.awt.Dimension(1100, 500));
        setPreferredSize(new java.awt.Dimension(1100, 500));
        setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(java.awt.Color.lightGray);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true), org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jPanel4.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel4.setMaximumSize(new java.awt.Dimension(1095, 425));
        jPanel4.setMinimumSize(new java.awt.Dimension(1095, 425));
        jPanel4.setPreferredSize(new java.awt.Dimension(1095, 425));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(1060, 200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1060, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1060, 200));

        jLQuestionText.setEditable(false);
        jLQuestionText.setBackground(java.awt.Color.lightGray);
        jLQuestionText.setColumns(20);
        jLQuestionText.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLQuestionText.setLineWrap(true);
        jLQuestionText.setRows(5);
        jLQuestionText.setWrapStyleWord(true);
        jLQuestionText.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jLQuestionText.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jLQuestionText.setMaximumSize(new java.awt.Dimension(1060, 200));
        jLQuestionText.setMinimumSize(new java.awt.Dimension(1060, 200));
        jLQuestionText.setPreferredSize(new java.awt.Dimension(1060, 200));
        jScrollPane1.setViewportView(jLQuestionText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jScrollPane1, gridBagConstraints);

        ButtonsPanel.setMaximumSize(new java.awt.Dimension(880, 35));
        ButtonsPanel.setMinimumSize(new java.awt.Dimension(880, 35));
        ButtonsPanel.setPreferredSize(new java.awt.Dimension(880, 35));
        ButtonsPanel.setLayout(new java.awt.GridLayout(1, 0));

        jBFirst.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBFirst, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jBFirst.text")); // NOI18N
        jBFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFirstActionPerformed(evt);
            }
        });
        ButtonsPanel.add(jBFirst);

        jBRewind.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBRewind, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jBRewind.text")); // NOI18N
        jBRewind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRewindActionPerformed(evt);
            }
        });
        ButtonsPanel.add(jBRewind);

        jBForward.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBForward, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jBForward.text")); // NOI18N
        jBForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBForwardActionPerformed(evt);
            }
        });
        ButtonsPanel.add(jBForward);

        jBLast.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBLast, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jBLast.text")); // NOI18N
        jBLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLastActionPerformed(evt);
            }
        });
        ButtonsPanel.add(jBLast);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(ButtonsPanel, gridBagConstraints);

        jPanel1.setMaximumSize(new java.awt.Dimension(540, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(540, 35));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(540, 35));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jRBNegative.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jRBNegative, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jRBNegative.text")); // NOI18N
        jRBNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNegativeActionPerformed(evt);
            }
        });
        jPanel1.add(jRBNegative);

        jRBAfirmative.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jRBAfirmative, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jRBAfirmative.text")); // NOI18N
        jRBAfirmative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAfirmativeActionPerformed(evt);
            }
        });
        jPanel1.add(jRBAfirmative);

        jRBNoAplicable.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jRBNoAplicable, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jRBNoAplicable.text")); // NOI18N
        jRBNoAplicable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoAplicableActionPerformed(evt);
            }
        });
        jPanel1.add(jRBNoAplicable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jPanel1, gridBagConstraints);

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 35));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 35));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        JBExitDialog.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(JBExitDialog, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.JBExitDialog.text")); // NOI18N
        JBExitDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExitDialogActionPerformed(evt);
            }
        });
        jPanel2.add(JBExitDialog);

        jBExitProgram.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBExitProgram, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jBExitProgram.text")); // NOI18N
        jBExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitProgramActionPerformed(evt);
            }
        });
        jPanel2.add(jBExitProgram);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(java.awt.Color.lightGray);

        jLActualQuestionNumber.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLActualQuestionNumber, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jLActualQuestionNumber.text")); // NOI18N

        jLQuestionCategory.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLQuestionCategory, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jLQuestionCategory.text")); // NOI18N

        jLClientName.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLClientName, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jLClientName.text")); // NOI18N

        jLTotalQuestions.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLTotalQuestions, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jLTotalQuestions.text")); // NOI18N

        JEEtiquetaDe.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(JEEtiquetaDe, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.JEEtiquetaDe.text")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PFillingReportQuestions.class, "PFillingReportQuestions.jLabel1.text")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(600, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLQuestionCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLActualQuestionNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JEEtiquetaDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLTotalQuestions))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLClientName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLClientName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLActualQuestionNumber)
                    .addComponent(jLQuestionCategory)
                    .addComponent(JEEtiquetaDe)
                    .addComponent(jLTotalQuestions))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jBFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFirstActionPerformed
        // TODO add your handling code here:
        ResIndex = 0;
        UpdateDataFrame();
        //  this.repaint();
    }//GEN-LAST:event_jBFirstActionPerformed

    private void jBRewindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRewindActionPerformed
        // TODO add your handling code here:
        if (ResIndex > 0) {
            ResIndex--;
            UpdateDataFrame();
        }

    }//GEN-LAST:event_jBRewindActionPerformed

    private void jBForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBForwardActionPerformed
        if (ResIndex < TotalQuestions) {
            ResIndex++;
        }

        UpdateDataFrame();
    }//GEN-LAST:event_jBForwardActionPerformed

    private void jBLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLastActionPerformed
        // TODO add your handling code here:
        ResIndex = TotalQuestions;
        UpdateDataFrame();
        // this.repaint();
    }//GEN-LAST:event_jBLastActionPerformed

    private void JBExitDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExitDialogActionPerformed
        //  PGenVar.UpdateTextProgressStatusBar(null);
        SaveDBResponse();
        PConfig.RestoreHelpconfig();
        //    DBManager3p.CloseDSConnection();
        setVisible(false);
        invalidate();

    }//GEN-LAST:event_JBExitDialogActionPerformed

    private void jBExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitProgramActionPerformed
        SaveDBResponse();
//        DBManager3p.CloseDSConnection();
        PConfig.RestoreHelpconfig();
        setVisible(false);
        invalidate();
        LifecycleManager.getDefault().exit();
    }//GEN-LAST:event_jBExitProgramActionPerformed
    public boolean CompareDBStr(String sTmpStr1, String sTmpStr2) {

        boolean bresult = false;
        int icresult = -1;

        if ((sTmpStr1 == null) || (sTmpStr2 == null)) {
        } else {

            icresult = sTmpStr1.compareTo(sTmpStr2);

            if (icresult == 0) {
                bresult = true;
            }
        }
        return bresult;
    }

    void NegativePressed() {
        int iARow = 0;
        long lPreCalc = 0, lResCalc = 0;
        iARow = ResIndex;
        lPreCalc = 1 << iARow;

        lResCalc = lResNeg & lPreCalc;

        // if (jRBNegative.isSelected() == true) {
        if (lResCalc != lPreCalc) {
            lResNeg = lResNeg + lPreCalc;
        }
        lResCalc = lResNeg & lPreCalc;
        if (lResCalc == lPreCalc) {
            lResAfir = lResAfir - lPreCalc;
        }
        lResCalc = lResExc & lPreCalc;
        if (lResCalc == lPreCalc) {
            lResExc = lResExc - lPreCalc;
        }
        jRBAfirmative.setSelected(false);
        jRBNoAplicable.setSelected(false);
        jRBNegative.setSelected(true);
        // }
        UpdateDataFrame();
    }

    void InaplicablePressed() {
        int iARow = 0;
        long lPreCalc = 0, lResCalc = 0;

        iARow = ResIndex;
        lPreCalc = 1 << iARow;
        lResCalc = lResExc & lPreCalc;

        //if (jRBNoAplicable.isSelected() == true) {
        if (lResCalc != lPreCalc) {
            lResExc = lResExc + lPreCalc;
        }
        lResCalc = lResAfir & lPreCalc;
        if (lResCalc == lPreCalc) {
            lResAfir = lResAfir - lPreCalc;
        }
        lResCalc = lResNeg & lPreCalc;
        if (lResCalc == lPreCalc) {
            lResNeg = lResNeg - lPreCalc;
        }
        jRBAfirmative.setSelected(false);
        jRBNegative.setSelected(false);
        jRBNoAplicable.setSelected(true);

        //}
        UpdateDataFrame();

    }

    void AfirmativePressed() {
        int iARow = 0;
        long lPreCalc = 0, lResCalc = 0;

        iARow = ResIndex;
        lPreCalc = 1 << iARow;
        lResCalc = lResAfir & lPreCalc;

        //if (jRBAfirmative.isSelected() == true) {
        if (lResCalc != lPreCalc) {
            lResAfir = lResAfir + lPreCalc;
        }
        lResCalc = lResNeg & lPreCalc;
        if (lResCalc == lPreCalc) {
            lResNeg = lResNeg - lPreCalc;
        }
        lResCalc = lResExc & lPreCalc;
        if (lResCalc == lPreCalc) {
            lResExc = lResExc - lPreCalc;
        }

        jRBNegative.setSelected(false);
        jRBNoAplicable.setSelected(false);
        jRBAfirmative.setSelected(true);
        //}
        UpdateDataFrame();

    }
    private void jRBNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNegativeActionPerformed
        NegativePressed();

    }//GEN-LAST:event_jRBNegativeActionPerformed

    private void jRBNoAplicableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoAplicableActionPerformed
        InaplicablePressed();

    }//GEN-LAST:event_jRBNoAplicableActionPerformed

    private void jRBAfirmativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAfirmativeActionPerformed
        AfirmativePressed();

    }//GEN-LAST:event_jRBAfirmativeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton JBExitDialog;
    private javax.swing.JLabel JEEtiquetaDe;
    private javax.swing.JButton jBExitProgram;
    private javax.swing.JButton jBFirst;
    private javax.swing.JButton jBForward;
    private javax.swing.JButton jBLast;
    private javax.swing.JButton jBRewind;
    private javax.swing.JLabel jLActualQuestionNumber;
    private javax.swing.JLabel jLClientName;
    private javax.swing.JLabel jLQuestionCategory;
    private javax.swing.JTextArea jLQuestionText;
    private javax.swing.JLabel jLTotalQuestions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jRBAfirmative;
    private javax.swing.JButton jRBNegative;
    private javax.swing.JButton jRBNoAplicable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private CL_Client MyClient = new CL_Client();
    //  DBManagerGenerator3p DBManager3p = new DBManagerGenerator3p();
    List<NExcluibles> TFLNExcludedList = null;
    List<NAlmRes> TFLNAnswersList = null;
    List<NQuestions> TFLQuestionsList = null;
    List<NTypeQuestions> TFLNQuestionTypesList = null;
    NQuestions TheQuestion = null;
    FDBManExtra DBManager = null;

    long lResAfir = 0;
    long lResExc = 0;
    long lResNeg = 0;
    long lResInex = 0;
    int ResIndex = 0;
    int iUPreguntaContestada = 0;
    int TotalQuestions = 0;
    int TotalAnswers = 0;

    CLAllObjectList<String> Columns = new CLAllObjectList<>();

    void UpdateDataFrame() {
        String sPreg = null, sTPreg = null, sNTPreg = null, sNexclu = null;

        int iTmp = 0, iARow = 0;
        long lPreCalc = 0, lResCalc = 0, lNumRows = 0;
        int lTmp = 0;
        boolean bIsEqual = false, bEqualIs = false;

        TheQuestion = TFLQuestionsList.get(ResIndex);
        jLQuestionText.setText(TheQuestion.getQuestion_string());
        jLActualQuestionNumber.setText(String.format("%03d", ResIndex));
        int questty = TheQuestion.getId_questiontype();
        sTPreg = TFLNQuestionTypesList.get(questty).getQuestion_types_name();
        iARow = ResIndex;
        if (iARow > iUPreguntaContestada) {
            iUPreguntaContestada = iARow;
        }

        lPreCalc = 1 << iARow;
        lResCalc = lResAfir & lPreCalc;

        if (lResCalc == lPreCalc) {
            jRBAfirmative.setSelected(true);
        } else {
            jRBAfirmative.setSelected(false);
        }

        lNumRows = TFLNExcludedList.size();
        bIsEqual = false;
        bEqualIs = false;

        for (lTmp = 0; lTmp < lNumRows; lTmp++) {
            NExcluibles NEX = TFLNExcludedList.get(lTmp);
            bIsEqual = CompareDBStr(Integer.toString(NEX.getNcatex()), TFLNQuestionTypesList.get(questty).toString());
            if (bIsEqual == true) {
                bEqualIs = true;
            }
        }

        if (bEqualIs == true) {
            bIsEqual = false;
            bEqualIs = false;
            jRBNoAplicable.setEnabled(true);

            lResCalc = lResExc & lPreCalc;

            if (lResCalc == lPreCalc) {
                jRBNoAplicable.setSelected(true);

            } else {
                jRBNoAplicable.setSelected(false);
            }
        } else {
            jRBNoAplicable.setEnabled(false);
        }
        if ((jRBNoAplicable.isSelected() == false) && (jRBAfirmative.isSelected() == false)) {
            jRBNegative.setSelected(true);
        } else {
            jRBNegative.setSelected(false);
        }

        float percent = (float) (100.0 * iARow / iUPreguntaContestada);
        String fmtString = String.format("%03d-%03d [%03.0f%%]", iARow, iUPreguntaContestada, percent);
    }

    v2String getPropertiesValue(int itmpvar) {

        v2String v2s = null;

        long lPreCalc = 0, rsl = 0;

        v2s = new v2String("0", "0");

        lPreCalc = 1 << itmpvar;

        rsl = lResAfir & lPreCalc;

        if (rsl == lPreCalc) {
            v2s.vres = "1";
            v2s.vexc = "0";
        } else {
            rsl = lResExc & lPreCalc;

            if (rsl == lPreCalc) {
                v2s.vres = "0";
                v2s.vexc = "1";
            }
        }
        return v2s;
    }

    /*
    @Override
    public HelpCtx getHelpCtx() {
        return new HelpCtx("ccpd.es.NewCreateDocuments.about");
    }
     */
    private void ConfigureClientandEntity() {
        idActualClient = PConfig.getActualClient().getsIDClient();
        idActualEnterprise = PConfig.getActualEnterprise().getsIDEnterprise();
    }

    private void LoadLists() {
        PConfig.setDBName("ccpd_compliancereports");
        DBManager = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        TFLQuestionsList = DBManager.LoadListQuestions("ccpd_compliancereports", "questions");
        TotalQuestions = TFLQuestionsList.size() - 1;
        TFLNAnswersList = DBManager.LoadAnswersList("ccpd_compliancereports", "answers", idActualClient, idActualEnterprise);
        //TotalQuestions = TFLQuestionsList.size() - 1;
        TotalAnswers = TFLNAnswersList.size() - 1;
        TFLNExcludedList = DBManager.LoadExcludedList("ccpd_compliancereports", "excluded", idActualClient, idActualEnterprise);
        TFLNQuestionTypesList = DBManager.LoadQuestionTypesList("question_types", "question_types_name");
        Columns = DBManager.GetColumnsName("answers");
    }

    private void LoadingDataLists() {
        ConfigureClientandEntity();
        LoadLists();

    }

    class v2String {

        v2String(String tmpvres, String tmpvexc) {
            vres = tmpvres;
            vexc = tmpvexc;
        }
        String vres = "0";
        String vexc = "0";
    }

    int GetAnswersCompleted() {
        int iCount = 0, iLastRow = 0;
        long lPreCalc;
        String sTmpExc = null, sTmpRes = null;

        iLastRow = TFLNAnswersList.size();
        // ph.start(iLastRow);
        lResAfir = 0;
        lResExc = 0;
        if (iLastRow > 0) {
            for (iCount = 0; iCount < iLastRow; iCount++) {
                NAlmRes Resp = TFLNAnswersList.get(iCount);
                sTmpRes = Integer.toString(Resp.getId_question());
                sTmpExc = Resp.getExcluded().toString();
                lPreCalc = 1 << iCount;

                if (CompareDBStr(sTmpRes, "1") == true) {
                    lResAfir |= lPreCalc;
                }
                if (CompareDBStr(sTmpExc, "1") == true) {
                    lResExc |= lPreCalc;
                }
                lPreCalc = 0;
            }
        } else {
            iLastRow = 1;
        }
        sTmpExc = null;
        sTmpRes = null;
        return iLastRow;
    }

    public void UpdateDataPanel(int progress) {
        jLClientName.setText(MyClient.getsNClient());
        String sTmp = String.format("%03d", progress);
        jLTotalQuestions.setText(sTmp);
        TheQuestion = TFLQuestionsList.get(ResIndex);
        sTmp = String.format("%03d", ResIndex);
        jLQuestionText.setText(TheQuestion.getQuestion_string());
        jLActualQuestionNumber.setText(sTmp);
        int questionty = TheQuestion.getId_questiontype();
        NTypeQuestions QType = TFLNQuestionTypesList.get(questionty);
        String sTmpPre = QType.getQuestion_types_name();
        jLQuestionCategory.setText(sTmpPre);

    }

    void UpdateTableDB() {
        CLAllObjectList<CL_DBCV> InsertFields = new CLAllObjectList<CL_DBCV>();

        for (int iTmp = 0; iTmp <= ResIndex; iTmp++) {
            //NAlmRes RESP = NewAnswersList.get(iTmp);
            NAlmRes RESP = new NAlmRes();
            if (TotalAnswers > 0 && TotalAnswers <= ResIndex) {
                RESP = TFLNAnswersList.get(iTmp);
            }
            v2String v2s = getPropertiesValue(iTmp);
            BigInteger bres = new BigInteger(v2s.vres);
            BigInteger bexc = new BigInteger(v2s.vexc);
            RESP.setTheanswer(bres);
            RESP.setExcluded(bexc);
            CL_DBCV IField = new CL_DBCV();
            // IField.setsTableDBField("id_answers");
            IField.setsValue(Integer.toString(iTmp));
            InsertFields.add(IField);
            IField = new CL_DBCV();
            //  IField.setsTableDBField("excluded");
            IField.setsValue(bexc.toString());
            InsertFields.add(IField);
            IField = new CL_DBCV();
            //  IField.setsTableDBField("id_client");
            IField.setsValue(idActualClient);
            InsertFields.add(IField);
            IField = new CL_DBCV();
            // IField.setsTableDBField("id_question");
            IField.setsValue(Integer.toString(RESP.getId_question()));
            InsertFields.add(IField);
            IField = new CL_DBCV();
            //  IField.setsTableDBField("theanswer");
            IField.setsValue(bres.toString());
            InsertFields.add(IField);
            IField = new CL_DBCV();
            //  IField.setsTableDBField("id_enterprise");
            IField.setsValue(idActualEnterprise);
            InsertFields.add(IField);
            DBManager.InsertDatainDB("answers", Columns, InsertFields);
            InsertFields.clear();
        }

    }

    public void SaveDBResponse() {
        UpdateTableDB();
    }

}
