/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;

import ccpd.es.p8dbmanager.FDBManExtra;
import static beleris.es.finalinformationmanager.MainErrorManager.AcceptInformation;
import static beleris.es.finalinformationmanager.MainErrorManager.mconfyes;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CL_DBCV;
import static ccpd.es.p8config.P8Config.PConfig;
import java.util.List;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class Sec_Nominations extends javax.swing.JPanel {

    private static final long serialVersionUID = 5009043983146740390L;

    /**
     * Creates new form Sec_Nominations
     */
    public Sec_Nominations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JPTable = new javax.swing.JTable();

        JPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JPTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JPTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    FDBManExtra DBMSAP;
    List<String> DEST;

    private void FillPanel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" idregistro ");
        model.addColumn(" Clente ");
        model.addColumn(" Empresa ");
        model.addColumn(" Nombre ");
        model.addColumn(" Posición ");
        model.addColumn(" Recursos ");

        model.setRowCount(0);
        int index = 1;
        if (!DEST.isEmpty()) {
            ListIterator<String> dli = DEST.listIterator();
            while (dli.hasNext()) {
                String TheNext = " " + dli.next() + " ";
                var Number = String.format("%03d", index);
                model.addRow(new Object[]{Number, TheNext});
                index++;
            }
            JPTable.setModel(model);
        }
        AddEmptyRow();

    }

    private void LoadList() {
        //SELECT * FROM ccpd_security_measures.list_cat_desttransint;
        PConfig.setDBName("ccpd_security_measures");
        DBMSAP = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        DEST = DBMSAP.LoadList("nominations","idnominations" );

    }

    private void UpdateDBWithTableData() {
        int ntf = AcceptInformation("¿Está seguro de que quiere actualizar los datos?");
        if (ntf == mconfyes) {
            UpdateDBData();
        }
    }

    void AddEmptyRow() {
        int index = JPTable.getModel().getRowCount() + 1;
        DefaultTableModel model = (DefaultTableModel) JPTable.getModel();
        var Number = String.format("%03d", index);
        model.addRow(new Object[]{Number, ""});
    }

    private void InsertRow() {
        int index = JPTable.getModel().getRowCount() - 1;
        String sidautorizations = (String) JPTable.getModel().getValueAt(index, 0);
        String sidclient = (String) JPTable.getModel().getValueAt(index, 1);
        String sidenterprise = (String) JPTable.getModel().getValueAt(index, 2);
        String sname = (String) JPTable.getModel().getValueAt(index, 3);
        String sposition = (String) JPTable.getModel().getValueAt(index, 4);
        String sresources = (String) JPTable.getModel().getValueAt(index, 5);

        //CL_DBCV CamposPanel=new CL_DBCV();
        CLAllObjectList<CL_DBCV> List_CamposPanel = new CLAllObjectList<>();
        List_CamposPanel.add(new CL_DBCV(sidautorizations, sidautorizations));
        List_CamposPanel.add(new CL_DBCV(sidclient, sidautorizations));
        List_CamposPanel.add(new CL_DBCV(sidenterprise, sidautorizations));
        List_CamposPanel.add(new CL_DBCV(sname, sidautorizations));
        List_CamposPanel.add(new CL_DBCV(sposition, sidautorizations));
        List_CamposPanel.add(new CL_DBCV(sresources, sidautorizations));

        DBMSAP.InsertDatainDB("nominations", List_CamposPanel);
        AddEmptyRow();
    }

    private void DeleteRow() {
        int ntf = AcceptInformation("¿Está seguro de que quiere borrar la fila seleccionada?");
        if (ntf == mconfyes) {
            int index = JPTable.getSelectedRow();
            ((DefaultTableModel) JPTable.getModel()).removeRow(index);
        }
    }

    private void UpdateDBData() {
        int totalindex = JPTable.getModel().getRowCount();
        int index = 0;
        CLAllObjectList<CL_DBCV> List_CamposPanel = new CLAllObjectList<>();
        while (index < totalindex) {
            String sidautorizations = (String) JPTable.getModel().getValueAt(index, 0);
            String ssidclient = (String) JPTable.getModel().getValueAt(index, 1);
            String ssidenterprise = (String) JPTable.getModel().getValueAt(index, 2);
            String ssname = (String) JPTable.getModel().getValueAt(index, 3);
            String ssposition = (String) JPTable.getModel().getValueAt(index, 4);
            String ssresources = (String) JPTable.getModel().getValueAt(index, 5);

            if (!"".equals(ssidclient)) {
                List_CamposPanel.add(new CL_DBCV(ssidclient, sidautorizations));
            }
            if (!"".equals(ssidenterprise)) {
                List_CamposPanel.add(new CL_DBCV(ssidenterprise, sidautorizations));
            }
            if (!"".equals(ssname)) {
                List_CamposPanel.add(new CL_DBCV(ssname, sidautorizations));
            }
            if (!"".equals(ssposition)) {
                List_CamposPanel.add(new CL_DBCV(ssposition, sidautorizations));
            }
            if (!"".equals(ssresources)) {
                List_CamposPanel.add(new CL_DBCV(ssresources, sidautorizations));
            }

            index++;
        }
        DBMSAP.DeleteDataTable("nominations");
        DBMSAP.InsertDatainDB("nominations", List_CamposPanel);
    }
}
