/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ccpd.es.p8panels;


import static beleris.es.finalinformationmanager.MainErrorManager.AcceptInformation;
import static beleris.es.finalinformationmanager.MainErrorManager.mconfyes;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CL_DBCV;
import static ccpd.es.p8config.P8Config.PConfig;
import ccpd.es.p8dbmanager.FDBManExtra;
import java.util.List;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class Ta_TreatActivities extends javax.swing.JPanel {

    private static final long serialVersionUID = 935379364415417335L;

    /**
     * Creates new form Ta_TreatActivities
     */
    public Ta_TreatActivities() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JPTable = new javax.swing.JTable();

        JPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JPTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JPTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    FDBManExtra DBMSAP;
    List<String> DEST;

    private void FillPanel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" idregistro ");
        model.addColumn(" Clente ");
        model.addColumn(" Empresa ");
        model.addColumn(" Administrador del tratamiento ");
        model.addColumn(" Procedimiento de control específico ");
        model.setRowCount(0);
        int index = 1;
        if (!DEST.isEmpty()) {
            ListIterator<String> dli = DEST.listIterator();
            while (dli.hasNext()) {
                String TheNext = " " + dli.next() + " ";
                var Number = String.format("%03d", index);
                model.addRow(new Object[]{Number, TheNext});
                index++;
            }
            JPTable.setModel(model);
        }
        AddEmptyRow();

    }

    private void LoadList() {
        //SELECT * FROM ccpd_lists.list_cat_desttransint;
        PConfig.setDBName("ccpd_treat_activity_register");
        DBMSAP = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        DEST = DBMSAP.LoadList("treatactivity","idtreatactivity" );

    }

    private void UpdateDBWithTableData() {
        int ntf = AcceptInformation("¿Está seguro de que quiere actualizar los datos?");
        if (ntf == mconfyes) {
            UpdateDBData();
        }
    }

    void AddEmptyRow() {
        int index = JPTable.getModel().getRowCount() + 1;
        DefaultTableModel model = (DefaultTableModel) JPTable.getModel();
        var Number = String.format("%03d", index);
        model.addRow(new Object[]{Number, ""});
    }

    private void InsertRow() {
        int index = JPTable.getModel().getRowCount() - 1;
        String idtreatactivity = (String) JPTable.getModel().getValueAt(index, 0);
        String sidclient = (String) JPTable.getModel().getValueAt(index, 1);
        String sidenterprise = (String) JPTable.getModel().getValueAt(index, 2);
        String smanagername = (String) JPTable.getModel().getValueAt(index, 3);
        String smanageremail = (String) JPTable.getModel().getValueAt(index, 4);
        String treatprurposes = (String) JPTable.getModel().getValueAt(index, 5);
        String stakeholdercategories = (String) JPTable.getModel().getValueAt(index, 6);
        String personaldatacategories = (String) JPTable.getModel().getValueAt(index, 7);
        String typeoftreatment = (String) JPTable.getModel().getValueAt(index, 8);
        String recipentscategories = (String) JPTable.getModel().getValueAt(index, 9);
        String countriesenterprisestarget = (String) JPTable.getModel().getValueAt(index, 4);
        String dataprotectiondelegateemail = (String) JPTable.getModel().getValueAt(index, 10);
        String deadlinesdeletingdatacategories = (String) JPTable.getModel().getValueAt(index, 11);
        String securitymeasures = (String) JPTable.getModel().getValueAt(index, 12);
        String responsibleclaims = (String) JPTable.getModel().getValueAt(index, 13);
        String legalbasis = (String) JPTable.getModel().getValueAt(index, 14);

        //CL_DBCV CamposPanel=new CL_DBCV();
        CLAllObjectList<CL_DBCV> List_CamposPanel = new CLAllObjectList<>();
        List_CamposPanel.add(new CL_DBCV(idtreatactivity, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(sidclient, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(sidenterprise, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(smanagername, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(smanageremail, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(treatprurposes, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(stakeholdercategories, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(personaldatacategories, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(typeoftreatment, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(recipentscategories, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(countriesenterprisestarget, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(dataprotectiondelegateemail, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(deadlinesdeletingdatacategories, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(securitymeasures, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(responsibleclaims, idtreatactivity));
        List_CamposPanel.add(new CL_DBCV(legalbasis, idtreatactivity));

        DBMSAP.InsertDatainDB("treatactivity", List_CamposPanel);
        AddEmptyRow();
    }

    private void DeleteRow() {
        int ntf = AcceptInformation("¿Está seguro de que quiere borrar la fila seleccionada?");
        if (ntf == mconfyes) {
            int index = JPTable.getSelectedRow();
            ((DefaultTableModel) JPTable.getModel()).removeRow(index);
        }
    }

    private void UpdateDBData() {
        int totalindex = JPTable.getModel().getRowCount();
        int index = 0;
        CLAllObjectList<CL_DBCV> List_CamposPanel = new CLAllObjectList<>();
        while (index < totalindex) {
            String sidtreatactivity = (String) JPTable.getModel().getValueAt(index, 0);
            String sidclient = (String) JPTable.getModel().getValueAt(index, 1);
            String sidenterprise = (String) JPTable.getModel().getValueAt(index, 2);
            String smanagername = (String) JPTable.getModel().getValueAt(index, 3);
            String smanageremail = (String) JPTable.getModel().getValueAt(index, 4);
            String treatprurposes = (String) JPTable.getModel().getValueAt(index, 5);
            String stakeholdercategories = (String) JPTable.getModel().getValueAt(index, 6);
            String personaldatacategories = (String) JPTable.getModel().getValueAt(index, 7);
            String typeoftreatment = (String) JPTable.getModel().getValueAt(index, 8);
            String recipentscategories = (String) JPTable.getModel().getValueAt(index, 9);
            String countriesenterprisestarget = (String) JPTable.getModel().getValueAt(index, 4);
            String dataprotectiondelegateemail = (String) JPTable.getModel().getValueAt(index, 10);
            String deadlinesdeletingdatacategories = (String) JPTable.getModel().getValueAt(index, 11);
            String securitymeasures = (String) JPTable.getModel().getValueAt(index, 12);
            String responsibleclaims = (String) JPTable.getModel().getValueAt(index, 13);
            String legalbasis = (String) JPTable.getModel().getValueAt(index, 14);

            if (!"".equals(sidclient)) {
                List_CamposPanel.add(new CL_DBCV(sidclient, sidtreatactivity));
            }
            if (!"".equals(sidenterprise)) {
                List_CamposPanel.add(new CL_DBCV(sidenterprise, sidtreatactivity));
            }
            if (!"".equals(smanagername)) {
                List_CamposPanel.add(new CL_DBCV(smanagername, sidtreatactivity));
            }
            if (!"".equals(smanageremail)) {
                List_CamposPanel.add(new CL_DBCV(smanageremail, sidtreatactivity));
            }
            if (!"".equals(treatprurposes)) {
                List_CamposPanel.add(new CL_DBCV(treatprurposes, sidtreatactivity));
            }
            if (!"".equals(stakeholdercategories)) {
                List_CamposPanel.add(new CL_DBCV(stakeholdercategories, sidtreatactivity));
            }
            if (!"".equals(personaldatacategories)) {
                List_CamposPanel.add(new CL_DBCV(personaldatacategories, sidtreatactivity));
            }
            if (!"".equals(typeoftreatment)) {
                List_CamposPanel.add(new CL_DBCV(typeoftreatment, sidtreatactivity));
            }
            if (!"".equals(recipentscategories)) {
                List_CamposPanel.add(new CL_DBCV(recipentscategories, sidtreatactivity));
            }
            if (!"".equals(countriesenterprisestarget)) {
                List_CamposPanel.add(new CL_DBCV(countriesenterprisestarget, sidtreatactivity));
            }
            if (!"".equals(dataprotectiondelegateemail)) {
                List_CamposPanel.add(new CL_DBCV(dataprotectiondelegateemail, sidtreatactivity));
            }
            if (!"".equals(deadlinesdeletingdatacategories)) {
                List_CamposPanel.add(new CL_DBCV(deadlinesdeletingdatacategories, sidtreatactivity));
            }
            if (!"".equals(securitymeasures)) {
                List_CamposPanel.add(new CL_DBCV(securitymeasures, sidtreatactivity));
            }
            if (!"".equals(responsibleclaims)) {
                List_CamposPanel.add(new CL_DBCV(responsibleclaims, sidtreatactivity));
            }
            if (!"".equals(legalbasis)) {
                List_CamposPanel.add(new CL_DBCV(legalbasis, sidtreatactivity));
            }

            index++;
        }
        DBMSAP.DeleteDataTable("treatactivity");
        DBMSAP.InsertDatainDB("treatactivity", List_CamposPanel);
    }
}
