/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccpd.es.p8instalation;



import beleris.es.finalinformationmanager.LoggingManagerGenerator;
import static ccpd.es.p8config.P8Config.PConfig;
import org.openide.LifecycleManager;

/**
 *
 * @author edavid
 */
public class DBAutInstall extends javax.swing.JDialog {

    private static final long serialVersionUID = 1987654323L;

    /**
     * Creates new form DBAuttenInstalation
     */
    public DBAutInstall(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TAdminName.setText(PConfig.getAdminDBName());
        TUserName.setText(PConfig.getAdminDBName());
        TAdminPass.setText(PConfig.getAdminDBPassword());
        TUserPass.setText(PConfig.getAdminDBPassword());
        LoggingManagerGenerator.getGlobalLogger().config("Configurando datos de autenticación del servidor de base de datos.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TAdminName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TAdminPass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TUserPass = new javax.swing.JPasswordField();
        JBOk = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        JBSSR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.title")); // NOI18N
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(750, 500));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.blue, 2, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(781, 396));
        jPanel1.setMinimumSize(new java.awt.Dimension(781, 396));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(781, 396));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.jLabel5.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel5, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.jPanel3.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(350, 250));
        jPanel3.setMinimumSize(new java.awt.Dimension(350, 250));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 250));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.jLabel3.text")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(229, 35));
        jLabel3.setMinimumSize(new java.awt.Dimension(229, 35));
        jLabel3.setPreferredSize(new java.awt.Dimension(229, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel3, gridBagConstraints);

        TAdminName.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        TAdminName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TAdminName.setText(org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.TAdminName.text")); // NOI18N
        TAdminName.setMaximumSize(new java.awt.Dimension(229, 35));
        TAdminName.setMinimumSize(new java.awt.Dimension(229, 35));
        TAdminName.setPreferredSize(new java.awt.Dimension(229, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(TAdminName, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.jLabel4.text")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(229, 35));
        jLabel4.setMinimumSize(new java.awt.Dimension(229, 35));
        jLabel4.setPreferredSize(new java.awt.Dimension(229, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel4, gridBagConstraints);

        TAdminPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TAdminPass.setText(org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.TAdminPass.text")); // NOI18N
        TAdminPass.setMaximumSize(new java.awt.Dimension(229, 35));
        TAdminPass.setMinimumSize(new java.awt.Dimension(229, 35));
        TAdminPass.setPreferredSize(new java.awt.Dimension(229, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(TAdminPass, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.jPanel2.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(350, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 250));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(229, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(229, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(229, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        TUserName.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        TUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TUserName.setText(org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.TUserName.text")); // NOI18N
        TUserName.setMaximumSize(new java.awt.Dimension(229, 35));
        TUserName.setMinimumSize(new java.awt.Dimension(229, 35));
        TUserName.setPreferredSize(new java.awt.Dimension(229, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(TUserName, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.jLabel2.text")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(229, 35));
        jLabel2.setMinimumSize(new java.awt.Dimension(229, 35));
        jLabel2.setPreferredSize(new java.awt.Dimension(229, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        TUserPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TUserPass.setText(org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.TUserPass.text")); // NOI18N
        TUserPass.setMaximumSize(new java.awt.Dimension(229, 35));
        TUserPass.setMinimumSize(new java.awt.Dimension(229, 35));
        TUserPass.setPreferredSize(new java.awt.Dimension(229, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(TUserPass, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        JBOk.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(JBOk, org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.JBOk.text")); // NOI18N
        JBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(JBOk, gridBagConstraints);

        jBCancel.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBCancel, org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.jBCancel.text")); // NOI18N
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jBCancel, gridBagConstraints);

        JBSSR.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(JBSSR, org.openide.util.NbBundle.getMessage(DBAutInstall.class, "DBAutInstall.JBSSR.text")); // NOI18N
        JBSSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSSRActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(JBSSR, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBOkActionPerformed

        String confusernam = "", tfusernam = "", confadminnam = "", tfadminnam = "";
        String confuserpass = "", tfuserpass = "", confadminpass = "", tfadminpass = "";

        confusernam = PConfig.getAdminDBName();
        tfusernam = TUserName.getText();
        confadminnam = PConfig.getAdminDBName();
        tfadminnam = TAdminName.getText();

        confuserpass = PConfig.getAdminDBPassword();
        tfuserpass = new String(TUserPass.getPassword());
        confadminpass = PConfig.getAdminDBPassword();
        tfadminpass = new String(TAdminPass.getPassword());

        setFilled(confusernam.equals(tfusernam) && confadminnam.equals(tfadminnam) && confuserpass.equals(tfuserpass) && confadminpass.equals(tfadminpass));

        if (filled) {
            PConfig.setAdminDBName(TAdminName.getText());
            PConfig.setUserDBName(TUserName.getText());
            PConfig.setAdminDBPassword(new String(TAdminPass.getPassword()));
            PConfig.setUserDBPassword(new String(TUserPass.getPassword()));
            LoggingManagerGenerator.getGlobalLogger().config("Introduciendo datos de autenticación del servidor de base de datos.");
            dispose();
        } else {
            LoggingManagerGenerator.getGlobalLogger().severe("Error introduciendo datos de autenticación del servidor de base de datos.");
        }
    }//GEN-LAST:event_JBOkActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelActionPerformed

    private void JBSSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSSRActionPerformed
        LifecycleManager.getDefault().exit();
    }//GEN-LAST:event_JBSSRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBAutInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBAutInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBAutInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBAutInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DBAutInstall dialog = new DBAutInstall(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBOk;
    private javax.swing.JButton JBSSR;
    private javax.swing.JTextField TAdminName;
    private javax.swing.JPasswordField TAdminPass;
    private javax.swing.JTextField TUserName;
    private javax.swing.JPasswordField TUserPass;
    private javax.swing.JButton jBCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    private boolean filled = false;

    /**
     * @return the filled
     */
    public boolean isFilled() {
        return filled;
    }

    /**
     * @param filled the filled to set
     */
    public void setFilled(boolean filled) {
        this.filled = filled;
    }
}
