/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccpd.es.p8instalation;

import static ccpd.es.p8config.P8Config.PConfig;
import ccpd.es.p8dbmanager.FDBManExtra;
import org.openide.LifecycleManager;

/**
 *
 * @author edavid
 */
public class UserAutoInstall extends javax.swing.JDialog {

    private static final long serialVersionUID = 1356789L;

    private FDBManExtra DBManager;

    /**
     * Creates new form DBAuttenInstalation
     */
    public UserAutoInstall(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFClientName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JPClientPass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jBOk = new javax.swing.JButton();
        JBCancel = new javax.swing.JButton();
        JBSSR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "DBAutenInstalationParteUno.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(522, 524));
        jPanel1.setMinimumSize(new java.awt.Dimension(522, 524));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(522, 524));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel3, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.jPanel2.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(350, 400));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jTFClientName.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jTFClientName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFClientName.setText(org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.jTFClientName.text")); // NOI18N
        jTFClientName.setMaximumSize(new java.awt.Dimension(229, 33));
        jTFClientName.setMinimumSize(new java.awt.Dimension(229, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jTFClientName, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        JPClientPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JPClientPass.setText(org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.JPClientPass.text")); // NOI18N
        JPClientPass.setMaximumSize(new java.awt.Dimension(229, 33));
        JPClientPass.setMinimumSize(new java.awt.Dimension(229, 33));
        JPClientPass.setPreferredSize(new java.awt.Dimension(229, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(JPClientPass, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jBOk.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jBOk, org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.jBOk.text")); // NOI18N
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jBOk, gridBagConstraints);

        JBCancel.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(JBCancel, org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.JBCancel.text")); // NOI18N
        JBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(JBCancel, gridBagConstraints);

        JBSSR.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(JBSSR, org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.JBSSR.text")); // NOI18N
        JBSSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSSRActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(JBSSR, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(UserAutoInstall.class, "UserAutoInstall.jPanel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed

        String client = "cliente";
        String pass = "password";
        char[] cpas = JPClientPass.getPassword();
        String lpass = new String(cpas);
        boolean faseone = false, fasetwo = false;
        faseone = !client.equals(jTFClientName.getText());
        fasetwo = !pass.equals(lpass);
        if (faseone && fasetwo) {
            InsertClientDatainDB();
            setFilled(true);
        } else {
            setFilled(false);
        }
        dispose();
    }//GEN-LAST:event_jBOkActionPerformed

    private void JBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelActionPerformed
        setFilled(false);
        dispose();
    }//GEN-LAST:event_JBCancelActionPerformed

    private void JBSSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSSRActionPerformed
        LifecycleManager.getDefault().exit();
    }//GEN-LAST:event_JBSSRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAutoInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAutoInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAutoInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAutoInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserAutoInstall dialog = new UserAutoInstall(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancel;
    private javax.swing.JButton JBSSR;
    private javax.swing.JPasswordField JPClientPass;
    private javax.swing.JButton jBOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFClientName;
    // End of variables declaration//GEN-END:variables

    private boolean filled = false;

    void Autenticar_CreateTable_InsertClient() {

        String rootUser = PConfig.getAdminDBName();
        String rootPass = PConfig.getAdminDBPassword();
        DBManager = new FDBManExtra(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBManExtra.DB_MYSQL_Selected);
        String DBTableCreateStat = "USE `n_autenticar`;";
        DBTableCreateStat += "SET FOREIGN_KEY_CHECKS=0";
        DBTableCreateStat += "DROP TABLE IF EXISTS `autenticar`;\n";
        DBTableCreateStat += "CREATE TABLE `autenticar` (\n"
                + "  `idcliente` int(11) NOT NULL AUTO_INCREMENT,\n"
                + "  `ncliente` varchar(45) NOT NULL,\n"
                + "  `nclave` varchar(45) NOT NULL,\n"
                + "  `prioridad` varchar(2) NOT NULL,\n"
                + "  PRIMARY KEY (`idcliente`)\n"
                + ") ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;";
        DBTableCreateStat += "LOCK TABLES `autenticar` WRITE;";
        DBTableCreateStat += "INSERT INTO `autenticar` VALUES (1,'" + jTFClientName.getText() + "','" + new String(JPClientPass.getPassword()) + "',0);";
        DBTableCreateStat += "UNLOCK TABLES;";
        DBTableCreateStat += "SET FOREIGN_KEY_CHECKS=1";
        DBManager.ExecuteQueryTableDBWithOptions(DBTableCreateStat);

        if (!DBManager.isbError()) {
            setFilled(true);
        } else {
            setFilled(false);
        }
    }

    private void InsertClientDatainDB() {
        Autenticar_CreateTable_InsertClient();
    }

    /**
     * @return the filled
     */
    public boolean isFilled() {
        return filled;
    }

    /**
     * @param filled the filled to set
     */
    public void setFilled(boolean filled) {
        this.filled = filled;
    }
}
