/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ccpd.es.p8dialogs;

import beleris.es.finaldbmanager.FDBMan;
import static beleris.es.finalinformationmanager.MainErrorManager.ShowDError;
import static beleris.es.finalinformationmanager.MainErrorManager.ShowDInfo;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CL_Client;
import beleris.es.finalutils.NewHelpPresenter;
import static ccpd.es.p8config.P8Config.PConfig;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import org.openide.windows.WindowManager;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class AuthenticationDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = -9070930488677511463L;

    /**
     * Creates new form AuthenticationDialog
     */
    private boolean UserAuthenticated = false;
    private CL_Client ActualUser = new CL_Client();
    private FDBMan Users_List_DB;
    CLAllObjectList<String> UsersListfinal = new CLAllObjectList<>();
    private boolean cancelaction = false;
    // HelpUtils HU = new HelpUtils();

    public AuthenticationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Autenticación de usuario", "autenticacion", "autenticacion.html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPOuterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPInnerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JBCancel = new javax.swing.JButton();
        jBOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" Diálogo de autenticación ");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HelpF1(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPOuterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPOuterPanel.setMaximumSize(new java.awt.Dimension(400, 300));
        jPOuterPanel.setMinimumSize(new java.awt.Dimension(400, 300));
        jPOuterPanel.setPreferredSize(new java.awt.Dimension(400, 300));
        jPOuterPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel1.setText(" Autenticación ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOuterPanel.add(jLabel1, gridBagConstraints);

        jPInnerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPInnerPanel.setMaximumSize(new java.awt.Dimension(300, 200));
        jPInnerPanel.setMinimumSize(new java.awt.Dimension(300, 200));
        jPInnerPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        jPInnerPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 35));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPInnerPanel.add(jLabel2, gridBagConstraints);

        jPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPassword.setText("jPasswordField1");
        jPassword.setMaximumSize(new java.awt.Dimension(200, 35));
        jPassword.setMinimumSize(new java.awt.Dimension(200, 35));
        jPassword.setPreferredSize(new java.awt.Dimension(200, 35));
        jPassword.setSelectionEnd(0);
        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passkeyf1(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPInnerPanel.add(jPassword, gridBagConstraints);

        jUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUserName.setText(" nombre ");
        jUserName.setMaximumSize(new java.awt.Dimension(200, 35));
        jUserName.setMinimumSize(new java.awt.Dimension(200, 35));
        jUserName.setPreferredSize(new java.awt.Dimension(200, 35));
        jUserName.setSelectionEnd(0);
        jUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyF1Hand(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPInnerPanel.add(jUserName, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 35));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPInnerPanel.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOuterPanel.add(jPInnerPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPOuterPanel, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        JBCancel.setText("Cancelar");
        JBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelActionPerformed(evt);
            }
        });
        jPanel1.add(JBCancel);

        jBOK.setText("Aceptar");
        jBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOKActionPerformed(evt);
            }
        });
        jPanel1.add(jBOK);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelActionPerformed
        setCancelaction(true);
        PConfig.RestoreHelpconfig();
        dispose();
    }//GEN-LAST:event_JBCancelActionPerformed

    private void jBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOKActionPerformed
        setUserAuthenticated(CheckAuthentication());
        if (isUserAuthenticated()) {
            ShowDInfo("Usuario autenticado");
            PConfig.RestoreHelpconfig();
            dispose();

        } else {
            ShowDError("Usuario o clave incorrectas, inténtelo de nuevo");
            PConfig.RestoreHelpconfig();
            dispose();

        }
    }//GEN-LAST:event_jBOKActionPerformed
 
    private void HelpF1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HelpF1
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            Frame f = WindowManager.getDefault().getMainWindow();
                       //FHelpPresenter DHelp = new FHelpPresenter("Registro de control de Seguridad", "help/NewGeneralDataIntroPanels-PSRC.html");
            NewHelpPresenter DHelp = new NewHelpPresenter(f, true, "Ayuda del " + PConfig.getHelpTitleModule(), PConfig.getApplicationPath() + "/help/" + PConfig.getHelpModule() + "/" + PConfig.getHelpFileModule());
            DHelp.setLocationRelativeTo(f);
            DHelp.setVisible(true);
        }
    }//GEN-LAST:event_HelpF1

    private void KeyF1Hand(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyF1Hand
        // TODO add your handling code here:
        HelpF1(evt);
    }//GEN-LAST:event_KeyF1Hand

    private void passkeyf1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passkeyf1
        // TODO add your handling code here:
        HelpF1(evt);
    }//GEN-LAST:event_passkeyf1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AuthenticationDialog dialog = new AuthenticationDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancel;
    private javax.swing.JButton jBOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPInnerPanel;
    private javax.swing.JPanel jPOuterPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUserName;
    // End of variables declaration//GEN-END:variables

    private boolean CheckAuthentication() {
        boolean result = false;
        PConfig.setDBName("ccpd_autenticate");
        Users_List_DB = new FDBMan(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBMan.DB_MYSQL_Selected);
        UsersListfinal = Users_List_DB.LoadList("autenticate_table", "clientname");
        CLAllObjectList<String> PasswordLists = Users_List_DB.LoadList("autenticate_table", "clientpassword");
        if (UsersListfinal.isEmpty() || PasswordLists.isEmpty()) {
            result = false;
        } else {

            for (int idx = 0; idx < UsersListfinal.size(); idx++) {
                String Name = UsersListfinal.get(idx);
                String password = PasswordLists.get(idx);
                String EnteredName = jUserName.getText();
                String EnteredPaswword = new String(jPassword.getPassword());
                if (EnteredName.equals(Name) && EnteredPaswword.equals(password)) {
                    ActualUser = new CL_Client(Name, Integer.toString(UsersListfinal.indexOf(idx + 1)));
                    result = true;
                    break;
                }
            }

        }
        return result;
    }

    /**
     * @return the UserAuthenticated
     */
    public boolean isUserAuthenticated() {
        return UserAuthenticated;
    }

    /**
     * @param UserAuthenticated the UserAuthenticated to set
     */
    public void setUserAuthenticated(boolean UserAuthenticated) {
        this.UserAuthenticated = UserAuthenticated;
    }

    /**
     * @return the ActualUser
     */
    public CL_Client getActualUser() {
        return ActualUser;
    }

    /**
     * @param ActualUser the ActualUser to set
     */
    public void setActualUser(CL_Client ActualUser) {
        this.ActualUser = ActualUser;
    }

    /**
     * @return the cancelaction
     */
    public boolean isCancelaction() {
        return cancelaction;
    }

    /**
     * @param cancelaction the cancelaction to set
     */
    public void setCancelaction(boolean cancelaction) {
        this.cancelaction = cancelaction;
    }
}
