/*
 @author Emilio David Diaus López 2008-2021
 * *
 * *
 */
package ccpd.es.p8dialogs;

import beleris.es.finaldbmanager.FDBMan;
import beleris.es.finalinformationmanager.MainErrorManager;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CL_Client;
import beleris.es.finalprimaryclasses.CL_Enterprise;
import beleris.es.finalutils.NewHelpPresenter;
import static ccpd.es.p8config.P8Config.PConfig;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.util.ListIterator;
import javax.swing.table.DefaultTableModel;
import org.openide.windows.WindowManager;

/**
 *
 * @author edavid
 */
public class DListSelection extends javax.swing.JDialog /*implements HelpCtx.Provider */ {

    private static int iEntityDialogSelection = 1;
    private static int iFileDialogSelection = 2;
    private static int iClientDialogSelection = 3;
    private static final long serialVersionUID = 964623304574957946L;

    private int operation = 1;

    CLAllObjectList<String> EnterprisesListfinal = new CLAllObjectList<>();
    CLAllObjectList<String> ClientsListfinal = new CLAllObjectList<>();
    private FDBMan Enterprises_List_DB;
    private FDBMan Clients_List_DB;

    /**
     * Creates new form DListSelection
     */
    public DListSelection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // PConfig.setHelpConfig(getTitle(), "NewAuxiliarDialogs", "NewAuxiliarDialogs-about.html");
    }

    public DListSelection(java.awt.Frame parent, boolean modal, int tmpoperation) {
        super(parent, modal);
        initComponents();
        PConfig.setDBName("ccpd_enterprises");
        Enterprises_List_DB = new FDBMan(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBMan.DB_MYSQL_Selected);
        PConfig.setDBName("ccpd_clients");
        Clients_List_DB = new FDBMan(PConfig.getSQLURL(), PConfig.getAdminDBPassword(), PConfig.getDBName(), PConfig.getAdminDBName(), FDBMan.DB_MYSQL_Selected);

        operation = tmpoperation;
        if (operation == iEntityDialogSelection) {
            PConfig.BackupHelpconfig();
            PConfig.setHelpConfig("Seleccionar una empresa", "seleccion", "selempresas.html");
            ConfiguringEntitiesList();
        }
        if (operation == iClientDialogSelection) {
            PConfig.BackupHelpconfig();
            PConfig.setHelpConfig("Seleccionar un cliente", "seleccion", "selclientes.html");
            ConfiguringClientsList();
        }

        //    PConfig.setHelpConfig(getTitle(), "NewAuxiliarDialogs", "NewAuxiliarDialogs-about.html");
    }

    /*
    @Override
    public HelpCtx getHelpCtx() {
        return new HelpCtx("ccpd.es.auxdial.about");
    }
     */
    public void ConfiguringEntitiesList() {
        if (operation == getiEntityDialogSelection()) {

            LoadingEntitiesList();
            jFalsoTitulo.setText("Seleccione una Empresa");

        }

    }

    public void ConfiguringClientsList() {

        if (operation == getiClientDialogSelection()) {

            LoadingClientsList();
            jFalsoTitulo.setText("Seleccione un Cliente");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jElementsTable = new javax.swing.JTable();
        jFalsoTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(DListSelection.class, "DListSelection.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 600));
        setModal(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HelpF1Press(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HelpF1Reles(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), org.openide.util.NbBundle.getMessage(DListSelection.class, "DListSelection.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setToolTipText(org.openide.util.NbBundle.getMessage(DListSelection.class, "DListSelection.jPanel1.toolTipText")); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(475, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(475, 500));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(475, 500));

        jElementsTable.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jElementsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "  Tipo ", "  Indice", "  Nombre "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jElementsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jElementsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jElementsTable.setMaximumSize(new java.awt.Dimension(400, 400));
        jElementsTable.setMinimumSize(new java.awt.Dimension(400, 400));
        jElementsTable.setPreferredSize(new java.awt.Dimension(400, 400));
        jElementsTable.setShowGrid(true);
        jElementsTable.setShowHorizontalLines(true);
        jElementsTable.setShowVerticalLines(true);
        jElementsTable.getTableHeader().setReorderingAllowed(false);
        jElementsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jElementsTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jElementsTableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jElementsTable);

        jFalsoTitulo.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jFalsoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jFalsoTitulo, org.openide.util.NbBundle.getMessage(DListSelection.class, "DListSelection.jFalsoTitulo.text")); // NOI18N
        jFalsoTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(jFalsoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFalsoTitulo)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(DListSelection.class, "DListSelection.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(DListSelection.class, "DListSelection.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jElementsTable.getSelectedRow() != -1) {
            if (getOperation() == getiEntityDialogSelection()) {

                if (!PConfig.isEntityActivated()) {
                    PConfig.setEnterpriseActivated(false);
                }
            }
            if (getOperation() == getiEntityDialogSelection()) {
                if (!PConfig.isClientActivated()) {

                    PConfig.setClientActivated(false);
                }
            }
        } else {
            MainErrorManager.ShowDInfo(" Debe seleccionar un cliente, una empresa o fichero de la lista ...");
        }
        PConfig.RestoreHelpconfig();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jElementsTable.getSelectedRow() != -1) {
            PConfig.RestoreHelpconfig();
            if (getOperation() == getiEntityDialogSelection()) {
                if (!EnterprisesListfinal.isEmpty()) {
                    int irow = jElementsTable.getSelectedRow();
                    if (irow < EnterprisesListfinal.size()) {
                        PConfig.setActualEnterprise(new CL_Enterprise(EnterprisesListfinal.get(irow), String.valueOf(irow + 1)));
                        PConfig.setEnterpriseActivated(true);
                        PConfig.RestoreHelpconfig();
                    }

                }
            }
            if (getOperation() == getiClientDialogSelection()) {
                if (!ClientsListfinal.isEmpty()) {
                    int irow = jElementsTable.getSelectedRow();
                    if (irow < ClientsListfinal.size()) {
                        PConfig.setActualClient(new CL_Client(ClientsListfinal.get(irow), String.valueOf(irow + 1)));
                        PConfig.setClientActivated(true);
                        PConfig.RestoreHelpconfig();
                    }

                }
            }
            /* if (getOperation() == iFileDialogSelection) {
                if (!FilesListfinal.isEmpty()) {
                    int irow = jElementsTable.getSelectedRow();
                    if (irow < FilesListfinal.size()) {
                           FiElfichero Ent = FilesListfinal.get(irow);
                           PConfig.setActualFile(new CL_File(Ent.getFileName(), Integer.toString(Ent.getIdFile())));
                        PConfig.setFileActivated(true);
                    }
                }
            }*/

        } else {
            MainErrorManager.ShowDInfo(" Debe seleccionar un cliente, una empresa o cliente de la lista ...");
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HelpF1Press(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HelpF1Press
        // TODO add your handling code here:
        HelpF1(evt);
    }//GEN-LAST:event_HelpF1Press

    private void HelpF1Reles(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HelpF1Reles
        // TODO add your handling code here:
        HelpF1(evt);
    }//GEN-LAST:event_HelpF1Reles

    private void jElementsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jElementsTableKeyPressed
        // TODO add your handling code here:
        HelpF1(evt);
    }//GEN-LAST:event_jElementsTableKeyPressed

    private void jElementsTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jElementsTableKeyReleased
        // TODO add your handling code here:
        HelpF1(evt);
    }//GEN-LAST:event_jElementsTableKeyReleased

    private void HelpF1(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            Frame f = WindowManager.getDefault().getMainWindow();
            //FHelpPresenter DHelp = new FHelpPresenter("Registro de control de Seguridad", "help/NewGeneralDataIntroPanels-PSRC.html");
            NewHelpPresenter DHelp = new NewHelpPresenter(f, true, "Ayuda del " + PConfig.getHelpTitleModule(), PConfig.getApplicationPath() + "/help/" + PConfig.getHelpModule() + "/" + PConfig.getHelpFileModule());
            DHelp.setLocationRelativeTo(f);
            DHelp.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DListSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DListSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DListSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DListSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DListSelection dialog = new DListSelection(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jElementsTable;
    private javax.swing.JLabel jFalsoTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    /*
    List<FusionEmEmpresaYFe01Resfichero> SelectTheClientEntityEntityItemsOnly(List<FusionEmEmpresaYFe01Resfichero> ls, int iclient) {
        List<FusionEmEmpresaYFe01Resfichero> result = ls;
        ListIterator<FusionEmEmpresaYFe01Resfichero> lis = result.listIterator();
        while (lis.hasNext()) {
            FusionEmEmpresaYFe01Resfichero lisi = lis.next();
            if (lisi.getIdcliente() != iclient) {
                lis.remove();
            }
        }
        return result;
    }
     */
    /**
     * @return the operation
     */
    public int getOperation() {
        return operation;
    }

    /**
     * @param operation the operation to set
     */
    public void setOperation(int operation) {
        this.operation = operation;
    }

    private void LoadingEntitiesList() {
        EnterprisesListfinal = Enterprises_List_DB.LoadList("generaldata_treatmentmanager", "enterprise_manager_name");
        FillList(EnterprisesListfinal, "ID", "Nombre de la Empresa");
    }

    private void LoadingClientsList() {
        ClientsListfinal = Clients_List_DB.LoadList("dbclients", "client_name");
        FillList(ClientsListfinal, "ID", "Nombre del Cliente");

    }

    /**
     * @return the iEntityDialogSelection
     */
    public static int getiEntityDialogSelection() {
        return iEntityDialogSelection;
    }

    /**
     * @param aiEntityDialogSelection the iEntityDialogSelection to set
     */
    public static void setiEntityDialogSelection(int aiEntityDialogSelection) {
        iEntityDialogSelection = aiEntityDialogSelection;
    }

    /**
     * @return the iClientDialogSelection
     */
    public static int getiClientDialogSelection() {
        return iClientDialogSelection;
    }

    /**
     * @param aiClientDialogSelection the iClientDialogSelection to set
     */
    public static void setiClientDialogSelection(int aiClientDialogSelection) {
        iClientDialogSelection = aiClientDialogSelection;
    }

    void FillList(CLAllObjectList<String> destlist, String sID, String sName) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(sID);
        model.addColumn(sName);
        model.setRowCount(0);
        int index = 1;
        if (!destlist.isEmpty()) {
            ListIterator<String> dli = destlist.listIterator();
            while (dli.hasNext()) {
                String TheNext = " " + dli.next() + " ";
                var Number = String.format("%03d", index);
                model.addRow(new Object[]{Number, TheNext});
                index++;
            }
            jElementsTable.setModel(model);
        }
    }
}
