/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccpd.es.p8dialogs;

import beleris.es.finalinformationmanager.LoggingManagerGenerator;
import beleris.es.finalinformationmanager.MainErrorManager;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLFrameHyperlinkEvent;
import org.openide.util.Exceptions;

/**
 *
 * @author Emilio David Diaus López 2008-2021
 */
public class ShowHelpDialog extends javax.swing.JDialog {

    public static int mconfyes = 1, confno = 2, confcancel = 3;
    static String sYES = " Aceptar ", sNO = " No ", sCANCEL = " Cancelar ";
    private static final long serialVersionUID = -6443813576996197272L;

    /**
     * Creates new form NewHelpPresenter_2
     */
    public ShowHelpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public ShowHelpDialog(java.awt.Frame parent, boolean modal, String tmpTitle, String tmpHelpPageURL) {
        super(parent, modal);
        initComponents();
        JEditorPane InnerHelpPanel = null;
        setTitle(tmpTitle);
        File f = new File(tmpHelpPageURL);
        URL url = null;
        try {
            url = f.toURI().toURL();
        } catch (MalformedURLException ex) {
            LoggingManagerGenerator.getGlobalLogger().log(Level.SEVERE, null, ex);
            MainErrorManager.ShowDWarning("No puedo activar la ayuda, no encuentro el archivo.");
        }
        try {
            InnerHelpPanel = new JEditorPane(url);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        //InnerHelpPanel.setLayout(null);
        //myPanel.setSize(1000, 1000);
        if (InnerHelpPanel != null) {
            InnerHelpPanel.setEditable(false);
            InnerHelpPanel.addHyperlinkListener(new ActivateHTMLLink());
            JScrollPane scrollPanel = new JScrollPane(InnerHelpPanel);
            //scroll.setSize(1000, 1000);
            JTheInnerPanel.add(scrollPanel);
        }
    }

    class ActivateHTMLLink implements HyperlinkListener {

        public void hyperlinkUpdate(HyperlinkEvent e) {
            if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                JEditorPane pane = (JEditorPane) e.getSource();
                if (e instanceof HTMLFrameHyperlinkEvent) {
                    HTMLFrameHyperlinkEvent evt = (HTMLFrameHyperlinkEvent) e;
                    HTMLDocument doc = (HTMLDocument) pane.getDocument();
                    doc.processHTMLFrameHyperlinkEvent(evt);
                } else {

                    //pane.setPage(e.getURL());
                    OpenHTMLDocument(e.getURL().toString());
                }
            }
        }
    }

    void OpenHTMLDocument(String HTMLPage) {
        String[] commandwindows = {"cmd /c " + HTMLPage};
        String[] commandlinux = {"firefox " + HTMLPage};
        Runtime rt;
        String OSName = System.getProperty("os.name");
        rt = Runtime.getRuntime();

        if ("windows".equals(OSName)) {
            try {
                rt.exec(commandwindows);

            } catch (IOException ex) {
                LoggingManagerGenerator.getGlobalLogger().log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                rt.exec(commandlinux);

            } catch (IOException ex) {
                LoggingManagerGenerator.getGlobalLogger().log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JTheInnerPanel = new javax.swing.JPanel();
        jBExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(ShowHelpDialog.class, "ShowHelpDialog.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(1500, 885));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        JTheInnerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JTheInnerPanel.setAutoscrolls(true);
        JTheInnerPanel.setMaximumSize(new java.awt.Dimension(1450, 800));
        JTheInnerPanel.setMinimumSize(new java.awt.Dimension(1450, 800));
        JTheInnerPanel.setName(""); // NOI18N
        JTheInnerPanel.setPreferredSize(new java.awt.Dimension(1450, 800));
        JTheInnerPanel.setLayout(new javax.swing.BoxLayout(JTheInnerPanel, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(JTheInnerPanel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBExitButton, org.openide.util.NbBundle.getMessage(ShowHelpDialog.class, "ShowHelpDialog.jBExitButton.text")); // NOI18N
        jBExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jBExitButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_jBExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
 /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowHelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowHelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowHelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowHelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ShowHelpDialog dialog = new ShowHelpDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JTheInnerPanel;
    private javax.swing.JButton jBExitButton;
    // End of variables declaration//GEN-END:variables
}
