/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package ccpd.es.p8windows;

import ccpd.es.p8panels.JPSecurity_Measures;
import beleris.es.finalinformationmanager.LoggingManagerGenerator;
import static beleris.es.finalinformationmanager.MainErrorManager.AcceptInformation;
import static beleris.es.finalinformationmanager.MainErrorManager.ShowDError;
import static beleris.es.finalinformationmanager.MainErrorManager.mconfyes;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import beleris.es.finalprimaryclasses.CL_Client;
import static ccpd.es.p8config.P8Config.PConfig;
import ccpd.es.p8dialogs.AuthenticationDialog;
import ccpd.es.p8dialogs.DListSelection;
import ccpd.es.p8panels.JPCreateOtherDocuments;
import ccpd.es.p8panels.JPCustomization;
import ccpd.es.p8panels.PCreatingReportDocument;
import ccpd.es.p8panels.PFillingReportQuestions;
import ccpd.es.p8panels.Panel_TableDBManager;
import ccpd.es.p8pdfmanager.P8PdfManager;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Frame;
import static java.awt.Frame.MAXIMIZED_BOTH;
import org.netbeans.api.settings.ConvertAsProperties;
import static org.openide.LifecycleManager.getDefault;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.Toolbar;
import org.openide.awt.ToolbarPool;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//ccpd.es.p8windows//PrincipalWindow//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "PrincipalWindowTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "ccpd.es.p8windows.PrincipalWindowTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PrincipalWindowAction",
        preferredID = "PrincipalWindowTopComponent"
)
@Messages({
    "CTL_PrincipalWindowAction=Ventana principal",
    "CTL_PrincipalWindowTopComponent=Ventana principal",
    "HINT_PrincipalWindowTopComponent=Esta es la ventana principal"
})
public final class PrincipalWindowTopComponent extends TopComponent {

    private static final long serialVersionUID = -2367734091231885605L;

    // private CLAllObjectList<String> ClientList;
    // private CLAllObjectList<String> EnterpriseList;
    public PrincipalWindowTopComponent() {
        initComponents();
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Escritorio de la aplicación", "escritorio", "escritorio.html");
        System.setProperty("program.name", "CCPD8");
        LoggingManagerGenerator LMG = new LoggingManagerGenerator();
        setName(Bundle.CTL_PrincipalWindowTopComponent());
        setToolTipText(Bundle.HINT_PrincipalWindowTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        WindowManager.getDefault().getMainWindow().setExtendedState(MAXIMIZED_BOTH);
        WindowManager.getDefault().getMainWindow().setTitle("CCPD8 (c) Emilio David Diaus López 2025-26");
        Toolbar toolbar = ToolbarPool.getDefault().findToolbar("UndoRedo");
        if (toolbar != null) {
            toolbar.getParent().setEnabled(false);
            toolbar.getParent().setVisible(false);
            toolbar.setVisible(false);
        }
        toolbar = ToolbarPool.getDefault().findToolbar("Memory");
        if (toolbar != null) {           
            toolbar.getParent().setEnabled(false);
            toolbar.getParent().setVisible(false);
            toolbar.setVisible(false);
        }
        UpdateInfoPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPOperationsMenu = new javax.swing.JPanel();
        jBClientOperations = new javax.swing.JButton();
        jBEnterpriseOperations = new javax.swing.JButton();
        jBTratActivities = new javax.swing.JButton();
        jBTratRisks = new javax.swing.JButton();
        jBSecurityMeasures = new javax.swing.JButton();
        jBImpactEvaluation = new javax.swing.JButton();
        jBTratActivitiesRegister = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        JBFillCompliantReport = new javax.swing.JButton();
        JPerson = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAInfoTextPanel = new javax.swing.JTextArea();
        jPBPBar = new javax.swing.JProgressBar();
        JBSelectEnterprise = new javax.swing.JButton();
        jNSelectClient = new javax.swing.JButton();
        JBViewComplaintReport = new javax.swing.JButton();
        jCreateandPrintDocs = new javax.swing.JButton();
        jBTratActivitiesRegister1 = new javax.swing.JButton();
        jPOperationsPanel = new javax.swing.JPanel();

        setBackground(java.awt.Color.lightGray);
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setForeground(java.awt.Color.darkGray);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(360);

        jPOperationsMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Operaciones", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPOperationsMenu.setMaximumSize(new java.awt.Dimension(360, 980));
        jPOperationsMenu.setMinimumSize(new java.awt.Dimension(360, 980));
        jPOperationsMenu.setName("Ventana Principal"); // NOI18N
        jPOperationsMenu.setPreferredSize(new java.awt.Dimension(360, 980));
        jPOperationsMenu.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jBClientOperations, "Operaciones con los Clientes");
        jBClientOperations.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBClientOperations.setMaximumSize(new java.awt.Dimension(340, 25));
        jBClientOperations.setMinimumSize(new java.awt.Dimension(340, 25));
        jBClientOperations.setPreferredSize(new java.awt.Dimension(340, 25));
        jBClientOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClientOperationsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jBClientOperations, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBEnterpriseOperations, "Operaciones con las Empresas");
        jBEnterpriseOperations.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBEnterpriseOperations.setMaximumSize(new java.awt.Dimension(340, 25));
        jBEnterpriseOperations.setMinimumSize(new java.awt.Dimension(340, 25));
        jBEnterpriseOperations.setPreferredSize(new java.awt.Dimension(340, 25));
        jBEnterpriseOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnterpriseOperationsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jBEnterpriseOperations, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBTratActivities, "Actividades de tratamiento ");
        jBTratActivities.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBTratActivities.setMaximumSize(new java.awt.Dimension(340, 25));
        jBTratActivities.setMinimumSize(new java.awt.Dimension(340, 25));
        jBTratActivities.setPreferredSize(new java.awt.Dimension(340, 25));
        jBTratActivities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTratActivitiesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jBTratActivities, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBTratRisks, "Riesgos del tratamiento");
        jBTratRisks.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBTratRisks.setMaximumSize(new java.awt.Dimension(340, 25));
        jBTratRisks.setMinimumSize(new java.awt.Dimension(340, 25));
        jBTratRisks.setPreferredSize(new java.awt.Dimension(340, 25));
        jBTratRisks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTratRisksActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jBTratRisks, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBSecurityMeasures, "Medidas de seguridad");
        jBSecurityMeasures.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBSecurityMeasures.setMaximumSize(new java.awt.Dimension(340, 25));
        jBSecurityMeasures.setMinimumSize(new java.awt.Dimension(340, 25));
        jBSecurityMeasures.setPreferredSize(new java.awt.Dimension(340, 25));
        jBSecurityMeasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSecurityMeasuresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jBSecurityMeasures, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBImpactEvaluation, "Evaluaciones de impacto");
        jBImpactEvaluation.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBImpactEvaluation.setMaximumSize(new java.awt.Dimension(340, 25));
        jBImpactEvaluation.setMinimumSize(new java.awt.Dimension(340, 25));
        jBImpactEvaluation.setPreferredSize(new java.awt.Dimension(340, 25));
        jBImpactEvaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImpactEvaluationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jBImpactEvaluation, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBTratActivitiesRegister, "Crear registro de actividades de tratamiento");
        jBTratActivitiesRegister.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBTratActivitiesRegister.setMaximumSize(new java.awt.Dimension(340, 25));
        jBTratActivitiesRegister.setMinimumSize(new java.awt.Dimension(340, 25));
        jBTratActivitiesRegister.setPreferredSize(new java.awt.Dimension(340, 25));
        jBTratActivitiesRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTratActivitiesRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPOperationsMenu.add(jBTratActivitiesRegister, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBExit, " Salir ");
        jBExit.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBExit.setMaximumSize(new java.awt.Dimension(340, 25));
        jBExit.setMinimumSize(new java.awt.Dimension(340, 25));
        jBExit.setPreferredSize(new java.awt.Dimension(340, 25));
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jBExit, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBFillCompliantReport, "Rellenar Informe de cumplimiento");
        JBFillCompliantReport.setMargin(new java.awt.Insets(5, 5, 5, 5));
        JBFillCompliantReport.setMaximumSize(new java.awt.Dimension(340, 25));
        JBFillCompliantReport.setMinimumSize(new java.awt.Dimension(340, 25));
        JBFillCompliantReport.setPreferredSize(new java.awt.Dimension(340, 25));
        JBFillCompliantReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFillCompliantReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(JBFillCompliantReport, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JPerson, "Personalización");
        JPerson.setMargin(new java.awt.Insets(5, 5, 5, 5));
        JPerson.setMaximumSize(new java.awt.Dimension(340, 25));
        JPerson.setMinimumSize(new java.awt.Dimension(340, 25));
        JPerson.setPreferredSize(new java.awt.Dimension(340, 25));
        JPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPersonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(JPerson, gridBagConstraints);

        jTAInfoTextPanel.setEditable(false);
        jTAInfoTextPanel.setColumns(20);
        jTAInfoTextPanel.setRows(5);
        jTAInfoTextPanel.setWrapStyleWord(true);
        jTAInfoTextPanel.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTAInfoTextPanel.setMaximumSize(new java.awt.Dimension(340, 60));
        jTAInfoTextPanel.setMinimumSize(new java.awt.Dimension(340, 60));
        jTAInfoTextPanel.setPreferredSize(new java.awt.Dimension(340, 60));
        jScrollPane1.setViewportView(jTAInfoTextPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jScrollPane1, gridBagConstraints);

        jPBPBar.setMaximumSize(new java.awt.Dimension(340, 25));
        jPBPBar.setMinimumSize(new java.awt.Dimension(340, 25));
        jPBPBar.setPreferredSize(new java.awt.Dimension(340, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jPBPBar, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBSelectEnterprise, " Seleccionar Empresa actual");
        JBSelectEnterprise.setMargin(new java.awt.Insets(5, 5, 5, 5));
        JBSelectEnterprise.setMaximumSize(new java.awt.Dimension(340, 25));
        JBSelectEnterprise.setMinimumSize(new java.awt.Dimension(340, 25));
        JBSelectEnterprise.setPreferredSize(new java.awt.Dimension(340, 25));
        JBSelectEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSelectEnterpriseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(JBSelectEnterprise, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jNSelectClient, "Seleccionar Cliente actual");
        jNSelectClient.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jNSelectClient.setMaximumSize(new java.awt.Dimension(340, 25));
        jNSelectClient.setMinimumSize(new java.awt.Dimension(340, 25));
        jNSelectClient.setPreferredSize(new java.awt.Dimension(340, 25));
        jNSelectClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNSelectClientActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jNSelectClient, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBViewComplaintReport, " Visualizar Informe de Cumplimiento ");
        JBViewComplaintReport.setMargin(new java.awt.Insets(5, 5, 5, 5));
        JBViewComplaintReport.setMaximumSize(new java.awt.Dimension(340, 25));
        JBViewComplaintReport.setMinimumSize(new java.awt.Dimension(340, 25));
        JBViewComplaintReport.setPreferredSize(new java.awt.Dimension(340, 25));
        JBViewComplaintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBViewComplaintReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(JBViewComplaintReport, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jCreateandPrintDocs, "Crear otros documentos");
        jCreateandPrintDocs.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jCreateandPrintDocs.setMaximumSize(new java.awt.Dimension(340, 25));
        jCreateandPrintDocs.setMinimumSize(new java.awt.Dimension(340, 25));
        jCreateandPrintDocs.setPreferredSize(new java.awt.Dimension(340, 25));
        jCreateandPrintDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateandPrintDocsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jCreateandPrintDocs, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBTratActivitiesRegister1, "Crear PDF de registro de activ. de tratamiento");
        jBTratActivitiesRegister1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jBTratActivitiesRegister1.setMaximumSize(new java.awt.Dimension(340, 25));
        jBTratActivitiesRegister1.setMinimumSize(new java.awt.Dimension(340, 25));
        jBTratActivitiesRegister1.setPreferredSize(new java.awt.Dimension(340, 25));
        jBTratActivitiesRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTratActivitiesRegister1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPOperationsMenu.add(jBTratActivitiesRegister1, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPOperationsMenu);

        jPOperationsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Operación en curso", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPOperationsPanel.setMaximumSize(new java.awt.Dimension(1560, 1080));
        jPOperationsPanel.setMinimumSize(new java.awt.Dimension(1560, 1080));
        jPOperationsPanel.setPreferredSize(new java.awt.Dimension(1560, 1080));
        jSplitPane1.setRightComponent(jPOperationsPanel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTratActivitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTratActivitiesActionPerformed
        // TODO add your handling code here:
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Actividades de tratamiento", "tratamiento", "tratamiento.html");
        CLAllObjectList<String> ColumnsNames = new CLAllObjectList<>();
        ColumnsNames.add("Número ID");
        ColumnsNames.add("Cliente");
        ColumnsNames.add("Empresa");
        ColumnsNames.add("Código");
        ColumnsNames.add("Información adicional");
        ColumnsNames.add("Datos del responsable y otros");
        ColumnsNames.add("Datos del Delegado de protección de datos");
        ColumnsNames.add("Propósitos del tratamiento");
        ColumnsNames.add("Categorías de interesados");
        ColumnsNames.add("Categorías de datos");
        ColumnsNames.add("Tipo del tratamiento");
        ColumnsNames.add("Categorías de destinatarios");
        ColumnsNames.add("Paises destinatarios");
        ColumnsNames.add("Transferencias de datos internacionales");
        ColumnsNames.add("Límie temporal de retención de datos");
        ColumnsNames.add("Análisis de riesgos");
        ColumnsNames.add("Descripción del tratamiento");
        ColumnsNames.add("Sistemas de proceso de información");
        ColumnsNames.add("Salvaguardas de la información de datos internacional");
        ColumnsNames.add("OPperaciones de proceso de datos de ususario");
        ColumnsNames.add("Reclamaciones al responsable");
        ColumnsNames.add("Derechos legales");
        ColumnsNames.add("Base legal");
        Panel_TableDBManager CLOP = new Panel_TableDBManager("ccpd_treat_activity_creator", "treatactivity", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsNames, "Actividades de tratamiento");
        AddObjecttoOperationsPanel(CLOP);
//        jPOperationsPanel.add(PCWCR);
        //   jPOperationsPanel.repaint();
    }//GEN-LAST:event_jBTratActivitiesActionPerformed

    private void jBTratRisksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTratRisksActionPerformed
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Riesgos del tratamiento - listas de administración de riesgos", "tratamiento", "riesgostratamiento.html");
        Panel_TableDBManager CLOP = new Panel_TableDBManager("ccpd_treat_risks", "riskmanagementlist");
        AddObjecttoOperationsPanel(CLOP);
    }//GEN-LAST:event_jBTratRisksActionPerformed
    void AddObjecttoOperationsPanel(Component Cnt) {
        getjPBPBar().setValue(0);
        getjPOperationsPanel().removeAll();
        getjPBPBar().setValue(15);
        getjPOperationsPanel().invalidate();
        getjPBPBar().setValue(30);
        getjPOperationsPanel().setLayout(new FlowLayout());
        getjPBPBar().setValue(45);
        getjPOperationsPanel().add(Cnt);
        getjPBPBar().setValue(60);
        getjPOperationsPanel().setVisible(true);
        getjPBPBar().setValue(75);
        getjPOperationsPanel().validate();
        getjPBPBar().setValue(90);
        getjPOperationsPanel().repaint();
        getjPBPBar().setValue(100);
        UpdateInfoPanel();
        // DBManager.GetClientAndEnterpriseLists(ClientList,EnterpriseList);
    }
    private void jBClientOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClientOperationsActionPerformed
        // TODO add your handling code here:
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Operaciones con clientes", "operaciones", "operclientes.html");
        CLAllObjectList<String> ColumnsNames = new CLAllObjectList<>();
        ColumnsNames.add("Número ID");
        ColumnsNames.add("Nombre");
        ColumnsNames.add("Apellidos");
        ColumnsNames.add("Dirección");
        ColumnsNames.add("NIF");
        ColumnsNames.add("Región");
        ColumnsNames.add("Provincia");
        ColumnsNames.add("País");
        ColumnsNames.add("Localización");
        ColumnsNames.add("Código Postal");
        ColumnsNames.add("Teléfono");
        ColumnsNames.add("Fax");
        ColumnsNames.add("e-mail");
        ColumnsNames.add("Webpage");
        ColumnsNames.add("Su empresa");
        ColumnsNames.add("usuario o apodo");
        Panel_TableDBManager CLOP = new Panel_TableDBManager("ccpd_clients", "dbclients", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsNames, "Operaciones con clientes");
        AddObjecttoOperationsPanel(CLOP);

    }//GEN-LAST:event_jBClientOperationsActionPerformed

    private void jBEnterpriseOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnterpriseOperationsActionPerformed
        // TODO add your handling code here:
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Operaciones con empresas", "operaciones", "operempresas.html");
        CLAllObjectList<String> ColumnsNames = new CLAllObjectList<>();
        ColumnsNames.add("Número ID");
        ColumnsNames.add("Nombre del Administrador o Empresa");
        ColumnsNames.add("NIF empresa");
        ColumnsNames.add("Nombre del representante");
        ColumnsNames.add("Apellidos del representante");
        ColumnsNames.add("NIF");
        ColumnsNames.add("Dirección");
        ColumnsNames.add("Región");
        ColumnsNames.add("Provincia");
        ColumnsNames.add("País");
        ColumnsNames.add("Localización");
        ColumnsNames.add("Código Postal");
        ColumnsNames.add("Teléfono");
        ColumnsNames.add("Fax");
        ColumnsNames.add("e-mail");
        ColumnsNames.add("Webpage");
        ColumnsNames.add("cliente");
        //ColumnsNames.add("empresa");

        Panel_TableDBManager ENOP = new Panel_TableDBManager("ccpd_enterprises", "generaldata_treatmentmanager", PConfig.getActualClient().getsIDClient(), PConfig.getActualEnterprise().getsIDEnterprise(), ColumnsNames, "Operaciones con empresas");
        AddObjecttoOperationsPanel(ENOP);

    }//GEN-LAST:event_jBEnterpriseOperationsActionPerformed

    private void jBSecurityMeasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSecurityMeasuresActionPerformed
        // TODO add your handling code here:
        JPSecurity_Measures SECMEAS = new JPSecurity_Measures();
        AddObjecttoOperationsPanel(SECMEAS);;
    }//GEN-LAST:event_jBSecurityMeasuresActionPerformed

    private void jBTratActivitiesRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTratActivitiesRegisterActionPerformed
        // TODO add your handling code here:
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Actividades de tratamiento", "tratamiento", "tratamiento.html");
        Panel_TableDBManager CLOP = new Panel_TableDBManager("ccpd_treat_activity_creator", "treatactivity");
        AddObjecttoOperationsPanel(CLOP);
    }//GEN-LAST:event_jBTratActivitiesRegisterActionPerformed

    private void jBImpactEvaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImpactEvaluationActionPerformed
        Panel_TableDBManager CLOP = new Panel_TableDBManager("ccpd_lists", "list_impact_evaluation");
        AddObjecttoOperationsPanel(CLOP);
    }//GEN-LAST:event_jBImpactEvaluationActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed

        int ntf = AcceptInformation("¿Está seguro de que quiere salir del programa?");
        if (ntf == mconfyes) {
            getDefault().exit();
        }

    }//GEN-LAST:event_jBExitActionPerformed

    private void JBFillCompliantReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFillCompliantReportActionPerformed
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Rellenar nforme de cumplimiento", "infocumpli", "rellenacumpli.html");
        if (PConfig.isUserAuthenticated() == true && PConfig.isClientActivated() == true && PConfig.isEntityActivated() == true) {
            PFillingReportQuestions PFRQ = new PFillingReportQuestions();
            AddObjecttoOperationsPanel(PFRQ);
        } else {
            ShowDError("Debe dar de alta y seleccionar un cliente y una empresa para poder continuar ...");
        }
    }//GEN-LAST:event_JBFillCompliantReportActionPerformed

    private void JPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPersonActionPerformed
        // TODO add your handling code here:
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Personalización del programa", "personalizacion", "personalizacion.html");
        JPCustomization CLOP = new JPCustomization();
        AddObjecttoOperationsPanel(CLOP);
    }//GEN-LAST:event_JPersonActionPerformed

    private void jNSelectClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNSelectClientActionPerformed
        ClientSelection();
        UpdateInfoPanel();
    }//GEN-LAST:event_jNSelectClientActionPerformed

    private void JBSelectEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSelectEnterpriseActionPerformed
        EnterpriseSelection();
        UpdateInfoPanel();
    }//GEN-LAST:event_JBSelectEnterpriseActionPerformed

    private void JBViewComplaintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBViewComplaintReportActionPerformed
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Ver el informe de cumplimiento", "infocumpli", "createinfocumpli.html");
        if (PConfig.isUserAuthenticated() == true && PConfig.isClientActivated() == true && PConfig.isEntityActivated() == true) {
            PCreatingReportDocument PCWCR = new PCreatingReportDocument(PConfig.getActualClient());
            AddObjecttoOperationsPanel(PCWCR);
        } else {
            ShowDError("Debe dar de alta y seleccionar un cliente y una empresa para poder continuar ...");
        }
    }//GEN-LAST:event_JBViewComplaintReportActionPerformed

    private void jCreateandPrintDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateandPrintDocsActionPerformed
        PConfig.BackupHelpconfig();
        PConfig.setHelpConfig("Crear otros documentos", "creardocs", "creardocumentos.html");
        JPCreateOtherDocuments CAPDOC = new JPCreateOtherDocuments();
        AddObjecttoOperationsPanel(CAPDOC);;
    }//GEN-LAST:event_jCreateandPrintDocsActionPerformed

    private void jBTratActivitiesRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTratActivitiesRegister1ActionPerformed

        if (PConfig.isUserAuthenticated() == true && PConfig.isClientActivated() == true && PConfig.isEntityActivated() == true) {
            PConfig.BackupHelpconfig();
            PConfig.setHelpConfig("Actividades de tratamiento", "tratamiento", "vertratamiento.html");
            P8PdfManager pdfman = new P8PdfManager("Activityregister.pdf");
            pdfman.GeneratePDFTreatActivitiesRegister("Las medidas de seguridad se encuentran detalladas en un documento aparte pudiendo incluir listas de control de acceso, delegación de autorizaciones,"
                    + "medidas de seguridad alternativas, autorizaciones, encargado del tratamiento de datos,tratamiento externo de datos,"
                    + "descripción de los ficheros, medios digitales y documentos en papel,nombramientos, procedimientos de seguridad y procedimientos especiales de control de acceso.");
        } else {
            ShowDError("Debe dar de alta y seleccionar un cliente y una empresa para poder continuar ...");
        }
    }//GEN-LAST:event_jBTratActivitiesRegister1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBFillCompliantReport;
    private javax.swing.JButton JBSelectEnterprise;
    private javax.swing.JButton JBViewComplaintReport;
    private javax.swing.JButton JPerson;
    private javax.swing.JButton jBClientOperations;
    private javax.swing.JButton jBEnterpriseOperations;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBImpactEvaluation;
    private javax.swing.JButton jBSecurityMeasures;
    private javax.swing.JButton jBTratActivities;
    private javax.swing.JButton jBTratActivitiesRegister;
    private javax.swing.JButton jBTratActivitiesRegister1;
    private javax.swing.JButton jBTratRisks;
    private javax.swing.JButton jCreateandPrintDocs;
    private javax.swing.JButton jNSelectClient;
    private javax.swing.JProgressBar jPBPBar;
    private javax.swing.JPanel jPOperationsMenu;
    private javax.swing.JPanel jPOperationsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTAInfoTextPanel;
    // End of variables declaration//GEN-END:variables
    String sStatus = "sin autenticar";
    CL_Client ActualUser = new CL_Client();
    // HelpUtils HU = new HelpUtils();

    @Override

    public void componentOpened() {

        if (!PConfig.isUserAuthenticated()) {
            AuthenticateUserProcedure();
        } else {
            sStatus = " autenticado";
        }
        if (!PConfig.isClientActivated()) {
            if (PConfig.getiClientsNumber() > 0) {
                ShowDError("Debe dar de alta un cliente para poder continuar ...");
            } else {
                ShowDError("Debe seleccionar un cliente para poder continuar ...");
            }
        }
        if (!PConfig.isEntityActivated()) {
            if (PConfig.getiEnterprisesNumber() > 0) {
                ShowDError("Debe dar de alta una empresa para poder continuar ...");
            } else {
                ShowDError("Debe seleccionar una empresa para poder continuar ...");
            }
        }
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void AuthenticateUserProcedure() {
        // PConfig.setHelpConfig("Autenticación de usuario", "autenticacion", "autenticacion.html");
        boolean authenticated = false;
        while (!authenticated) {

            AuthenticationDialog AD = new AuthenticationDialog(WindowManager.getDefault().getMainWindow(), true);
            AD.setAlwaysOnTop(true);
            AD.setLocationRelativeTo(WindowManager.getDefault().getMainWindow());
            AD.setVisible(true);
            authenticated = AD.isUserAuthenticated();
            boolean result = AD.isCancelaction();
            if (authenticated || result) {
                if (authenticated) {
                    ActualUser = AD.getActualUser();
                    PConfig.setUserAuthenticated(true);
                }
                UpdateInfoPanel();
                break;
            }
        }

    }

    private void EnterpriseSelection() {

        Frame f = WindowManager.getDefault().getMainWindow();
        DListSelection DLS = new DListSelection(f, true, DListSelection.getiEntityDialogSelection());
        DLS.setLocationRelativeTo(f);
        DLS.setVisible(true);

    }

    private void ClientSelection() {

        Frame f = WindowManager.getDefault().getMainWindow();
        DListSelection DLS = new DListSelection(f, true, DListSelection.getiClientDialogSelection());
        DLS.setLocationRelativeTo(f);
        DLS.setVisible(true);

    }

    /**
     * @return the jPOperationsPanel
     */
    public javax.swing.JPanel getjPOperationsPanel() {
        return jPOperationsPanel;
    }

    /**
     * @param jPOperationsPanel the jPOperationsPanel to set
     */
    public void setjPOperationsPanel(javax.swing.JPanel jPOperationsPanel) {
        this.jPOperationsPanel = jPOperationsPanel;
    }

    /**
     * @return the jPBPBar
     */
    public javax.swing.JProgressBar getjPBPBar() {
        return jPBPBar;
    }

    /**
     * @param jPBPBar the jPBPBar to set
     */
    public void setjPBPBar(javax.swing.JProgressBar jPBPBar) {
        this.jPBPBar = jPBPBar;
    }

    public void UpdateInfoPanel() {
        if (PConfig.isUserAuthenticated()) {
            sStatus = " autenticado";
        } else {
            sStatus = " no autenticado";
        }
        String StatusInfo = "Usuario: " + ActualUser.getsNClient();
        StatusInfo = StatusInfo + "\nCliente: " + PConfig.getActualClient().getsNClient();
        StatusInfo = StatusInfo + "\nEmpresa: " + PConfig.getActualEnterprise().getsNEnterprise();
        StatusInfo = StatusInfo + "\nusuario " + sStatus;
        jTAInfoTextPanel.setText(StatusInfo);
    }

}
